### ISSUE TITLE
Rebalance Ancient Horns

### ISSUE THREAD

**Issue by MerpisMe** [FrozenBlock/WilderWild#100]
They're too strong lol

imo rarity doesn't really work well as a balance, and while you could argue that tridents go against this, tridents are still really not even all that good.

i think honestly instead of making them deal a ton of damage, we should instead make them deal a lot of knockback and a fair amount of damage

in addition to that, we could add back the enchantments to increase knockback or damage, but make them mutually exclusive to one another

**Comment by BluePhoenixLOL** [comment]
100!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by MerpisMe** [comment]
> 100!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

wauep

**Comment by BluePhoenixLOL** [comment]
also no they are useless with the cooldown

**Comment by BluePhoenixLOL** [comment]
> > 100!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 
> wauep

this is issue 100

**Comment by MerpisMe** [comment]
i know

**Comment by MerpisMe** [comment]
> also no they are useless with the cooldown

they're still way too powerful
like yeah there's the cooldown but that doesn't mean that they're any less overpowered

**Comment by AViewFromTheTop** [comment]
I personally think they remove a huge source of annoyance in mid/late-game, the annoyance of being forced to fight off tons of mobs that you KNOW you will overcome anyway
I'm sure there's a way to balance it, but I feel like doing so would also take away from the fun and add bloat in the process

**Comment by AViewFromTheTop** [comment]
they're literally half the reason i'm able to build on my server

**Comment by BluePhoenixLOL** [comment]
> they're literally half the reason i'm able to build on my server

wait server?

**Comment by MerpisMe** [comment]
> I personally think they remove a huge source of annoyance in mid/late-game, the annoyance of being forced to fight off tons of mobs that you KNOW you will overcome anyway
> I'm sure there's a way to balance it better, but I feel like doing so would also take away from the fun (or just add back that annoyance) and add bloat in the process

my main concern is the fact that you can get it early game and then break all progression
it's basically an easy way to defeat the wither and ender dragon in a very small amount of time

**Comment by BluePhoenixLOL** [comment]
they are resistant
the ender dragon has thick scale armor
and the wither, is just, like a wither

**Comment by MerpisMe** [comment]
a

idk i think it would still just make more sense if it did more knockback than damage since it's literally just a *loud sound*

**Comment by BluePhoenixLOL** [comment]
nah

**Comment by BluePhoenixLOL** [comment]
knockback is useless and annoying

**Comment by MerpisMe** [comment]
ok and

**Comment by AViewFromTheTop** [comment]
Based BluePheonix

**Comment by BluePhoenixLOL** [comment]
> Based BluePheonix

ITS XFRTREX I CANT FUCKIN CHANGE ITTT

**Comment by MerpisMe** [comment]
tell me why it's a good idea in the slightest to make it so that you can obtain the strongest weapon in the game within minutes of starting
because i honestly cannot see how that makes any sense

**Comment by BluePhoenixLOL** [comment]
Leave a comment
No file chosen
Attach files by dragging & dropping, selecting or pasting them.
Remember, contributions to this repository should follow our GitHub Community Guidelines.
Assignees
No one—
Labels
consensus
items
Projects
None yet
Milestone
No milestone
Development
 for this issue or link a pull request.
Notifications
Customize
You’re receiving notifications because you commented.
3 participants
@MerpisMe
@BluePhoenixLOL
@AViewFromTheTop

**Comment by BluePhoenixLOL** [comment]
shoot what was that, anyways i meant to say "do you mean the weakest weapon in the game?"

**Comment by MerpisMe** [comment]
> shoot what was that, anyways i meant to say "do you mean the weakest weapon in the game?"

you cannot be serious bro 
it is the strongest thing in the game in terms of base dps and its cooldown is still only like 30 seconds

**Comment by BluePhoenixLOL** [comment]
did you really just say ONLY 30 seconds

**Comment by BluePhoenixLOL** [comment]
ONLY?!

**Comment by MerpisMe** [comment]
30 seconds is nothing for how fucking strong it is bro have you even tried it against the wither

**Comment by BluePhoenixLOL** [comment]
also no it only does 2 crit hits of an unenchanted sword

**Comment by BluePhoenixLOL** [comment]
> 30 seconds is nothing for how fucking strong it is bro have you even tried it against the wither

yes i have there is way better options to kill it, like a sword

**Comment by BluePhoenixLOL** [comment]
smite 5

**Comment by AViewFromTheTop** [comment]
> tell me why it's a good idea in the slightest to make it so that you can obtain the strongest weapon in the game within minutes of starting
> because i honestly cannot see how that makes any sense

The thing is extremely hard to find in Ancient Cities, sometimes not even being in there
You’re telling me that the average player will find a city, go through every single chest, and leave completely unharmed within MINUTES of starting a new world 
The _average_ player
