### ISSUE TITLE
Sort Items *into* the creative inventory

### ISSUE THREAD

**Issue by MerpisMe** [FrozenBlock/WilderWild#102]
we need better creative menu organization lol

**Comment by Treetrain1** [comment]
i dont think we should port anything more than the datafixers
it would be hard to do + it just removes the point of using quilt instead of fabric

we could maybe have a quilt version of the mod we release alongside updates

**Comment by MerpisMe** [comment]
> i dont think we should port anything more than the datafixers it would be hard to do + it just removes the point of using quilt instead of fabric
> 
> we could maybe have a quilt version of the mod we release alongside updates

yeah the point is to make it so we dont have to maintain two separate versions, not to rule out quilt

**Comment by MerpisMe** [comment]
while i would totally like to work solely on quilt because it has more stuff, like i said, more people use fabric than quilt and thus our mod will probably not get many downloads if we only use quilt.. likewise, we could maybe look into possibly making our own sorting system *inspired* by quilt's instead of just porting it

**Comment by oliviathevampire** [comment]
Quilt does not AFAIK have a system for this

**Comment by MerpisMe** [comment]
> Quilt does not AFAIK have a system for this

wait what i've been lied to

**Comment by MerpisMe** [comment]
OK UPDATE, @Treetrain1 @AViewFromTheTop to do this we'd have to mixin world.item.CreativeModeTab.class, which should actually be super simple (just.. not enough for me to know how to do it :/)

**Comment by MerpisMe** [comment]
uh. nevermind actually, thats just the tab item display. i'll search some more

**Comment by MerpisMe** [comment]
ok i think it's actually world.item.Item.class

**Comment by AViewFromTheTop** [comment]
we'd need to mixin Items.class and somehow inject our own items before and after certain other items (like cypress before birch logs, blah blah blah)
definetely not worth doing

**Comment by MerpisMe** [comment]
> we'd need to mixin Items.class and somehow inject our own items before and after certain other items (like cypress before birch logs, blah blah blah) definetely not worth doing

if you could figure out how to set it up i wouldnt mind taking the time to sort them

**Comment by AViewFromTheTop** [comment]
Just tried, it results in said items just not showing up.
