### ISSUE TITLE
Ancient Horns in loot tables don't have Instrument NBT, thereby not working.

### ISSUE THREAD

**Issue by AViewFromTheTop** [FrozenBlock/WilderWild#104]

**Comment by BluePhoenixLOL** [comment]
uh oh

**Comment by BluePhoenixLOL** [comment]
oh well you just drop them and then pick them back up but thats still a bad bug, how do goat horns do it in outposts?

**Comment by BluePhoenixLOL** [comment]
duplicate of: https://github.com/FrozenBlock/WilderWild/issues/105
