### ISSUE TITLE
SUGGESTION: Make Powering Dripleaf's Stems also keep them from collapsing

### ISSUE THREAD

**Issue by MerpisMe** [FrozenBlock/WilderWild#108]
Basically, instead of only requiring the head of the plant to be powered to prevent it from collapsing, we can make it so that powering any part of it along the plant keeps it from collapsing.
I think this should actually be super simple, and it still baffles me that this hasn't already been implemented by mojang.

**Comment by AViewFromTheTop** [comment]
Your wish is my command!
