### ISSUE TITLE
Rework Config Screen using Cloth Config

### ISSUE THREAD

**Issue by MerpisMe** [FrozenBlock/WilderWild#110]
For starters, the way it's organized is immensely better than the one we have now. Also, it makes it waaaaay easier for us to set up the config stuff, requiring only two classes instead of the four or five we have now.

For an example of how to do it:
https://github.com/PinkGoosik/visuality/tree/1.19/src/main/java/visuality/config

**Comment by Treetrain1** [comment]
done but will do future changes
