### ISSUE TITLE
Instruments Broken + Other Usable Items break after using Ancient Horn

### ISSUE THREAD

**Issue by MerpisMe** [FrozenBlock/WilderWild#111]
- Instruments don't play their sound at all

After using an Ancient Horn, usable items no longer work;
- Foods cannot be fully eaten
- Drinks cannot be fully drunk
- Bows cannot be shot
- Crossbows cannot be shot
- Tridents cannot be thrown

**Comment by AViewFromTheTop** [comment]
Are you sure this is a WW issue because literally nothing should cause that

**Comment by MerpisMe** [comment]
idk i need some confirmation that this is actually happening

**Comment by MerpisMe** [comment]
> Are you sure this is a WW issue because literally nothing should cause that

also it cant be anything else because i dont have any other mods running on my dev environment

**Comment by AViewFromTheTop** [comment]
> > Are you sure this is a WW issue because literally nothing should cause that
> 
> also it cant be anything else because i dont have any other mods running on my dev environment

ModMenu

**Comment by MerpisMe** [comment]
> > > Are you sure this is a WW issue because literally nothing should cause that
> > 
> > 
> > also it cant be anything else because i dont have any other mods running on my dev environment
> 
> ModMenu

modmenu wouldn't affect that

**Comment by AViewFromTheTop** [comment]
is this fixed now

**Comment by Treetrain1** [comment]
> is this fixed now

Idk but for me goat horn and copper horn don’t work

**Comment by AViewFromTheTop** [comment]
> > is this fixed now
> 
> Idk but for me goat horn and copper horn don’t work

are you on the latest commit

**Comment by Treetrain1** [comment]
> > > is this fixed now
> > 
> > 
> > Idk but for me goat horn and copper horn don’t work
> 
> are you on the latest commit

No I am unable to test it right now
I’ll let you know the next time I test it

**Comment by MerpisMe** [comment]
i'll test it

**Comment by Treetrain1** [comment]
> No I am unable to test it right now I’ll let you know the next time I test it
yeah the looping sound for goat horns and copper horns just doesnt play

**Comment by Treetrain1** [comment]
oh tridents are broken for me now wtf

**Comment by Treetrain1** [comment]
i think its because of frozenlib

**Comment by MerpisMe** [comment]
yes because thats part of the issue

**Comment by MerpisMe** [comment]
it's not frozenlib, it only started like two days ago

**Comment by Treetrain1** [comment]
> it's not frozenlib, it only started like two days ago

i went to the 'freezing libraries' commit. didnt work
i went back one commit and it worked 

lol

**Comment by MerpisMe** [comment]
fuck you 
skill issue

**Comment by AViewFromTheTop** [comment]
> fuck you skill issue

not skill issue he's right

**Comment by MerpisMe** [comment]
@AViewFromTheTop update: this actually only happens after using an ancient horn
dying seems to reset this bug

**Comment by AViewFromTheTop** [comment]
> @AViewFromTheTop update: this actually only happens after using an ancient horn dying seems to reset this bug

did treetrain fix it on frozenlib's side because i think i forgot to reset the used item flag

**Comment by Treetrain1** [comment]
> > @AViewFromTheTop update: this actually only happens after using an ancient horn dying seems to reset this bug
> 
> did treetrain fix it on frozenlib's side because i think i forgot to reset the used item flag

yeah i fixed it
