### ISSUE TITLE
Replace Ancient Horns in loot tables with new Item to CRAFT Ancient Horns

### ISSUE THREAD

**Issue by MerpisMe** [FrozenBlock/WilderWild#113]
This will follow the design philosophy explained by kingbogz in [this thread](https://twitter.com/kingbdogz/status/1516875909575462913?s=20&t=Pg6IRNukhpdmQ9jRWdH2qg) regarding disc 5, and honestly, I think this would be a perfect solution to them being too easy to get and use. 
The idea is that we have some kind of new item that generates in place of ancient horns, and you would need some amount of that item PLUS a goat horn in order to craft the ancient horn. For starters, not only does it feel more challenging AND rewarding, but it also means that you have to explore more than just one chest to get it. 
I know the original consensus was that we didn't want it to be craftable, but I feel like making it craftable would seriously make it feel more worthwhile once you obtain it.

**Comment by MerpisMe** [comment]
Also, I think it'd fit in quite snugly with the fact that everything else you can get in ancient cities require you to find multiple pieces in order to construct them

**Comment by Treetrain1** [comment]
yes

**Comment by AViewFromTheTop** [comment]
Genius merp once again

**Comment by MerpisMe** [comment]
okay SO what should this item be?

**Comment by MerpisMe** [comment]
yknow what fuck it lets just make it a bingo card :trollface:

**Comment by Treetrain1** [comment]
Ancient Goat Skin

lol idk

**Comment by MerpisMe** [comment]
> Ancient Goat Skin
> 
> lol idk

i dont think it should be anything relating to horns or goats in general, since i really want to make them require a goat horn (or potentially a copper horn?? i like crafting trees, minecraft needs more crafting trees)

maybe we could make it "sculk ossein" and it'll be like the powdered and ground version of osseous sculk (since that's what ossein actually is)

**Comment by MerpisMe** [comment]
![image](https://user-images.githubusercontent.com/27739930/186557049-1f9a578b-fa8e-4701-944f-f4c3344fd6f2.png)
idk lol

**Comment by Treetrain1** [comment]
yeah the current ancient horn colors actually would fit if we went with copper horn + the sculk ossein

**Comment by Treetrain1** [comment]
the copper horn part being the top and the sculk ossein being the back
![image](https://user-images.githubusercontent.com/39657565/186558318-05e781b3-81d6-402c-b652-06e0566549d6.png)

**Comment by MerpisMe** [comment]
yeah maybe we have it be like, 3 sculk ossein, 3 echo shards, copper horn

**Comment by MerpisMe** [comment]
![image](https://user-images.githubusercontent.com/27739930/186559438-eb3d94a8-5d90-452c-a984-e6031c5220e4.png)

**Comment by AViewFromTheTop** [comment]
Btw I thought they were just gonna be horn fragments or something
Requiring players to have copper horns already is kinda time-wasting and frustrating, and kinda makes these feel not Ancient

**Comment by AViewFromTheTop** [comment]
Yeah seriously we just need horn fragments instead
What we’re doing atm just doesn’t feel right honestly

**Comment by MerpisMe** [comment]
> Yeah seriously we just need horn fragments instead
> What we’re doing atm just doesn’t feel right honestly

alright sure, though i do think we should include echo shards in the recipe since it's like you "recharge" the broken-but-now-repaired horn

**Comment by MerpisMe** [comment]
so, question; do we want to keep sculk ossein in for the reed and add in the horn fragments as well? i'm thinking it'll be something like this:
(O = sculk ossein, E = echo shard, F = horn fragment, G = gold ingot)
`[E] [E] [G]`
`[F] [F] [F]`
`[O] [F] [F]` (shapeless?)
i can see why you would be opposed to it since it may seem a little bloaty, but just an idea

**Comment by AViewFromTheTop** [comment]
Screw sculk ossein

**Comment by AViewFromTheTop** [comment]
Just horn shards and an echo shard

**Comment by MerpisMe** [comment]
aw ok

i was also brainstorming the possibility of us adding in like a "damaged horn" item that you'd need to craft with the additional horn shards (maybe 8?) to repair it, since i think that might be a bit clearer and a bit less of a carbon copy of what the other deep dark items are. i'm a bit hesitant on this one though.

**Comment by MerpisMe** [comment]
also, i think it would be neat if the ancient horn started off relatively weak and you could then upgrade it to how it is (or maybe stronger than how it is currently) with enchantments, HOWEVER, adding more enchantments increases the cooldown by 5 seconds per level of enchantment.

**Comment by AViewFromTheTop** [comment]
No damaged horn
It’ll just complicate things too much compared to vanilla’s philosophy, and literally just be an unstackable shard

**Comment by Xfrtrex** [comment]
https://www.youtube.com/watch?v=zA3dBWbR5-g ITS HERE

**Comment by AViewFromTheTop** [comment]
> https://www.youtube.com/watch?v=zA3dBWbR5-g ITS HERE

But I didn’t do anything with anyone in the last two years how am I a father
