### ISSUE TITLE
Datapack support request.

### ISSUE THREAD

**Issue by MagmaBro123** [FrozenBlock/WilderWild#115]
Support for https://www.planetminecraft.com/data-pack/the-ancient-city-overhaul/
and https://www.planetminecraft.com/data-pack/ancient-city-loot-improvements/.

Stone Chests don't spawn if you change the structures, and I'm not sure if the loot edits are compat. with this.

**Comment by AViewFromTheTop** [comment]
> Support for https://www.planetminecraft.com/data-pack/the-ancient-city-overhaul/ and https://www.planetminecraft.com/data-pack/ancient-city-loot-improvements/. Stone Chests don't spawn if you change the structures, and I'm not sure if the loot edits are compat. with this.

The loot edits are compatible. WilderWild also changes the directories for the edited parts of cities with Stone Chests, so they shouldn't be overriden by Datapacks unless structure files are placed under wilderwild instead of minecraft.

**Comment by AViewFromTheTop** [comment]
The changes WW makes to their directories actually make compat easier, since people who don't have the mod can still enjoy the datapack and people with WW can enjoy it with Stone Chests if the creator of the Datapack choses.

**Comment by AViewFromTheTop** [comment]
Impossible to fix on our side without completely re-registering Ancient Cities.
