### ISSUE TITLE
Shrieker Gargling is broken

### ISSUE THREAD

**Issue by MerpisMe** [FrozenBlock/WilderWild#117]
it's controlled by WorldRendererMixin.java. no idea why it'd have broken, but it did and i don't know when

**Comment by MerpisMe** [comment]
ok i've looked through every file that could've possibly broken it and i've found absolutely no reason for why it should be broken. wtf.

**Comment by MerpisMe** [comment]
it's nothing to do with LevelRendererMixin (previously called WorldRenderMixin)

**Comment by Treetrain1** [comment]
fixed
