### ISSUE TITLE
Sculk Spreading is completely random

### ISSUE THREAD

**Issue by MerpisMe** [FrozenBlock/WilderWild#118]
Starting from when we first migrated to mojmaps, sculk has been spreading way too much. To see this in action, simply kill a chicken near a catalyst, and observe that, rather than spreading a consistent amount of sculk like in vanilla, it either spreads way too much, or way too little sculk.

I think the issue here is that it doesn't actually check for how much exp the mob should have dropped, so it just chooses a random number of sculk to spread, for whatever reason. 

https://user-images.githubusercontent.com/27739930/186967357-2e3e37d8-207b-447d-9e1c-00e4c3fb59e2.mp4

**Comment by AViewFromTheTop** [comment]
i still have no idea what caused this

**Comment by Treetrain1** [comment]
fixed
