### ISSUE TITLE
Jellyfish Ideas

### ISSUE THREAD

**Issue by AViewFromTheTop** [FrozenBlock/WilderWild#119]
- Tickle with feathers to get a cloud of jelly (like dragon's breath) which can be bottled
- Multiple colours; different variants spawn in different biomes
  - Orange jellyfish spawn in dripstone caves?
  - Green jellyfish spawn in lush caves? (we'd have to increase the number of aquifers in lush caves if we do this.. which honestly i wouldn't be too unhappy about)
- Can be bred using coral fans/corals/sea pickles
- Could maybe pick coral fans/corals off of reefs, causing them to drop, which they will then eat
  - if the player picks it up before they can get it, the player will receive the coral, effectively enabling coral farms
- Renaming a jelly to "Jellyfish Jelly" causes it to use Spongebob jellyfish sounds :)

**Comment by AViewFromTheTop** [comment]
![D8D0686B-53B0-47E9-9736-9608C2613C92](https://user-images.githubusercontent.com/87103914/187054145-cefc1b91-e84f-4ce7-a7a2-92b521f75700.jpeg)

@MerpisMe

**Comment by MerpisMe** [comment]
ty

**Comment by AViewFromTheTop** [comment]
@MerpisMe I think a great reference for how they should look are the Bloopers in the first Mario- though these should be able to tilt a bit to the left and right.

**Comment by MerpisMe** [comment]
> @MerpisMe I think a great reference for how they should move are the Bloopers in the first Mario- though these should be able to tilt a bit to the left and right.

ho w do w e stop th em fro m ro t atting eve ry direction

**Comment by AViewFromTheTop** [comment]
> ho w do w e stop th em fro m ro t atting eve ry direction

mth.clamp

**Comment by MerpisMe** [comment]
updated with some new stuff @AViewFromTheTop

**Comment by MerpisMe** [comment]
oh oh what if frogs eating jellyfish made them drop something special as well @AViewFromTheTop

**Comment by Xfrtrex** [comment]
no frogs should not eat jellyfish, but turtles maybe? they eat jellyfish irl

**Comment by MerpisMe** [comment]
oooo

**Comment by AViewFromTheTop** [comment]
@MerpisMe are we adding jelly you can bottle or are we leaving that behind

**Comment by AViewFromTheTop** [comment]
Also idk about the coral fan thing since they don’t grow back naturally

**Comment by MerpisMe** [comment]
> Also idk about the coral fan thing since they don’t grow back naturally

alright so then maybe we should just have them eat sea pickles and then have sea pickles naturally regenerate?

**Comment by MerpisMe** [comment]
oh btw, jellyfish remain completely stationary after a little while when there's no player nearby (or a player in spectator mode). would it be possible to make them have more active wander goals? @AViewFromTheTop

**Comment by AViewFromTheTop** [comment]
meh we shouldn't make that stuff naturally regenerate

**Comment by AViewFromTheTop** [comment]
i personally don't get why they HAVE to actively eat something, literally no other mobs outside of sheep do that- and sheep have a use for that, regrowing their wool.

**Comment by MerpisMe** [comment]
> i personally don't get why they HAVE to actively eat something, literally no other mobs outside of sheep do that- and sheep have a use for that, regrowing their wool.

that's a fair point, i was sort of just throwing the idea out there. should we make them eat sea pickles though? those are renewable and they still loosely fit what jellyfish eat in real life

**Comment by MerpisMe** [comment]
however, foxes

**Comment by AViewFromTheTop** [comment]
> however, foxes

you're just listing a useless mob
we're trying to not make a useless mob

**Comment by MerpisMe** [comment]
and villagers :trollface:

**Comment by AViewFromTheTop** [comment]
> and frogs and piglins

what do piglins eat
and frogs give you another item in return
frogs actually have a REASON to eat things

**Comment by MerpisMe** [comment]
> what do piglins eat

they hunt and kill hoglins and then pick up the meat

**Comment by AViewFromTheTop** [comment]
> and villagers :trollface:

i'm sure i would eat too if i had the same reason as them

**Comment by AViewFromTheTop** [comment]
villagers eat because it's weird for a grown frickin steve to shove food in their mouths

**Comment by AViewFromTheTop** [comment]
piglins, i have no idea

**Comment by MerpisMe** [comment]
OH and axolotls
i'm noticing a pattern here

**Comment by AViewFromTheTop** [comment]
> OH and axolotls i'm noticing a pattern here

they don't eat they just kill

**Comment by MerpisMe** [comment]
> > OH and axolotls i'm noticing a pattern here
> 
> they don't eat they just kill

i mean yeah but it's implied that they do it to eat, but because they eat live fish irl it would be weird for them to just swallow a fish whole (though.. that would be interesting. maybe that's what the point of that open mouth texture was)
axolotls irl dont just kill fish for no reason lol

**Comment by MerpisMe** [comment]
anyway, i was brainstorming earlier and i came up with an idea about jellyfish that spawn in the cave biome
we could rename them to "pearlescent jellies" or something like that and then have them render a quaternion that uses the firework "glow" texture (or make a similar texture), so it looks like they're glowing. may not be very vanilla though. i do kind of wish that mojang would do that sort of thing.

**Comment by AViewFromTheTop** [comment]
i had the same idea about the name
As for the quaternion, maybe that could just replace that "inside" part of them- though, we'd have to make pearlescents a separate entity type

**Comment by AViewFromTheTop** [comment]
actually the quaternion wouldn't scale properly with the body, so nvm

**Comment by MerpisMe** [comment]
> actually the quaternion wouldn't scale properly with the body, so nvm

yeah i was thinking of it as more of just a generic bloom effect, it could be just a bit bigger than the body itself as to not be overwhelmingly obstructive
though, would we really have to make them a separate entity? we could probably just make it use an empty texture with the other variants or something like that, or we could just make it part of the entity model itself and have it face the camera (which i believe is possible to do), and have it just grab the glow texture from a spot on the entity texture

**Comment by AViewFromTheTop** [comment]
@MerpisMe i gotta be honest, the jellyfish eating stuff is like adding sponges as entities to filter plankton in minecraft
plankton would literally be useless and literally just lag the ever-living FUCK out of the game, and it's even more insulting that they'd just dissapear when they touch sponges
jellies don't need to eat anything

**Comment by MerpisMe** [comment]
> @MerpisMe i gotta be honest, the jellyfish eating stuff is like adding sponges as entities to filter plankton in minecraft plankton would literally be useless and literally just lag the ever-living FUCK out of the game, and it's even more insulting that they'd just dissapear when they touch sponges jellies don't need to eat anything

no i know they shouldnt eat anything on their own, but i do think we should make it so you can *feed* them to breed them, because, honestly, baby jellyfish would be fucking adorable

**Comment by AViewFromTheTop** [comment]
> no i know they shouldnt eat anything on their own, but i do think we should make it so you can _feed_ them to breed them, because, honestly, baby jellyfish would be fucking adorable

ugh i hate how breeding works in minecraft it's so ANNOYING

**Comment by MerpisMe** [comment]
> we could probably just make it use an empty texture with the other variants or something like that, or we could just make it part of the entity model itself and have it face the camera (which i believe is possible to do), and have it just grab the glow texture from a spot on the entity texture

(this would also make it scale with the body if we do choose to do it)

**Comment by AViewFromTheTop** [comment]
no we're not doing a quaternion

**Comment by MerpisMe** [comment]
> no we're not doing a quaternion

sad

but i'd really like to somehow figure out how we can make pearlescent jellies brighter than other jellies. if we can disable face shading on them that would probably work well. maybe not, idk. i think minecraft's rendering engine really shits all over how pretty jellyfish could look, which really sucks

**Comment by AViewFromTheTop** [comment]
merp when she wants garbage minecraft classic lightmaps to be readded

**Comment by MerpisMe** [comment]
> merp when she wants garbage minecraft classic lightmaps to be readded

oK FINE what if we could figure out how to make the lightmap multiply the colours of the jellies when shading instead of just overlaying black at varying opacity
that's totally out of all of our abilities i know but its just a thought
i just hate the fact that minecraft shades things using progressive levels of black instead of hueshifting

**Comment by MerpisMe** [comment]
or what if we could just reduce the intensity of the lightmap on jellies
fuCK

**Comment by AViewFromTheTop** [comment]
ok merp i have thoughts to attend to

**Comment by MerpisMe** [comment]
![FCDC7BFE-72C8-46E7-B5D9-B8CF236E2289](https://user-images.githubusercontent.com/27739930/187539180-1084ea98-2700-4026-8c26-3473db46103f.png)

**Comment by AViewFromTheTop** [comment]
@MerpisMe i think the bucket should have pink jelly by default

**Comment by MerpisMe** [comment]
> @MerpisMe i think the bucket should have pink jelly by default

i agree

also what are your thoughts on the multiple colour variants spawning randomly

**Comment by AViewFromTheTop** [comment]
> also what are your thoughts on the multiple colour variants spawning randomly

sure why not

**Comment by AViewFromTheTop** [comment]
@MerpisMe i really don't like the new colors
scarlet and blue are fine, but the rest (even pink... was it changed..?) are such weird neon-dull colors and it makes my eyes hurt

**Comment by AViewFromTheTop** [comment]
@MerpisMe btw, I think the jelly colours should match those of the coral reefs- blue, pink, purple, red, and yellow- maybe green can stay, just for cosmetic reasons.
yellow would be the merp jellyfish: https://www.aquariumofpacific.org/onlinelearningcenter/species/egg_yolk_jelly1?adlt=strict&toWww=1&redig=BF1FA39D3F1F45B59601E272DDC60EEA

**Comment by MerpisMe** [comment]
> @MerpisMe btw, I think the jelly colours should match those of the coral reefs- blue, pink, purple, red, and yellow- maybe green can stay, just for cosmetic reasons.

sounds good, i just picked a few random colours and went with them so they weren't by any means final lol
> yellow would be the merp jellyfish: https://www.aquariumofpacific.org/onlinelearningcenter/species/egg_yolk_jelly1?adlt=strict&toWww=1&redig=BF1FA39D3F1F45B59601E272DDC60EEA

suck my

**Comment by AViewFromTheTop** [comment]
> sounds good, i just picked a few random colours and went with them so they weren't by any means final lol

ok

> suck my

well i guess i'd have to say i sucked eggs in highschool unlike squidward
