### ISSUE TITLE
Gargling Shriekers emit Floating Sculk Bubbles

### ISSUE THREAD

**Issue by MerpisMe** [FrozenBlock/WilderWild#122]
ok this is a bad mockup because the /particle command is garbage, but imagine how cool this would be if the bubbles weren't travelling at mach 5 and they stayed longer + had a more dynamic trajectory (basically just clone how echoers did it but make it continuous)

https://user-images.githubusercontent.com/27739930/187057102-83c92d4c-0e1b-45a5-9755-d2c3b87355ff.mp4

**Comment by MerpisMe** [comment]
actually just make it like how it worked in accurate sculk except replace the bubbles with floating sculk bubbles

**Comment by Treetrain1** [comment]
yes

**Comment by MerpisMe** [comment]
@AViewFromTheTop could you try to get this working

**Comment by MerpisMe** [comment]
can we try to do this before we release 1.1 (:
