### ISSUE TITLE
Unique Sky + Fog Colours for Lush Caves, Dripstone Caves, Deep Dark

### ISSUE THREAD

**Issue by MerpisMe** [FrozenBlock/WilderWild#123]
i think we very briefly talked about doing this at one point, but it probably fell between the cracks
in any case, it'd be nice to have, since for starters being able to see the bright daylight sky whilst in the deep dark seriously ruins the experience

**Comment by AViewFromTheTop** [comment]
hi merp
idk if you saw but i got the jelly animation done, the only things you have to do now are make the jellyfish bucket texture and throw together a sound for releasing them from buckets

**Comment by Xfrtrex** [comment]
merp is redoing jellyfish model

**Comment by MerpisMe** [comment]
> hi merp idk if you saw but i got the jelly animation done, the only things you have to do now are make the jellyfish bucket texture and throw together a sound for releasing them from buckets

yeah i saw, i'm working on actually improving the textures for the jellies in general, so you caught me at a pretty good time
also i'm gonna tweak the animation just a tiny bit since they're squashed vertically when idle

**Comment by MerpisMe** [comment]
> merp is redoing jellyfish model

i could've said that, and no i'm not, i just added a single cube to it lol

**Comment by Xfrtrex** [comment]
> > hi merp idk if you saw but i got the jelly animation done, the only things you have to do now are make the jellyfish bucket texture and throw together a sound for releasing them from buckets
> 
> yeah i saw, i'm working on actually improving the textures for the jellies in general, so you caught me at a pretty good time also i'm gonna tweak the animation just a tiny bit since they're squashed vertically when idle

no they dont just they just get stuck how the base size is when not moving

**Comment by MerpisMe** [comment]
> > > hi merp idk if you saw but i got the jelly animation done, the only things you have to do now are make the jellyfish bucket texture and throw together a sound for releasing them from buckets
> > 
> > 
> > yeah i saw, i'm working on actually improving the textures for the jellies in general, so you caught me at a pretty good time also i'm gonna tweak the animation just a tiny bit since they're squashed vertically when idle
> 
> no they dont just they just get stuck how the base size is when not moving

oh you're right. that should actually be a pretty easy fix

**Comment by MerpisMe** [comment]
wait, no no, when their x and z scale is normal, their y scale isn't. that's what i'm talking about

**Comment by AViewFromTheTop** [comment]
ehhhh idk about changing the model itself
as for them squishing when they die, that's the reason i made the cos negative
it looks much better than them doing the "push" thing

**Comment by AViewFromTheTop** [comment]
oh you said idle not when they die

**Comment by MerpisMe** [comment]
> ehhhh idk about changing the model itself 

don't worry, you'll like it

**Comment by AViewFromTheTop** [comment]
bluepheonix is right, how their size is stuck at what it previously was when they stop moving

**Comment by Osmiooo** [comment]
LMFAO BLUEHPEONIX

**Comment by MerpisMe** [comment]
> > ehhhh idk about changing the model itself
> 
> don't worry, you'll like it

![image](https://user-images.githubusercontent.com/27739930/187093087-90c8887c-2fe2-4288-b94b-59d1241b2dde.png)

**Comment by Xfrtrex** [comment]
> bluepheonix is right, how their size is stuck at what it previously was when they stop moving

STOP CALLING ME THAAAAAAAAAT

**Comment by Osmiooo** [comment]
> > bluepheonix is right, how their size is stuck at what it previously was when they stop moving
> 
> STOP CALLING ME THAAAAAAAAAT

ok bluephoenixlol

**Comment by AViewFromTheTop** [comment]
> ok.. can someone set this up for me so i can do it @Treetrain1 @AViewFromTheTop i know the fog colours and water colours are part of the same method, so i think this should be pretty simple? should just be a mixin in the biome registry

I don't think this should be added. Anyone can make a big hole in the ground and cave biomes can rarely generate on the surface, which will end up looking 10 times more broken than what we currently have.
As for water colours, I don't like when random non-water-based biomes have unique colours.

**Comment by Treetrain1** [comment]
> > ok.. can someone set this up for me so i can do it @Treetrain1 @AViewFromTheTop i know the fog colours and water colours are part of the same method, so i think this should be pretty simple? should just be a mixin in the biome registry
> 
> I don't think this should be added. Anyone can make a big hole in the ground and cave biomes can rarely generate on the surface, which will end up looking 10 times more broken than what we currently have. As for water colours, I don't like when random non-water-based biomes have unique colours.

Deep Dark?

**Comment by AViewFromTheTop** [comment]
> Deep Dark?

People can build massive holes in the ground to do that. Perhaps we can get away with only that biome, and that's IT.

**Comment by Treetrain1** [comment]
> > Deep Dark?
> 
> People can build massive holes in the ground to do that. Perhaps we can get away with only that biome, and that's IT.

i mean wouldnt it just be the same as what we did for TWM?

**Comment by AViewFromTheTop** [comment]
> I don't think this should be added. Anyone can make a big hole in the ground and cave biomes can rarely generate on the surface, which will end up looking 10 times more broken than what we currently have. As for water colours, I don't like when random non-water-based biomes have unique colours.

@MerpisMe
