### ISSUE TITLE
1.18.X backport please

### ISSUE THREAD

**Issue by dlfnn** [FrozenBlock/WilderWild#129]
Really good mod, better if there is 1.18.2 version <3

**Comment by Treetrain1** [comment]
This is unfortunately (almost) impossible to do because the mod is directly focused on the wild update.
It is possible if we utilize a backport mod but I'm not sure how we would do that.

**Comment by MerpisMe** [comment]
even if we could utilize a backport mod we would have to refactor a bunch of our code to work in 1.18, since there were quite a number of code changes in 1.19

**Comment by dlfnn** [comment]
I don't know whether this would help, but there is a backport mod to 1.18:
https://github.com/ItsBlackGear/TheWildBackport-Master

**Comment by MerpisMe** [comment]
> I don't know whether this would help, but there is a backport mod to 1.18:
> https://github.com/ItsBlackGear/TheWildBackport-Master

maybe? even if we could get it working it's not up there as one of our priorities. we optimally want to get the mod to feature-completion before porting it to anything else
