### ISSUE TITLE
rgb jellies

### ISSUE THREAD

**Issue by MerpisMe** [FrozenBlock/WilderWild#131]
naming a jellyfish something special could make it switch to a solid greyscale colour and have it cycle through the rainbow using the same code as sheep. making it become solid would make it so we don't have to worry about making a new renderlayer

**Comment by Treetrain1** [comment]
jeb_

**Comment by Treetrain1** [comment]
> jeb_

no actually lets do
merp_

**Comment by Treetrain1** [comment]
so

**Comment by Treetrain1** [comment]
so..

**Comment by MerpisMe** [comment]
i think in order to do this we'd have to make a new rendertype so idk

**Comment by AViewFromTheTop** [comment]
Closing since it works- we just need small improvements which aren't important atm-
