### ISSUE TITLE
Glaciers

### ISSUE THREAD

**Issue by LIUKRAST** [FrozenBlock/WilderWild#133]
I mean, you know 
![image](https://user-images.githubusercontent.com/73425030/188291340-e4a30e31-59a1-41bb-ae37-d8806f20d569.png)
![image](https://user-images.githubusercontent.com/73425030/188291348-7a8cccae-eb98-418e-bfe8-762c546db25c.png)

imma code that if everyone accepts it

**Comment by Treetrain1** [comment]
no

**Comment by Osmiooo** [comment]
> no

explain yourself

**Comment by Treetrain1** [comment]
> > no
> 
> explain yourself

we must add freezers to minecraft before we do glaciers obviously

**Comment by LIUKRAST** [comment]
> > > no
> > 
> > 
> > explain yourself
> 
> we must add freezers to minecraft before we do glaciers obviously

i mean, imma add also freezer block then

**Comment by AViewFromTheTop** [comment]
I’d say go ahead, this is one of those things you can’t really judge until it’s actually added

**Comment by LIUKRAST** [comment]
> I’d say go ahead, this is one of those things you can’t really judge until it’s actually added

Thanks :3 I'm gonna provide some screenshots as soon as I release

**Comment by AViewFromTheTop** [comment]
One and a half years late
