### ISSUE TITLE
incompatibility with copper pipes mod

### ISSUE THREAD

**Issue by slovinsqui** [FrozenBlock/WilderWild#136]
when together, wilder wild asks me to install an older version of copper pipes mod, is this intended?

Simple copper pipes mod link: https://www.curseforge.com/minecraft/mc-mods/simple-copper-pipes

**Comment by Treetrain1** [comment]
What version of Wilder Wild and Simple Copper Pipes are you using?

**Comment by slovinsqui** [comment]
WilderWild-1.0.6-Fabric+1.19.jar

lunade-copper-pipe-1.10.jar

**Comment by Treetrain1** [comment]
Wilder Wild is incompatible with Simple Copper Pipes below 1.11 beta 5.
This is because Wilder Wild has integration for Simple Copper Pipes, but the tools made for integration wasn't made until the 1.11 betas.

**Comment by slovinsqui** [comment]
ooh I thought 1.10 was the most recent version of simple copper pipes because there is no v1.11 in Mc 1.19.0

**Comment by AViewFromTheTop** [comment]
> ooh I thought 1.10 was the most recent version of simple copper pipes because there is no v1.11 in Mc 1.19.0

This version supports WilderWild: https://www.curseforge.com/minecraft/mc-mods/simple-copper-pipes/files/3942765

**Comment by slovinsqui** [comment]
Thank you c:

**Comment by slovinsqui** [comment]
I didn´t notice v1.11 because it was inside the versions tab lol
