### ISSUE TITLE
Mushroom Stew upgrade

### ISSUE THREAD

**Issue by bfranacosta** [FrozenBlock/WilderWild#137]
I'd like to merge mushrooms and shelf fungus to craft the stew. Idk if it's intended or a bug, but for a future release it'd be nice.
![image](https://user-images.githubusercontent.com/104370510/188897402-aa477f39-c033-4d36-96fc-2ed95b683199.png)

**Comment by MerpisMe** [comment]
we're planning on making shelf fungi drop regular mushrooms if broken without silktouch or shears
