### ISSUE TITLE
Implement Shelf Fungi Loot Tables

### ISSUE THREAD

**Issue by MerpisMe** [FrozenBlock/WilderWild#139]
**Silktouch/Shears**
Stage 1: 1 Shelf fungus
Stage 2: 2 Shelf fungus
Stage 3: 3 Shelf fungus
Stage 4: 4 Shelf fungus

**No Silktouch/Shears**
Stage 1: 1-3 mushrooms (of respective type)
Stage 2: 2-5 mushrooms
Stage 3: 3-7 mushrooms
Stage 4: 4-9 mushrooms

**Comment by MerpisMe** [comment]
@AViewFromTheTop hey if you have time could you try to quickly implement this
i have no idea how loot tables work

**Comment by AViewFromTheTop** [comment]
> @AViewFromTheTop hey if you have time could you try to quickly implement this i have no idea how loot tables work

neither do i
we need to deploy the troops

**Comment by Osmiooo** [comment]
we have troops?

**Comment by AViewFromTheTop** [comment]
fuck this issue
