### ISSUE TITLE
Palm leaves decay

### ISSUE THREAD

**Issue by Soro335** [FrozenBlock/WilderWild#140]
Ok, so, for palm trees don't look like shit, we need to figure out how to make the vertical leaves not disappear. I have two suggestions: 

1. Add vertical leaves support 
2. Make leaves that will depend on the block (pic), this block does not allow the leaves to decaying in a radius of 6x6x6, drop saplings or coconuts\bananas
![image](https://user-images.githubusercontent.com/82042293/189202187-7c238847-ae25-4134-a234-fe97ea072846.png)

**Comment by AViewFromTheTop** [comment]
I think the easiest way to fix this (keep in mind I don't know for sure) is to let Palm Leaves check all diagonal leaves instead of only directly to the side.

**Comment by MerpisMe** [comment]
the picture related would be called a palm crown block. the textures for it are already in the files
