### ISSUE TITLE
Signs Texture Error

### ISSUE THREAD

**Issue by Bluyidark** [FrozenBlock/WilderWild#148]
Hi, I really like this mod but I encountered an issue where both baobab sign and cypress sign didn't render their texture properly. 
![2022-09-12_03 33 54](https://user-images.githubusercontent.com/112769984/189545875-05d18738-e848-421c-a003-f5100d8311f1.png)

**Comment by MerpisMe** [comment]
could you provide a log file and a list of any other mods you may be running?

**Comment by Treetrain1** [comment]
Also what version of Wilder Wild are you using?

**Comment by Bluyidark** [comment]
Here's the log, and I'm using version 1.0.5. Thanks for the help!
[latest.log](https://github.com/FrozenBlock/WilderWild/files/9543431/latest.log)

**Comment by Treetrain1** [comment]
Do you have any mod that speeds up resource loading?

**Comment by Bluyidark** [comment]
Maybe optifine? Though I did use sodium instead before, and it still faced the same issue.

**Comment by Treetrain1** [comment]
this can probably be fixed by disabling every compat or upgrading wilder wild to 1.0.6

**Comment by Bluyidark** [comment]
Gotcha, I will give it a try tomorrow!

**Comment by Bluyidark** [comment]
So I've tested it out, it seems that neither disabling every compat or upgrading to 1.0.6 do the work. Though, I spent a little more time to test and find out that the bug may caused by Expanded Storage mod which depended on Ellemes' Container Library. After I removed these 2 mods, the texture rendered out fine! : D

**Comment by MerpisMe** [comment]
that's odd. you might have to make an issue report on their end in that case
