### ISSUE TITLE
SUGGESTION: Wet Sponge drips dry on top of Pointed Dripstone

### ISSUE THREAD

**Issue by MerpisMe** [FrozenBlock/WilderWild#149]
i legitimately cannot see any reason why we shouldn't add this tbh, i think giving pointed dripstone more uses is always a plus. while, sure, it may be useless considering the nether is a better and faster alternative, i can see this being a niche kind of thing in the same way that fire aspect is to campfires as campfires are to furnaces.

**Comment by AViewFromTheTop** [comment]
This has been added thanks to TreeTrain.
