### ISSUE TITLE
SUGGESTION: Soul Fire makes unique ambient sounds

### ISSUE THREAD

**Issue by MerpisMe** [FrozenBlock/WilderWild#150]
This one could just be a toggle. I tried implementing this myself but i don't know what i'm doing, so it didn't work. the sound event for it is already in the files if anybody who knows how to implement it would like to try it out.
This could also extend to soul campfires, I'd just have to make a unique set of sounds for those

**Comment by Xfrtrex** [comment]
soul fire has sounds in MC Dungeons! i can send in the discord, its a loop sound, and i cant send sound files in github

**Comment by AViewFromTheTop** [comment]
> @AViewFromTheTop what are your thoughts on this idea btw would this maybe be a soundrevamp idea

YOOOOOOOOOO
honestly, no idea, but it'd probably work better there since WW really doesn't have anything to do w/ the nether
