### ISSUE TITLE
Fix Jellyfish Caves Placement

### ISSUE THREAD

**Issue by MerpisMe** [FrozenBlock/WilderWild#151]
They should be much smaller on average and generate ONLY under ocean biomes (but only sometimes generate at all)

**Comment by AlexTheDolphin0** [comment]
> alex when genshin

You're absolutely correct

**Comment by Osmiooo** [comment]
alex work
![merp_deletethis](https://user-images.githubusercontent.com/75801667/191849683-f7dcc724-7bc0-4ba7-bab6-08ad2b6601cb.png)

**Comment by MerpisMe** [comment]
> > alex when genshin
> 
> You're absolutely correct

we're planning on releasing 1.1 within the next week or so. we can cut that down to the next few days if you do this ONE thing. :)

**Comment by AlexTheDolphin0** [comment]
> > > alex when genshin
> > 
> > 
> > You're absolutely correct
> 
> we're planning on releasing 1.1 within the next week or so. we can cut that down to the next few days if you do this ONE thing. :)
ok got it

**Comment by AViewFromTheTop** [comment]
Should we close this now?

**Comment by AlexTheDolphin0** [comment]
I'll work on it ASAP. Haven't been feeling well recently(last week or so) but I've been feeling a bit better so I'll try and get something done.

**Comment by AViewFromTheTop** [comment]
> I'll work on it ASAP. Haven't been feeling well recently(last week or so) but I've been feeling a bit better so I'll try and get something done.

No, that's alright. I personally think their placement is fine, hence why I asked. Feel better soon.

**Comment by AViewFromTheTop** [comment]
alright can someone test and see if they have good placement now
cause honestly, idk what else we really have left to do

**Comment by AlexTheDolphin0** [comment]
> alright can someone test and see if they have good placement now cause honestly, idk what else we really have left to do

I'll try and test it, potentially make some adjustments.

**Comment by AlexTheDolphin0** [comment]
> > alright can someone test and see if they have good placement now cause honestly, idk what else we really have left to do
> 
> I'll try and test it, potentially make some adjustments.

Ok currently it seems to only generate under the ocean, and they're also really large. Seem to generate pretty rarely. Haven't done a lot of testing yet though.

**Comment by AViewFromTheTop** [comment]
That's what I've noticed, too
I do think we should register their parameters twice so we can have smaller blobs of them underground
