### ISSUE TITLE
Fallen Trees Parity 

### ISSUE THREAD

**Issue by Soro335** [FrozenBlock/WilderWild#153]
In bedrock edition, fallen trees look a little better than ours, can we do parity? 
![image](https://user-images.githubusercontent.com/82042293/192103657-57cfec19-4193-40ba-b56b-365ad586849a.png)
![image](https://user-images.githubusercontent.com/82042293/192103669-4b9055f9-b6d8-4653-bba9-08c1bceb690c.png)

**Comment by Soro335** [comment]
![image](https://user-images.githubusercontent.com/82042293/192103896-df142b00-a3c3-4577-9d70-3cd874a858b2.png)
another screenshot

**Comment by MerpisMe** [comment]
has this already been implemented?

**Comment by AViewFromTheTop** [comment]
i dont want to add this tbh do i have to

**Comment by AViewFromTheTop** [comment]
Technically achieved with snapped trees.
