### ISSUE TITLE
fix stone chest recipe

### ISSUE THREAD

**Issue by MerpisMe** [FrozenBlock/WilderWild#154]
Currently it overrides the furnace recipe
the ideas we were discussing were between just adding a chest to the middle of it, or doing that but also making it possible to craft with any kind of stone type (since it's called "stone chest" and not "deepslate chest")

**Comment by AViewFromTheTop** [comment]
how does it _override_ it i don't get why that'd happen

**Comment by AViewFromTheTop** [comment]
oh groups

**Comment by Treetrain1** [comment]
> how does it _override_ it i don't get why that'd happen

cobbled deepslate in a circle makes furnace

**Comment by Osmiooo** [comment]
![image](https://user-images.githubusercontent.com/75801667/192114698-376f4b7d-5e3a-4fa2-969a-49ccdaa10f3d.png)
furnace also has that craft

**Comment by AViewFromTheTop** [comment]
yeah i know i forgot about the GROUP thing with recipes ffs i'm not an idiot

**Comment by MerpisMe** [comment]
i honestly think just making it require a chest in the middle and making it work with all stone types is the best solution
again, we don't want this to be a *deepslate* chest, just a chest that's made of some kind of stone
i am still planning on making custom block sounds for them, i just havent thought about it

**Comment by AViewFromTheTop** [comment]
nah deepslate chest is better

**Comment by AViewFromTheTop** [comment]
otherwise a new texture would look like shit

**Comment by Osmiooo** [comment]
no not a new texture

**Comment by MerpisMe** [comment]
not a new texture, just a different recipe
i plan to change the sounds to distinguish it from deepslate because it was never my intention to make them inherently deepslate. otherwise we would've just called them deepslate chests.

**Comment by AViewFromTheTop** [comment]
can we consider this fixed now

**Comment by MerpisMe** [comment]
yea
