### ISSUE TITLE
Architectury Implementation

### ISSUE THREAD

**Issue by MerpisMe** [FrozenBlock/WilderWild#156]
further discussion on this should go in the comments here @AViewFromTheTop

**Comment by Treetrain1** [comment]
so whats up with architectury?

**Comment by MerpisMe** [comment]
we want to try to implement it since it allows us to port the mod to forge without doing nearly as much heavy lifting

**Comment by AViewFromTheTop** [comment]
Made obsolete by Sinytra Connector
