### ISSUE TITLE
Cave biome ambient loops persist after death

### ISSUE THREAD

**Issue by MerpisMe** [FrozenBlock/WilderWild#158]
**Description of the Bug Encountered**
Dying whilst in a cave biome that has an ambient loop will cause the ambient loop to continue throughout all biomes.

**Steps To Reproduce**
1. Go to a cave biome
2. Observe the ambient loop
3. Type /kill
4. The sound will continue playing after respawning

**Expected Behavior**
The loop would stop playing and continue once the player is in the biome

**Additional context**
 On a related note, if the loop is cancelled, for instance, via /stopsound or via turning the Ambient Sounds category volume all the way down and back up, the loop will NOT start again.

**THIS IS A VANILLA BUG**, i am not sure whether or not we'll be able to fix this.

**Comment by MerpisMe** [comment]
important thing to note-- this also happened with the nether ambience for a few snapshots until they fixed it, BUT there are still a few issues, most notably the issue where it does not continue after using /stopsound or turning the Ambient Sounds volume down and back up

**Comment by MerpisMe** [comment]
and now that i think about it, there's a good possibility that the way these work is by constantly playing the sound and changing the volume whenever the appropriate biome is entered, which might explain why these bugs are occuring (and why there's always at least like 4 sounds playing at once regardless of setting)

**Comment by AViewFromTheTop** [comment]
Why don’t we just make a custom ambient sound thing in FrozenLib if we can’t fix it

**Comment by Treetrain1** [comment]
wonder if 1.20 fixed this by any chance

**Comment by AViewFromTheTop** [comment]
anyway i reviewed the code a week or two ago for the dynamic biome sounds and i see no reason it shouldn't be fixed unless there's a new instance of the sound tracker made each time the player respawns, which would be stupid but possible since it isn't static (though doesn't it just keep one instance of the player..?)
anyway
i would test in 1.20 if i were you

**Comment by Treetrain1** [comment]
definitely still present in 1.20

**Comment by AViewFromTheTop** [comment]
> definitely still present in 1.20

hmmmmm
must be a

**Comment by Treetrain1** [comment]
> > definitely still present in 1.20
> 
> hmmmmm must be a

yeah probably a

**Comment by AViewFromTheTop** [comment]
Closing as this is a vanilla issue
