### ISSUE TITLE
Add Termite stripping support for other mods' logs

### ISSUE THREAD

**Issue by MerpisMe** [FrozenBlock/WilderWild#159]
idk how this would work tbh but it would be neat

In addition to this, we could maybe add support for hollowed versions of other mods' logs.. we would just have to remove the center pixels and maybe add contrast to the side texture. could look into mods that do something similar to figure out how we can do it

**Comment by AViewFromTheTop** [comment]
who cares about other mods

**Comment by AViewFromTheTop** [comment]
> people who play with mods

well that's not me
i have no clue what logs would be included in this

**Comment by AViewFromTheTop** [comment]
i made the termite stuff EXTREMELY easy to control with tags and maps, so other modders should have no issue doing this on their own

**Comment by AViewFromTheTop** [comment]
either way, if this is even viable on our part, we should definitely wait until 1.1 is done

**Comment by MerpisMe** [comment]
i was thinking we would just add in code that automates it instead of adding a bunch of different mods' logs and stuff to it

**Comment by AViewFromTheTop** [comment]
> i was thinking we would just add in code that automates it instead of adding a bunch of different mods' logs and stuff to it

I saw something on the fabric wiki that says how to do it

**Comment by AViewFromTheTop** [comment]
> I saw something on the fabric wiki that says how to do it

nvm
anyone know of a mod that does it?

**Comment by Treetrain1** [comment]
> > I saw something on the fabric wiki that says how to do it
> 
> nvm anyone know of a mod that does it?

maybe EveryCompat?

**Comment by CamKablam** [comment]
> > > I saw something on the fabric wiki that says how to do it
> > 
> > 
> > nvm anyone know of a mod that does it?
> 
> maybe EveryCompat?

EveryCompat only has compatibility with whatever mods the creator has added compatibility with. Every block is coded in manually, and enabled when the corresponding mod is enabled. It would be difficult for Wilder Wild to add compatibility with every mod that adds logs, unless automation code is created somehow.

**Comment by Treetrain1** [comment]
maybe something like moonlight lib has the answer lol

**Comment by Treetrain1** [comment]
Yeah, could try adding Moonlight integration
They have stuff for model and texture generation
