### ISSUE TITLE
Cypress Signs and Stripped Cypress Logs do not drop anything

### ISSUE THREAD

**Issue by MerpisMe** [FrozenBlock/WilderWild#160]

**Comment by AViewFromTheTop** [comment]
for fucks sake i JUST fixed this under a month ago what the fuuuuuuck

**Comment by AViewFromTheTop** [comment]
yeah there's literally a loot table for stripped cypress logs
wtf is the problem i dont get it

**Comment by AViewFromTheTop** [comment]
are you sure this is on the latest commit

**Comment by MerpisMe** [comment]
ok nvm then

**Comment by Osmiooo** [comment]
merp forgot this was 1.0 issue

**Comment by AViewFromTheTop** [comment]
who reported it then

**Comment by MerpisMe** [comment]
i didnt know it was fixed osmio shut the fuck up

**Comment by Osmiooo** [comment]
> who reported it then

someone on the discord

**Comment by MerpisMe** [comment]
> who reported it then

someone on discord, i didn't realize it was fixed

**Comment by AViewFromTheTop** [comment]
ffs i thought someone went behind my back and unfixed it
