### ISSUE TITLE
Sculk Charges Use Worldgen-Only Tags In Non-Worldgen Scenarios

### ISSUE THREAD

**Issue by AViewFromTheTop** [FrozenBlock/WilderWild#161]
@Treetrain1 
We should probably just disable it at this point.

**Comment by Treetrain1** [comment]
😭

**Comment by AViewFromTheTop** [comment]
Well

**Comment by Treetrain1** [comment]
disable the non worldgen?

**Comment by AViewFromTheTop** [comment]
> disable the non worldgen?

Yeah
It works perfectly in worldgen, for some reason not in non-worldgen
