### ISSUE TITLE
Issue with REI addons

### ISSUE THREAD

**Issue by GermanArtur** [FrozenBlock/WilderWild#165]
Issue with one of these REI addons: Roughly Enough Loot Tables, Roughly Enough Proffessions, Roughly Enough Resources, Roughly Enough Trades.

One of these modifications breaks the launch of the world when Wilder Wild is installed

**Comment by Treetrain1** [comment]
Related to theorbtwo/RoughlyEnoughResources#67

**Comment by Treetrain1** [comment]
Issue on RER's side. Closing this
