### ISSUE TITLE
[1.19.2] Wilder Wilds breaking other mods adding to vanilla swamp biomes

### ISSUE THREAD

**Issue by TelepathicGrunt** [FrozenBlock/WilderWild#167]
### Steps to Fix
- [x] Replace all worldgen modification mixins with BiomeModifications 
- [x] Remove broken Jigsaw Structure mixin
- [x] Fix Structures Mixin
- [x] Fix Swamp biome parameters

---

A user reported to me that my mod, Repurposed Structures, was not spawning Swamp Villages in the vanilla swamp biome. After messing with their modpack for a while, I track the issue down to Wilder Wilds. With that mod on, the Swamp Villages will not show up on /locate command when using this datapack that forces it to only spawn in minecraft:swamp (normally spawns in both minecraft:swamp and minecraft:mangrove_swamp)
[swampbiomeonly.zip](https://github.com/FrozenBlock/WilderWild/files/9739515/swampbiomeonly.zip)
![image](https://user-images.githubusercontent.com/40846040/194713159-d60881f3-8130-4c0b-9a11-db17c6173cc1.png)
Command: **/locate structure repurposed_structures:village_swamp**

My guess is, somewhere along the way, Wilder Wilds is either nuking other mod's/datapack's structures from the swamp biome or is replacing the swamp biome with the wrong instead of it (builtin registry swamp biome vs dynamic registry swamp biome). I do not know exactly what Wilder Wilds is doing. The reason this is my theory is because I use vanilla's worldgen json system to add my structure to swamps. So whatever is being done, is breaking a vanilla system that was intended by mojang to allow structures to spawn in any biome.

I am looking into Wilder WIld's code and I see a few things of grave concern. First is that these mixins should not exist imo. Fabric API's Biome Modifier API can already remove placedfeatures from biomes safely. All biome modifications should be through `BiomeModifications` for best compatibility and prevent conflicts. But I suspect this isn't what is breaking my mod.
https://github.com/FrozenBlock/WilderWild/blob/master/src/main/java/net/frozenblock/wilderwild/mixin/worldgen/BiomeDefaultFeaturesMixin.java
Example of using BiomeModifications to remove the swamp tree which you seem to be trying to do. There is a second remove method that takes a generation step and a placed feature resource key that can remove even datapacked forms of the PlacedFeature. This is far cleaner than a mixin and just needs to be called at mod startup to register the changes you want to do at world startup later:
```java
BiomeModifications.create(new ResourceLocation(RepurposedStructures.MODID, "remove_trees_swamp"))
                .add(ModificationPhase.REMOVALS,
                        BiomeSelectors.includeByKey(Biomes.SWAMP),
                        (context) -> context.getGenerationSettings().removeBuiltInFeature(VegetationPlacements.TREES_SWAMP.value()));
```

This mixin too can be replaced as the context in BiomeModifiers grants access to the colors and effects and everything for a biome too.
https://github.com/FrozenBlock/WilderWild/blob/master/src/main/java/net/frozenblock/wilderwild/mixin/worldgen/OverworldBiomesMixin.java

A different mixin that's concerning is this one. This should not exist at all. What this is going to do is break the terrain adaption for any structure that reaches the 128 block radius. Structures layouts themselves are restricted to a 17x17 chunk area due to the chunk status for them. The terrain adaption goes around these pieces and could make the structure try to influence terrain beyond the 17x17 chunk limit if it was 128 block radius size. So what Mojang's original check here was doing was making sure that the specified structure max side + the terrain adaption size is less than 128 so that the structure's influence does not break the chunk status limit. 
https://github.com/FrozenBlock/WilderWild/blob/afe0ae20bb557ba5c2aefd083b400b527fd60709/src/main/java/net/frozenblock/wilderwild/mixin/worldgen/JigsawStructureMixin.java#L48

Despite my GitHub search, I could not find anything conclusive of how Wilder Wilds is preventing Swamp Villages from spawning in vanilla swamp biomes. I would strongly suggest switching out several of these mixins in favor of BiomeModifications instead and then testing to see if that resolves this issue. If not, a deeper search will need to be done. 

If you get stuck or need help, just ask me. A lot of these mixins would've been avoided by simply asking for help in a modding discord. if a person in a modding discord did suggest to use these mixins instead of BiomeModifications, that person really needs to be told to use BiomeModifications and only recommend BiomeModifications going forward for best compat for everyone involved.

Sorry if this is lengthy and a lot to put on you. I'm just deeply concerned from what I was seeing and wanted to make sure that Wilder Wilds gets put onto the best path forward

———
Edit:

for this mixin: https://github.com/FrozenBlock/WilderWild/blob/master/src/main/java/net/frozenblock/wilderwild/mixin/worldgen/StructuresMixin.java

Looks like just size and the last param is being modified. But that last param is already at maximum size for ancient cities because they are using bury terrain adaption. It should remain 116 and not touched.

This mixin will increase the structure size to 20 for ancient city like you want and is much cleaner and more compatible with other mods if they decide to modify this field too. Though other ancient city mods will more likely just use json to replace the structure's structure json itself which nukes your changes.
```java

@Mixin(Structures.class)
public class StructuresMixin {

    @ModifyArgs(
            method = "<clinit>",
            at = @At(value = "INVOKE", target = "Lnet/minecraft/world/level/levelgen/structure/structures/JigsawStructure;<init>(Lnet/minecraft/world/level/levelgen/structure/Structure$StructureSettings;Lnet/minecraft/core/Holder;Ljava/util/Optional;ILnet/minecraft/world/level/levelgen/heightproviders/HeightProvider;ZLjava/util/Optional;I)V", ordinal = 0),
            require = 0
    )
    private static void wilderWilds_increaseAncientCitySize(Args args) {
        int structureSize = 20;
        args.set(3, structureSize);
    }
}
```

**Comment by MerpisMe** [comment]
hey, thanks for the report! i've assigned a few people who might be able to fix this, so hopefully this should be resolved by the next minor release if not later. while i'm not entirely sure how accurate this is, there is a possibility that there is code left over in the files from when we were attempting to expand the 256x256 hard limit for structure sizes in hope of making ancient cities generate much larger on average. i'm pretty sure that's what the issue you've mentioned here was.

**Comment by AViewFromTheTop** [comment]
All that was removed after we found it was too complex for us- nothing about Cities is leftover.
Either way, I’m still taking a break and can’t help with this. I highly doubt this is anything strictly on our side, considering you can load up worlds with Terralith and it works perfectly fine.

**Comment by MerpisMe** [comment]
no no, the jigsawstructuremixin still remains, that's the issue

**Comment by MerpisMe** [comment]
alright, all that's left is to switch the other mixins to BiomeModifications

**Comment by TelepathicGrunt** [comment]
Hmm. Interesting. Good catch! Are you changing the swamp placement through terrablender? It could be some sort of odd bug in terrablender. If so, I’ll try and reproduce it in my dev environment by importing and using terrablender and report to them if so.

**Comment by Treetrain1** [comment]
> Hmm. Interesting. Good catch! Are you changing the swamp placement through terrablender? It could be some sort of odd bug in terrablender. If so, I’ll try and reproduce it in my dev environment by importing and using terrablender and report to them if so.

We are changing the placement through TerraBlender but we fallback onto changing it through mixins if the user does not have TerraBlender

**Comment by Treetrain1** [comment]
Swamps should be slightly larger now, hopefully allowing the structure to spawn in them more often.
