### ISSUE TITLE
Missing wilds' fungi do not generate in wilder wilds' modified old growth birch biomes

### ISSUE THREAD

**Issue by lxly9** [FrozenBlock/WilderWild#168]
Basically what the title says, it should work normally but as the dev of repurposed structures already said, the overwritten biome does not let othere mods' features generate. I just want the polypore mushrooms and the forgetmenots to generate ;-;

**Comment by MerpisMe** [comment]
this, alongside #167 should both be fixed following the latest commits
@Treetrain1 please confirm

**Comment by lxly9** [comment]
That would be really cool, as I love both mods! (Also unrelated but i adore your stone chest addition)
