### ISSUE TITLE
[Bug] Rendering issues with Sodium installed

### ISSUE THREAD

**Issue by lxly9** [FrozenBlock/WilderWild#175]
**Important**
Happens with and without Iris present, current java vm is graalvm 22.3.0

**Steps To Reproduce**
1. Place nematocyst
2. render issue

**Screenshots**
![2022-10-25_18 50 05](https://user-images.githubusercontent.com/102386118/197834727-cb57c296-a50d-45fa-b851-ed6058bc089b.png)

**Comment by MerpisMe** [comment]
this issue is 100% on sodium's end. we've tried manually overriding sodium's translucent shader to have a transparency check, but were unable to get it to work

**Comment by MerpisMe** [comment]
also, this shouldn't happen with only wilder wild installed. if you have a resource pack that modifies the translucent shader, that will also break the rendering

**Comment by lxly9** [comment]
Ah, okay I was pretty sure that it was either iris or sodium messing with it, though it only appeared recently

**Comment by lxly9** [comment]
I thought it maybe has something to do with graalvm since they also had entity rendering issues in 22.2.0

**Comment by lxly9** [comment]
I don't have any resource packs with translucency shaders installed too, i'll check with graalvm tomorrow

**Comment by MerpisMe** [comment]
alright, sounds good! feel free to make a bug report on sodium's end, though i can't foresee them fixing it for this mod alone. doesn't like they're super keen on doing that. a little while ago i chatted with the current maintainer (IMS) and he basically told me that we'd have to try to get it to work ourselves since sodium's core main shaders are hardcoded.

**Comment by lxly9** [comment]
yup, i heard they were trying to rewrite the translucent and water shaders for the next bug release as that is one of the main bugs that still persists. Chatted with pepper from continuity about it, really sucks that there is no alternative ir plugin for the fluid engine

**Comment by MerpisMe** [comment]
> yup, i heard they were trying to rewrite the translucency and water shaders for the next big release as that is one of the main bugs that still persists.

oh, nice! that's really good news- hopefully they'll consider making it easier for other mod devs to add their own blocks to the shaders, that'd be amazing.

> Chatted with pepper from continuity about it, really sucks that there is no alternative or plugin for the fluid engine

yepp, agreed

**Comment by AViewFromTheTop** [comment]
@MerpisMe would you be able to make models that follow the shape of the Nematocyst texture?
I’m thinking of adding a resource pack that shows up when Sodium’s installed with the shaped models to lessen this issue.

**Comment by MerpisMe** [comment]
> @MerpisMe would you be able to make models that follow the shape of the Nematocyst texture?
> I’m thinking of adding a resource pack that shows up when Sodium’s installed with the shaped models to lessen this issue.

i could try to i suppose yea

**Comment by Treetrain1** [comment]
kinda fixed with sodium 0.5.3 + nvidium 0.2.2

**Comment by Treetrain1** [comment]
actually reopening bc theres still a few issues left

**Comment by AViewFromTheTop** [comment]
> kinda fixed with sodium 0.5.3 + nvidium 0.2.2

wait they fixed the transparency stuff???
what does nvidium have to do with it btw

**Comment by AViewFromTheTop** [comment]
and what issues are left

**Comment by Treetrain1** [comment]
> > kinda fixed with sodium 0.5.3 + nvidium 0.2.2
> 
> wait they fixed the transparency stuff??? what does nvidium have to do with it btw

nvidium added transparency sorting

**Comment by AViewFromTheTop** [comment]
OK IM REDOWNLOADING THAT SHIT RIGHT NOW

**Comment by Treetrain1** [comment]
translucency sorting*

**Comment by AViewFromTheTop** [comment]
ALL I EVER WANTED
ALL I EVER NEEDED
IS HERE
IN MY ARMS
