### ISSUE TITLE
Enderman Anger Loop stacks up

### ISSUE THREAD

**Issue by Treetrain1** [FrozenBlock/WilderWild#177]
causes a sound overload

**Comment by AViewFromTheTop** [comment]
Ok do something about it then

**Comment by Treetrain1** [comment]
> Ok do something about it then

im trying lol

**Comment by AViewFromTheTop** [comment]
Seriously though do you have any idea why that specific scenario causes it cause honestly idfk why it would

**Comment by MerpisMe** [comment]
ender dragon is multiple entities

**Comment by Treetrain1** [comment]
i mean we could just like... make it not play it when the target is an ender dragon :trollface:

**Comment by Treetrain1** [comment]
wait sometimes it happens with other entities

**Comment by Treetrain1** [comment]
https://user-images.githubusercontent.com/39657565/198450761-2e4056bc-e87b-47a0-ac83-419a4ab66387.mp4

**Comment by AViewFromTheEnd** [comment]
Is this fixed now?

**Comment by AViewFromTheTop** [comment]
Is this fixed now?

**Comment by Treetrain1** [comment]
> Is this fixed now?

Not sure
I’ll test it today
