### ISSUE TITLE
Ticking Entity Crash for Fireflies

### ISSUE THREAD

**Issue by Batinobus** [FrozenBlock/WilderWild#178]
Whenever, I'm in a biome with fireflies (sadly my base is in a jungle), the fireflies cause my game to crash due to a ticking entity crash.

**Steps To Reproduce**
1. Go to biome with fireflies.
2. Game crashes.

**Expected Behavior**
Not crash.

**Screenshots**

(first screenshot is of game freezing)

![Desktop Screenshot 2022 10 28 - 21 33 05 20](https://user-images.githubusercontent.com/116882555/198567412-ea97fb20-dbde-44ad-ae4e-8d9acfbd430a.png)
![Desktop Screenshot 2022 10 28 - 21 34 03 86](https://user-images.githubusercontent.com/116882555/198567499-902e3701-9634-44ae-8bc0-9ff5a01078ad.png)

**Logs**
Not sure if this is right thing but
The game crashed whilst ticking entity
Error: java.lang.ClassCastException: class net.frozenblock.wilderwild.entity.Firefly cannot be cast to class net.minecraft.class_1321 (net.frozenblock.wilderwild.entity.Firefly and net.minecraft.class_1321 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @21a947fe)

**Additional context**
Only occurs in biomes with fireflies.
It may be due to my other mods and some compatibility causing a crash so I'll list em down:
Architectury
biomemakeover
capybara
chat-up
ChoiceTheorm's overhauled village 
Chubby Stuff
Cloth config
craftable sadles
deeperdark
duckling
echo-rod
ellemes container library
expanded storage
fabric api
fallingtree
forgetmechunk
geckolib
HopoBetterRuinedPortals
immserive-paintings
iris-mc
ironbows
keebszs battle towers
lambdynamiclights
litematica
lithium
malilib
megaparrot
modmenu
morefrogs
naturalist
noaddrepcost
no-enchant-cap
reeses sodium options
repurposed structures
roughly enough items
shinyhorses
shulkerboxtooltip
simplehats
simplyhouses
sklorlib
sodium
sprout
trinkets
wilderwild (good mod btw)
wraith waystones
youre in grave danger

**Comment by Batinobus** [comment]
Im not quite sure if I know what you mean.

**Comment by Treetrain1** [comment]
> Im not quite sure if I know what you mean.

Could you send the crash report found in ./minecraft/crash-reports where the crash happens in?

**Comment by Batinobus** [comment]
[crash-2022-10-28_21.33.03-server.txt](https://github.com/FrozenBlock/WilderWild/files/9892469/crash-2022-10-28_21.33.03-server.txt)

This should be it.

**Comment by Treetrain1** [comment]
Looks like its an issue on the Capybara mod's side.
They are declaring that the entity is tameable even though it is not.

**Comment by Batinobus** [comment]
Ah, ok. I'll remove the mod and let you know if the game no longer crashes.

Thank you for your help and time. :)

**Comment by Treetrain1** [comment]
this should be all thats needed in order to report the bug
```vsc
java.lang.ClassCastException: class net.frozenblock.wilderwild.entity.Firefly cannot be cast to class net.minecraft.class_1321 (net.frozenblock.wilderwild.entity.Firefly and net.minecraft.class_1321 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @21a947fe)
	at net.teamdraco.capybara.entity.ai.CapybaraAnimalAttractionGoal.method_6269(CapybaraAnimalAttractionGoal.java:28)```

**Comment by Batinobus** [comment]
Ok and can confirm that I was able to go the entire night without a crash around fireflies.

Once again, thank you for your help :)
