### ISSUE TITLE
warm river biome

### ISSUE THREAD

**Issue by MerpisMe** [FrozenBlock/WilderWild#179]
basically just a river type that generates in warmer areas. uses either a lighter blue or a yellowish colour for the water.

reasoning: frozen rivers exist, pristine blue water looks stupid in deserts and other hot biomes

pros: warm rivers, jacob satisfied

cons: none

in all seriousness this should actually be extremely simple to do, we'd just have to replace the river placement in hotter biomes with it

**Comment by Soro335** [comment]
Not in wilder wild
