### ISSUE TITLE
TerraBlender prevents Wilder Wild's Surface Rules from applying

### ISSUE THREAD

**Issue by Treetrain1** [FrozenBlock/WilderWild#183]
yeah

**Comment by mosharky** [comment]
Is this what's causing modded biomes to not generate for me? Disabling Wilder Wild's fixes it but it has worked for me before, so I'm assuming a mod I installed is conflicting to cause this.

**Comment by MerpisMe** [comment]
There must have been an update to terrablender recently that broke it

**Comment by MerpisMe** [comment]
shouldnt this be a bug report on terrablender's end and not ours

**Comment by Treetrain1** [comment]
> shouldnt this be a bug report on terrablender's end and not ours

Hmm
Yeah probably
I guess an issue can be created on their end and then this referenced

**Comment by MerpisMe** [comment]
@AViewFromTheTop would you mind applying the fix for oasis surface rules to everything else so we can close this?

**Comment by Treetrain1** [comment]
Fixed in 1.1.7
