### ISSUE TITLE
Firefly Spawnrate Config

### ISSUE THREAD

**Issue by mosharky** [FrozenBlock/WilderWild#186]
Other mods add their own rendition of the Firefly. This would be a good way to let modpack creators choose one. I currently have 4 different Firefly mobs in my modpack.

**Comment by MerpisMe** [comment]
we plan on potentially adding a server-sided config for firefly spawnrates, wherein it will be possible to outright disable them

**Comment by xSHXRKIEx** [comment]
Yes please, defs need entity configs for this mod

**Comment by MerpisMe** [comment]
closing as this has now been implemented in 1.1.3 and @Treetrain1 apparently doesn't know how to close an issue whenever he completes it :trollface: 
(that was me)
