### ISSUE TITLE
Conflict with Applied Energistics 2 wrong block placement [Quilt 1.19.2]

### ISSUE THREAD

**Issue by waddon1** [FrozenBlock/WilderWild#187]
**Description of the Bug Encountered**
After installing this mod, when placing certain blocks from AE2 on a server the block will switch to a completely different block.

**Steps To Reproduce**
1. Install Wilder Wild alongside AE2
2. Join a server with the mods installed
3. Place an AE2 block e.g. charger
4. AE2 block becomes another random block (Charger becomes a Potted Azalea. Sky Stone Chest becomes a Waterlogged Deepslate Brick Wall)

**Expected Behavior**
AE2 block places the correct block

**Screenshots**

**Logs**
There doesn't appear to be anything relevant in the logs

**Additional context**
N/A

**Comment by MerpisMe** [comment]
does the server have wilder wild installed?
if not, this is a known hug and there's not much we can do to fix it, you'll just have to remove wilder wild when joining the server.

**Comment by waddon1** [comment]
Yes it does

**Comment by MerpisMe** [comment]
okay, that's good to know. thanks for the report!

**Comment by Treetrain1** [comment]
What versions of Applied Energetics 2 and Wilder Wild does the server and client have?
Is there a version mismatch between the server and client?

**Comment by waddon1** [comment]
Both wilder wild 1.1.2 and AE2 12.8.5

**Comment by waddon1** [comment]
This doesn't appear to be happening now, however I believe it was caused by Eldritch Mobs. Despite me removing all mods apart from AE2 and Wilder Wild. I kept the same world file and it was still happening so it appeared that Eldritch Mobs may have tainted the world file on the server somehow I guess.
