### ISSUE TITLE
Incompatibility with C2ME

### ISSUE THREAD

**Issue by AntonIXO** [FrozenBlock/WilderWild#188]
**Description of the Bug Encountered**
Incompatibility with C2ME mod

**Steps To Reproduce**
1. Install Wilder Wild, Repurposed Structures, C2ME
2. Join game, break block to cause spawnAfterBreak method
3. Failed to light chunk, crash

Seems like problem with spawnAfterBreak method in HangingTendrilBlock class

**Logs**
https://pastebin.com/6q0ZK58X

**Comment by MerpisMe** [comment]
please reupload your log file, it has expired

**Comment by AntonIXO** [comment]
> please reupload your log file, it has expired

https://gist.github.com/AntonIXO/a658b1eb9e6e3bd2cb659053b65a31d0
