### ISSUE TITLE
Crash after updating to 1.1.3

### ISSUE THREAD

**Issue by waddon1** [FrozenBlock/WilderWild#189]
**Description of the Bug Encountered**
I updated the mod to 1.1.3 and now my modpack crashes on startup

**Steps To Reproduce**
1. Update from 1.1.2 to 1.1.3
2. Start up the game
3. Game crashes

**Expected Behavior**
Start game
No crash

**Screenshots**

**Logs**
[crash-2022-12-07_13.39.35.0339-quilt_loader.txt](https://github.com/FrozenBlock/WilderWild/files/10176556/crash-2022-12-07_13.39.35.0339-quilt_loader.txt)

**Additional context**

**Comment by Treetrain1** [comment]
fixed in 1.1.4
