### ISSUE TITLE
Crash on startup after updating to 1.1.4

### ISSUE THREAD

**Issue by jmadarg** [FrozenBlock/WilderWild#190]
**Description of the Bug Encountered**
Game crashes on startup after updating to 1.1.4 from 1.1.2

**Steps To Reproduce**
1. Update to 1.1.4
2. Try to launch the game
3. Game crashes

**Screenshots**

**Logs**

[crash-2022-12-07_21.35.55-client.txt](https://github.com/FrozenBlock/WilderWild/files/10181165/crash-2022-12-07_21.35.55-client.txt)
[crash-2022-12-07_21.35.53-server.txt](https://github.com/FrozenBlock/WilderWild/files/10181166/crash-2022-12-07_21.35.53-server.txt)
[latest.log](https://github.com/FrozenBlock/WilderWild/files/10181168/latest.log)

**Comment by Treetrain1** [comment]
Fixed in 1.1.5
