### ISSUE TITLE
Crash on startup after updating to 1.1.5

### ISSUE THREAD

**Issue by waddon1** [FrozenBlock/WilderWild#191]
**Description of the Bug Encountered**
Update from 1.1.2 to 1.1.5 and the game crashes on startup appears to be a conflict with prefab

**Steps To Reproduce**
1. Update from 1.1.2 to 1.1.5
2. Start game
3. Crash

**Expected Behavior**
Start game and not crash.

**Screenshots**

**Logs**
[crash-2022-12-09_14.25.09-client.txt](https://github.com/FrozenBlock/WilderWild/files/10195689/crash-2022-12-09_14.25.09-client.txt)

**Additional context**

**Comment by Treetrain1** [comment]
Seems you are using 1.1.4
This was fixed in 1.1.5

**Comment by waddon1** [comment]
Sorry turns out it doesn't create a crash report and that was my last one so here is the actual log with 1.1.5 
[latest (1).log](https://github.com/FrozenBlock/WilderWild/files/10198268/latest.1.log)

**Comment by Treetrain1** [comment]
the crash doesn’t seem to be related to wilder wild
could you try without the Not Enough Crashes mod and send the log generated without it?

**Comment by waddon1** [comment]
[latest (2).log](https://github.com/FrozenBlock/WilderWild/files/10198502/latest.2.log)

**Comment by Treetrain1** [comment]
According to the error, it is something to do with Quilt
Is there a crash report you could send?

**Comment by waddon1** [comment]
Yes it does appear to have given me one now
[crash-2022-12-09_22.14.27-client.txt](https://github.com/FrozenBlock/WilderWild/files/10198542/crash-2022-12-09_22.14.27-client.txt)

**Comment by Treetrain1** [comment]
I'm unable to find any mention of Wilder Wild in these logs,
but the error seems to come from Quilt Loading Screen's mixins

**Comment by waddon1** [comment]
I'll try removing that, but the crash only ever occurs when wilder wild is updated past 1.1.2

**Comment by waddon1** [comment]
That seems to have fixed it, weird.
