### ISSUE TITLE
Fix FrozenLib's mixins.

### ISSUE THREAD

**Issue by MagmaBro123** [FrozenBlock/WilderWild#193]
**Description of the Bug Encountered**
Title. Game crashes mentioning something related to Frozenlib. Whatever WilderWilds uses this for, its mixins cause a crash.

**Steps To Reproduce**
Install the mod with Fabric API (of course) and start the game.

**Expected Behavior**
The game to start.

**Screenshots**
N/A

**Logs**
https://pastebin.com/Zn2ts21i

**Additional context**
If you want my mod list, then here you go.
I noticed FrozenLib IS listed as a dependency (On Curse at least), however this issue still occurs even with that mod present as well.

![image](https://user-images.githubusercontent.com/51277766/209029769-2468de43-17c3-49e3-a4d3-cd8fb1b3b23a.png)

**Comment by Treetrain1** [comment]
I believe this is caused by a conflict with the "error_notifier" mod. Are you using Prism Launcher?

**Comment by MagmaBro123** [comment]
> 

Yes, I am.

**Comment by MagmaBro123** [comment]
@Treetrain1 Any info on this?

**Comment by MerpisMe** [comment]
error notifier is probably a built in mod or plugin that's part of prism launcher

**Comment by Treetrain1** [comment]
You are using Fabric API for 1.19.3 and Wilder Wild for 1.19.2

**Comment by Treetrain1** [comment]
No conflict, simply a version mismatch
