### ISSUE TITLE
1.19.3 build crash/incompatibility with quilt.

### ISSUE THREAD

**Issue by TheTrueTrident** [FrozenBlock/WilderWild#195]
**Description of the Bug Encountered**
Crash with quilt 1.19.3 using the newest 1.19.3 release.

**Steps To Reproduce**
1.  Download WilderWild and Quilt FABI
2. Launch the Quilt modloader with the mods installed.

**Expected Behavior**
I expected compatibility with Quilt since it was mentioned within the title. Wilder Wild [Fabric/Quilt]

**Logs**

[crash-2023-01-04_22.56.15-client.txt](https://github.com/FrozenBlock/WilderWild/files/10349192/crash-2023-01-04_22.56.15-client.txt)

**Comment by AViewFromTheEnd** [comment]
wouldn’t it be funny if I of all people fixed it

**Comment by AViewFromTheTop** [comment]
should be fixed in 1.2.
