### ISSUE TITLE
Crash for fabric 1.19.2 newest update of wilderwild

### ISSUE THREAD

**Issue by LadySunx** [FrozenBlock/WilderWild#196]
**Description of the Bug Encountered**
Sorry if I am completely on the wrong github to report a crash there was only two mods I updated which was minecells and wilderwild. After downgrading wilderwild I didn't crash when loading into the world. Once again sorry if I got the wrong place to post this the log doesn't give me any ideal on which mod it is. So, I am going based off of how I was able to load in after downgrading. 

**Steps To Reproduce**
1. update to the newest update of wilderwild beta load into the world and crash.
2. 
3. 
4. 

**Expected Behavior**

**Screenshots**

**Logs**
https://mclo.gs/Ophm5Ow
**Additional context**

**Comment by Treetrain1** [comment]
Could you test this again with 1.1.10?

**Comment by AViewFromTheTop** [comment]
Hello! Are you still facing this issue with the latest version?

**Comment by Treetrain1** [comment]
Closed for now
