### ISSUE TITLE
1.1.7 for 1.19.2 crash when loading into the world. 

### ISSUE THREAD

**Issue by LadySunx** [FrozenBlock/WilderWild#198]
**Description of the Bug Encountered**
Game crashes upon loading into the world
**Steps To Reproduce**
1. Update to 1.1.7 load into world and crash
2. 
3. 
4. 

**Expected Behavior**

**Screenshots**

**Logs**
This is the crash report 
https://mclo.gs/FNCLNXn

This is the latest log 
https://mclo.gs/vDdMFdD

**Additional context**

**Comment by MerpisMe** [comment]
this issue is being caused by twilight forest

**Comment by LadySunx** [comment]
So is the newest update of wilderwild incompatible with twilight forest?

**Comment by MerpisMe** [comment]
it might be, but it's not on our end. the logs you posted don't show wilder wild throwing any fatal errors

**Comment by LadySunx** [comment]
> it might be, but it's not on our end. the logs you posted don't show wilder wild throwing any fatal errors

Thing is i can play wilder wild 1.1.5 fine and load in fine but if i update wilder wild it the crash happens so would i need to report it to the twilight forest github?

**Comment by MerpisMe** [comment]
you would have to report it to them, yes
it's possible that something we changed in 1.1.7 is tripping something on twilight forest's end which causes the crash

**Comment by TropheusJ** [comment]
This is not Twilight Forest's fault. Frozen Lib has an unchecked cast that fails with TF [here](https://github.com/FrozenBlock/FrozenLib/blob/aa7f3afee9659be632750f619645d6598c43e1fe/src/main/java/net/frozenblock/lib/worldgen/surface/mixin/MinecraftServerMixin.java#L42). This is why you prefix your mixins, they will eventually end up in a stacktrace and attribution is very difficult.

**Comment by MerpisMe** [comment]
aha, noted. thanks for the info, apologies for the misunderstanding!

**Comment by AViewFromTheTop** [comment]
Just fixed.
Please be sure to report FrozenLib issues over there.
