### ISSUE TITLE
wilder wild crash with voidZ | 1.19.2 fabric

### ISSUE THREAD

**Issue by Surpos0** [FrozenBlock/WilderWild#199]
I think that this problem as with twilight forest

**Steps To Reproduce**
1. newest version of both mods
2. load any world
**Logs**
[crash-2023-01-20_08.42.04-client.txt](https://github.com/FrozenBlock/WilderWild/files/10464175/crash-2023-01-20_08.42.04-client.txt)

**Comment by AViewFromTheEnd** [comment]
Duplicate of #198, which has since been resolved.
