### ISSUE TITLE
Cypress Wood is Still Obtainable; Even if Cypress Biome is Disabled.

### ISSUE THREAD

**Issue by eithli** [FrozenBlock/WilderWild#200]
**Description of the Bug Encountered**

- Even if the cypress biome is disabled, cypress is still accessible through swamp huts.

**Steps To Reproduce**
1. Disable Cypress Biome.
2. Reload/or create a new world.
3. Locate a swamp hut.
4. Observe the bug.

**Expected Behavior**

- If the cypress biome is disabled via configuration, swamp huts should have any other wood set instead of cypress.

**Screenshots**

![2023-01-20_19 26 44](https://user-images.githubusercontent.com/109933737/213829166-03b49737-4a55-4623-bcd2-8807ba97c7bc.png)
![2023-01-20_19 26 57](https://user-images.githubusercontent.com/109933737/213829170-b2fe74d4-c211-4e24-8f5c-264ffd61f6aa.png)

**Logs**

[latest.log](https://github.com/FrozenBlock/WilderWild/files/10471147/latest.log)

**Comment by MerpisMe** [comment]
this might be better off if we just made a config option for custom swamp huts instead of tying it to the biome

**Comment by AViewFromTheTop** [comment]
done
