### ISSUE TITLE
Crash on world creation

### ISSUE THREAD

**Issue by benio1394** [FrozenBlock/WilderWild#201]
**Description of the Bug Encountered**
When I create the world the game immediately get crashed. I am using the newest 1.1.7 version for 1.19.2. After removing wilder wild everything is fine.

**Steps To Reproduce**
1. 
2. 
3. 
4. 

**Expected Behavior**

**Screenshots**

**Logs**
https://pastebin.com/q5KntyTa

**Additional context**

**Comment by Treetrain1** [comment]
Fixed in 1.1.8
