### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by SercraftGaming** [FrozenBlock/WilderWild#203]
**Description of the Bug Encountered**

Server crashes when i was walking in savanna biome

**Steps To Reproduce**
1. Be in savanna biome
2. Walk nearby baobab tree(probably)

**Logs**
java.lang.IllegalArgumentException: Cannot get property class_2746{name=hanging, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:air}
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at net.frozenblock.wilderwild.block.BaobabNutBlock.isHanging(BaobabNutBlock.java:132)
	at net.frozenblock.wilderwild.block.BaobabNutBlock.method_9558(BaobabNutBlock.java:78)

**Comment by SercraftGaming** [comment]
`---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 2023-01-29 14:24:36
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot get property class_2746{name=hanging, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:air}
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at net.frozenblock.wilderwild.block.BaobabNutBlock.isHanging(BaobabNutBlock.java:132)
	at net.frozenblock.wilderwild.block.BaobabNutBlock.method_9558(BaobabNutBlock.java:78)
	at net.minecraft.class_1542.handler$cnh001$tick(class_1542.java:3084)
	at net.minecraft.class_1542.method_5773(class_1542.java:103)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.handler$zjo000$modifiedRunLoop(MinecraftServer.java:4885)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at net.frozenblock.wilderwild.block.BaobabNutBlock.isHanging(BaobabNutBlock.java:132)
	at net.frozenblock.wilderwild.block.BaobabNutBlock.method_9558(BaobabNutBlock.java:78)
	at net.minecraft.class_1542.handler$cnh001$tick(class_1542.java:3084)
	at net.minecraft.class_1542.method_5773(class_1542.java:103)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)

-- Entity being ticked --
Details:
	Entity Type: minecraft:item (net.minecraft.class_1542)
	Entity ID: 1840
	Entity Name: Baobab Nut
	Entity's Exact location: -2270.45, 72.00, 273.35
	Entity's Block location: World: (-2271,72,273), Section: (at 1,8,1 in -142,4,17; chunk contains blocks -2272,-64,272 to -2257,319,287), Region: (-5,0; contains chunks -160,0 to -129,31, blocks -2560,-64,0 to -2049,319,511)
	Entity's Momentum: 0.00, -0.04, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.handler$zjo000$modifiedRunLoop(MinecraftServer.java:4885)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 2 total; [class_3222['Sashok45'/805, l='ServerLevel[world]', x=-915.42, y=64.00, z=395.49], class_3222['BaklaHHH'/1673, l='ServerLevel[world]', x=-2106.29, y=66.85, z=122.68]]
	Chunk stats: 9468
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,110,0), Section: (at 0,14,0 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 46367427 game time, 52788798 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 10896 (now: true), thunder time: 48739 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.handler$zjo000$modifiedRunLoop(MinecraftServer.java:4885)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 5.15.0-57-generic
	Java Version: 17.0.5, BellSoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), BellSoft
	Memory: 7866185120 bytes (7501 MiB) / 12884901888 bytes (12288 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 24
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
	Identifier: Intel64 Family 6 Model 63 Stepping 2
	Microarchitecture: Haswell (Server)
	Frequency (GHz): 2.40
	Number of physical packages: 2
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: ASPEED Graphics Family
	Graphics card #0 vendor: ASPEED Technology, Inc. (0x1a03)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: 0x2000
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 20247.82
	Virtual memory used (MB): 11882.98
	Swap memory total (MB): 12287.99
	Swap memory used (MB): 229.31
	JVM Flags: 2 total; -Xmx12288M -Xms12288M
	Fabric Mods: 
		another_furniture: Another Furniture 2.1.2-1.19.2
		architectury: Architectury 6.4.62
		bettervillage: Better village 2.0.0
		carpet: Carpet Mod 1.4.84
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		create: Create 0.5.0g-796+1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.5.0
			forgeconfigapiport: Forge Config API Port 4.2.6
				com_electronwill_night-config_core: core 3.6.5
				com_electronwill_night-config_toml: toml 3.6.5
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			porting_lib: Porting Lib 2.1.623+1.19.2
				forge_tags: Porting Lib Tags 3.0
				porting_lib_base: Porting Lib Base 2.1.623+1.19.2
					com_github_llamalad7_mixinextras: MixinExtras 0.1.1
					serialization_hooks: Serialization Hooks 0.3.26
				porting_lib_entity: Porting Lib Entity 2.1.623+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.623+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.623+1.19.2
				porting_lib_models: Porting Lib Models 2.1.623+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.623+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.623+1.19.2
					porting_lib_model_loader: Porting Lib Model Loader 2.1.623+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.623+1.19.2
					porting_lib_extensions: Porting Lib Extensions 2.1.623+1.19.2
						porting_lib_accessors: Porting Lib Accessors 2.1.623+1.19.2
						porting_lib_attributes: Porting Lib Attributes 2.1.623+1.19.2
							porting_lib_constants: Porting Lib Constants 2.1.623+1.19.2
						porting_lib_common: Porting Lib Common 2.1.623+1.19.2
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			registrate-fabric: Registrate for Fabric 1.1.44-MC1.19.2
		creativecore: CreativeCore (Fabric) 2.9.3
		creeperoverhaul: Creeper Overhaul 2.0.5
		emojiful: Emojiful 4.0.3
			com_esotericsoftware_yamlbeans_yamlbeans: yamlbeans 1.15
			midnightlib: MidnightLib 0.6.0
		emotecraft: Emotecraft 2.2.7-b.build.47
			player-animator: Player Animator 0.4.0
		fabric-api: Fabric API 0.69.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.13+0d0f210290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.12+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.20+0d0f210290
			fabric-block-api-v1: Fabric Block API (v1) 1.0.1+12bfe4ea90
			fabric-command-api-v1: Fabric Command API (v1) 1.2.13+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.9+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.30+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.38+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.4+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.0+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.7+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.3+ad31814d90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.33+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.2+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.31+6eb9a2a190
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.31+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.23+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.6.1+fa140d5990
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.36+9244241690
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.2+9244241690
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.10+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.13+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.5+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.21+33fbc73890
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.8+3b1d070f90
			fabric-networking-v0: Fabric Networking (v0) 0.3.25+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.3+06e0e25190
			fabric-particles-v1: Fabric Particles (v1) 1.0.12+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.29+9244241690
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.17+0d0f210290
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.9+c6af733c90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.1+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.2+574a764890
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.4+1cc24b1b90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.3+9d081d6490
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.2+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.7+kotlin.1.7.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.11+local
		farmersdelight: Farmer's Delight 1.19.2-1.3.9
		ferritecore: FerriteCore 5.0.3
		geckolib3: Geckolib 3.1.38
			com_eliotlash_mclib_mclib: mclib 20
		inventorysorter: Inventory Sorter 1.8.10-1.19
			kyrptconfig: Kyrpt Config 1.4.14-1.19
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		kubejs: KubeJS 1902.6.0-build.135
			ingredient-extension-api: Ingredient Extension API 3.0.5
		lazydfu: LazyDFU 0.1.3
		ledger: Ledger 1.2.5
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			server_translations_api: Server Translations API 1.4.14+1.19-rc2
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
		libraryferret: Library ferret 3.0.0
		lithium: Lithium 0.10.4
		minecraft: Minecraft 1.19.2
		mvs: Vanilla Structure Mod 2.5.10-1.19.2
		nochatreports: No Chat Reports 1.19.2-v1.13.12
		ping-wheel: Ping Wheel 1.2.0
		plasmo_voice: Plasmo Voice 1.2.19
		player_roles: Player Roles 1.6.1
			more_codecs: More Codecs 0.2.2+1.18
			player_roles_api: Player Roles API 1.6.1
		puzzleslib: Puzzles Lib 4.3.12
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		rhino: Rhino 1902.2.2-build.264
		roughlyenoughitems: Roughly Enough Items 9.1.580
			error_notifier: Error Notifier 1.0.9
		servux: Servux 0.1.0
		simplechunkloader: Simple Chunkloader 1.0.3
			libgui: LibGui 6.0.0-beta.5+1.19-pre1
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		starlight: Starlight 1.1.1+fabric.ae22326
		structory: Structory 1.0.1
		styledplayerlist: Styled Player List 2.2.2+1.19.1
			placeholder-api: Placeholder API 2.0.0-beta.7+1.19
			player-data-api: Player Data API 0.2.1+1.19
		terrablender: TerraBlender 2.0.1.136
		textutilities: Text Utilities 1.2.0
		vanillatweaks: VanillaTweaks 1.5.63
		wilderwild: Wilder Wild 1.1.6-Fabric+1.19.2
			caffeineconfig: CaffeineConfig 1.0.0+1.17
			frozenlib: FrozenLib 1.1.7-Fabric+1.19.2
			mm: Manningham Mills 2.3
			nbtcrafting: NBT Crafting 2.2.3+mc1.19
	Server Running: true
	Player Count: 2 / 20; [class_3222['Sashok45'/805, l='ServerLevel[world]', x=-915.42, y=64.00, z=395.49], class_3222['BaklaHHH'/1673, l='ServerLevel[world]', x=-2106.29, y=66.85, z=122.68]]
	Data Packs: vanilla, Fabric Mods, file/Less+OP+Villagers+v1.5.5.zip, file/no-elytra.zip (incompatible), file/unending-smp.zip (incompatible)
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)`

**Comment by SercraftGaming** [comment]
[log.txt](https://github.com/FrozenBlock/WilderWild/files/10529774/log.txt)

**Comment by AViewFromTheTop** [comment]
uwu

**Comment by Boxbott** [comment]
this same crash seems to happen for my server if anyone cuts down a baobab tree using ht's tree chop or any tree cutter mod

**Comment by AViewFromTheTop** [comment]
should be fixed in the next update now idk
