### ISSUE TITLE
1.1.11 causing crash when starting server

### ISSUE THREAD

**Issue by aeaver** [FrozenBlock/WilderWild#208]
**Description of the Bug Encountered**
When starting server it iwll crash caused by the frozen lib, Wilder wild ver 1.1.10 does not cause any kind of crash.
Crash still happend even after starting a new server world

**Logs**
https://mclo.gs/ZFCXpR8

**Comment by Treetrain1** [comment]
Fixed

Will release a hotfix very shortly
