### ISSUE TITLE
BrushExtender.jar (a mod i made for easier brushable blocks) isnt included in ww 1.19.4 builds, causing crashes

### ISSUE THREAD

**Issue by AViewFromTheTop** [FrozenBlock/WilderWild#215]
yes its in the libs folder tree please help

**Comment by Treetrain1** [comment]
> yes its in the libs folder tree please help

maybe share the repo :trollface:

**Comment by AViewFromTheTop** [comment]
@Treetrain1 i made the repo
https://github.com/AViewFromTheTop/BrushExtender
