### ISSUE TITLE
Cypress Saplings should have unique texture when waterlogged

### ISSUE THREAD

**Issue by AViewFromTheTop** [FrozenBlock/WilderWild#216]
Root-like...??? idk

**Comment by MerpisMe** [comment]
really the only things that do this are sea pickles, which emit light, and mesoglea, which becomes permeable

**Comment by AViewFromTheTop** [comment]
> mmm idk it feels weird to make things have different textures based on whether they're waterlogged unless there is an actual mechanical change associated with it

They always grow the “swamp” variation of cypress if waterlogged

**Comment by AViewFromTheTop** [comment]
regardless, it’s odd to have their needles grown underwater

**Comment by AViewFromTheTop** [comment]
@MerpisMe @enriarts @Treetrain1 so would we be able to add this or is the consensus no
