### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by AViewFromTheTop** [FrozenBlock/WilderWild#217]
Tumbleweed Stems should be obtained without shears, they’re a functional plant
Tumbleweed Stems should drop the Tumbleweed item as well if hit with shears and fully grown
Fallen Oak in Swamps
Fallen Mangrove in Mangrove Swamps
Moss instead of Podzol basins for non-Temperate Rainforest biomes
Basins in Jungle biomes
Rename Palm Leaves to Palm Fronds
Compostable Coconuts

**Comment by Soro335** [comment]
Should stops when touch iron bars and destroy crops 
![image](https://user-images.githubusercontent.com/82042293/226924236-01c3ca5a-d380-4566-85f5-033803274a6d.png)

**Comment by AViewFromTheTop** [comment]
> Should stops when touch iron bars and destroy crops
> ![image](https://user-images.githubusercontent.com/82042293/226924236-01c3ca5a-d380-4566-85f5-033803274a6d.png)

Oh shit I never thought of iron bars that way
