### ISSUE TITLE
Hanging sign does not drops when you break it. 

### ISSUE THREAD

**Issue by SergoFox123** [FrozenBlock/WilderWild#219]
When I break a hanging sign with my hand or an ax, it does not drop out. (Version 1.19.4)

**Steps To Reproduce**
1. Hang a hanging baobab or cypress sign
2. Break with hand or ax

https://user-images.githubusercontent.com/90069504/229364313-f03ded7c-5a17-412a-bc57-8aa3e656a481.mp4

**Comment by AViewFromTheTop** [comment]
oopsies that isn't supposed to happen
