### ISSUE TITLE
World turns to stone when using C2ME

### ISSUE THREAD

**Issue by CTuTD** [FrozenBlock/WilderWild#220]
I don't know what to do with it, but whenever I create a world, it's made of stone. And there are no new and even old biomes because everything is made of stone.  

these are screenshots
(https://user-images.githubusercontent.com/129602315/230768372-d0eeec4b-d940-46bf-adfa-857b38bf5c53.png)
(https://user-images.githubusercontent.com/129602315/230768414-46fdb8e9-407d-4fa5-a4cd-319ca32b304c.png)

and so it is all over the world!

**Comment by Soro335** [comment]
Provide information following Reporting Guidelines #130

**Comment by CTuTD** [comment]
Explain the issue in as clear detail as possible. We need to know how and why the issue is happening.  --->There is an explanation of the problem, but I do not know how and why it occurs. 

Attach screenshots or videos if applicable.  --->There are screenshots.

If the issue involves a crash, attach crash logs if applicable.  --->There are no failures, the game starts and works calmly.

Make sure your issue has not already been reported by another person.  --->No one seems to have reported this problem.

Make sure that what you're reporting is actually an issue.  --->Yes I think this is a problem.

If I'm doing something wrong in terms of processing my problems, please tell me what I need to do. This is my first time using this site, and I don't fully understand what I'm doing wrong.
I would really like to play with this mod.

**Comment by Soro335** [comment]
Provide logs and mod list pls!

**Comment by CTuTD** [comment]
list of mods:

immersive_aircraft-0.4.2+1.19.3-fabric.jar 
immersive_armors-1.5.5+1.19.3-fabric.jar 
MTR-fabric-1.19.3-3.2.1-hotfix-1.jar 
Adorn-4.1.0+1.19.3-fabric.jar 
fabric-language-kotlin-1.9.3+kotlin.1.8.20.jar 
paladin-furniture-mod-1.1.2-fabric-mc1.19.3.jar 
carryon-fabric-1.19.3-2.0.4.15.jar 
badpackets-fabric-0.3.4.jar 
travelers-backpack-1.19.3-8.3.6.jar 
cardinal-components-base-5.1.0.jar
cardinal-components-api-5.1.0.jar 
IronChests-1.7.8.jar 
voicechat-fabric-1.19.3-2.4.3.jar 
journeymap-1.19.3-5.9.5-fabric.jar 
Origins-1.19.3-1.8.1.jar 
ctov-3.1.7.jar 
[Universal]Immersive Structures-2.0.7.jar 
jei-1.19.3-fabric-12.4.0.22.jar 
c2me-fabric-mc1.19.3-0.2.0+alpha.10.0.jar
cloth-config-9.0.94-fabric.jar
dashloader-5.0.0-alpha.13+1.19.3.jar
dynamic-fps-2.2.0.jar
enhancedblockentities-0.8+1.19.3.jar
entityculling-fabric-1.6.1-mc1.19.3.jar
fabric-api-0.76.0+1.19.3.jar
ferritecore-5.1.0-fabric.jar
iris-mc1.19.3-1.5.2.jar
lazydfu-0.1.3.jar
lithium-fabric-mc1.19.3-0.11.1.jar
modmenu-5.1.0-beta.4.jar
reeses_sodium_options-1.4.9+mc1.19.2-build.67.jar
smoothboot-fabric-1.19-1.7.1.jar
sodium-extra-0.4.18+mc1.19.3-build.99.jar
sodium-fabric-mc1.19.3-0.4.9+build.23.jar
starlight-1.1.1+fabric.ae22326.jar
Fastload+1.18.2-1.19.4-3.3.0.jar

(https://user-images.githubusercontent.com/129602315/230775654-e344ce85-09c9-4132-b9ad-0c1517d3681f.png)

today's logs:

[2023-04-09-5.log](https://github.com/FrozenBlock/WilderWild/files/11185526/2023-04-09-5.log)
[2023-04-09-6.log](https://github.com/FrozenBlock/WilderWild/files/11185527/2023-04-09-6.log)
[2023-04-09-7.log](https://github.com/FrozenBlock/WilderWild/files/11185528/2023-04-09-7.log)
[latest.log](https://github.com/FrozenBlock/WilderWild/files/11185529/latest.log)
[2023-04-09-1.log](https://github.com/FrozenBlock/WilderWild/files/11185530/2023-04-09-1.log)
[2023-04-09-2.log](https://github.com/FrozenBlock/WilderWild/files/11185531/2023-04-09-2.log)
[2023-04-09-3.log](https://github.com/FrozenBlock/WilderWild/files/11185532/2023-04-09-3.log)
[2023-04-09-4.log](https://github.com/FrozenBlock/WilderWild/files/11185533/2023-04-09-4.log)

I hope this is what you need to solve the problem.Thanks.

(https://user-images.githubusercontent.com/129602315/230775806-9010f893-29ca-456c-9d21-e97239e09890.png)

**Comment by AViewFromTheTop** [comment]
This issue happens with C2ME, I'm well aware.
I don't really know how to fix this issue as our implementation of surface rule modification is completely harmless.
Just remove C2ME as it's still in Alpha and has a long way to go.

**Comment by CTuTD** [comment]
yes, you're really right, thank you!

**Comment by Treetrain1** [comment]
Reopening as this is still a valid issue with C2ME

**Comment by Treetrain1** [comment]
I believe this has been fixed in the next release
