### ISSUE TITLE
Allow Panorama replacement to be disabled

### ISSUE THREAD

**Issue by Dekamir** [FrozenBlock/WilderWild#223]
Add a config to disable Panorama replacing.

Example:
_misc.json_
```
{
  "userInterface": {
    "modPanorama": false,
  }
}
```

**Comment by AViewFromTheTop** [comment]
You already can disable it.

**Comment by Dekamir** [comment]
This does not seem to be the case in 1.19.2.  Sorry for the inconvenience.
I tried to port my packs to 1.19.4, but a lot of mods are also not ported to 1.19.4, so sadly I have to keep there.
It would be great if you'd backport the feature.

**Comment by Treetrain1** [comment]
> This does not seem to be the case in 1.19.2. Sorry for the inconvenience.
> I tried to port my packs to 1.19.4, but a lot of mods are also not ported to 1.19.4, so sadly I have to keep there.
> It would be great if you'd backport the feature.

It’s in all versions
Disable the resourcepack
