### ISSUE TITLE
Lakes cutting trees

### ISSUE THREAD

**Issue by chadzar** [FrozenBlock/WilderWild#224]
**Description of the Bug Encountered**
Sometimes lake generation cutt trees

**Expected Behavior**

To not cutt trees

**Screenshots**

Seed: -7438949324280004728

Coordinates: -134 64 259
![2023-04-17_20 46 04](https://user-images.githubusercontent.com/121126681/232635614-8b542a9b-bd04-48fa-94d5-23917214a342.png)
![2023-04-17_20 48 36](https://user-images.githubusercontent.com/121126681/232635757-bf8b0dd6-0e31-4b9e-8d82-63ab88466608.png)

**Additional context**

Version: 1.19.2 (Fabric 0.14.19)
Mod Version: 2.0 (1.19.2)

I'm not using any other world generation mod

**Comment by AViewFromTheTop** [comment]
I'm honestly not sure how to fix this as it's a Vanilla issue, technically.
The trees are generating before the Lake Feature is placed likely due to it generating between two chunks, so this happens.
