### ISSUE TITLE
Crash on the world creation

### ISSUE THREAD

**Issue by variety754** [FrozenBlock/WilderWild#225]
**Description of the Bug Encountered**
I was playing in my modpack and after updating Wilder Wild to latest version got this crash caused by incompability with wythers
**Steps To Reproduce**
1. Install Wilder Wild and Wythers
2. Set compability mode for Wythers
3. Launch Minecraft, create new world
4. Pray to the god for the issue to appear

**Expected Behavior**
Crash with code -1

**Logs**

[latest.log](https://github.com/FrozenBlock/WilderWild/files/11257109/latest.log)

**Comment by variety754** [comment]
It appears that the same crash happens with Terralith

**Comment by Treetrain1** [comment]
Fixed in next release

**Comment by variety754** [comment]
Thank you very much!!! 👏👏👏
