### ISSUE TITLE
Game crashes when trying to launch with most recent version of mod

### ISSUE THREAD

**Issue by suicidemiami** [FrozenBlock/WilderWild#226]
This is the error message I got.

The game crashed whilst initializing game
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3037.method_30649()" because "this.comp_333" is null

**Comment by Soro335** [comment]
Send logs please!

**Comment by Poly2it** [comment]
This crash has returned. I am experiencing the same issue on the latest release ([2.0.6](https://modrinth.com/mod/wilder-wild/version/2.0.6-mc1.19.2)).
