### ISSUE TITLE
Using Terrablender with newest version 2.0 on 1.19.4 disables some biomes from generating 

### ISSUE THREAD

**Issue by psyoalex** [FrozenBlock/WilderWild#227]
I was able to pin down that when using version 2.0 with Terrablender, some biomes just stop generating and you can't locate them through a command. It gives you the same message as when you try to find disabled biomes or structures.
For example - "Could not find a biome of type "wilderwild:mixed_forest" within reasonable distance."

The biomes that result in the same message: 

Dark Taiga 
Mixed Forest 
Old Growth Birch Taiga 
Old Growth Dark Forest 
Parched Forest 
Rainforest 
Temperate Rainforest

To clarify - I tried it with a clean install, disabled different mods, and reset the config. As soon as I disable Terrablender it's all working again. I also tried both 1.19.4 versions of Terrablender - 2.2.0.155 and 2.2.0.154.

It's also important to point out that it wasn't an issue on the previous version of Wilder Wild 1.1.15 with around 160 mods.

**Comment by AViewFromTheTop** [comment]
Closing as this is an issue on their side.
