### ISSUE TITLE
Can't generate new worlds and "freezes"

### ISSUE THREAD

**Issue by slovinsqui** [FrozenBlock/WilderWild#228]
MC: 1.19,2 Fabric: 0.14.19 Mod version: WilderWild-2.0-Fabric+1.19.2.jar

**Description of the Bug Encountered**
Game stops creating new worlds, but does not freeze or crash
each try on generating the same world gets more progress than the last time for some reason 
(update) doesn't go over 30
generating new chunks on already created worlds without the mod crashes the game

**Steps To Reproduce**
1. Create world
2. Generate world
3. Stops loading

**Expected Behavior**
reach 100 percent of loading progress and run world

**Screenshots**
![image](https://user-images.githubusercontent.com/96891858/232895861-49f6296f-491c-46b8-937a-e6d27d979a0e.png)

**Logs**
[latest.log](https://github.com/FrozenBlock/WilderWild/files/11265961/latest.log)

**Additional context**
I do have other terrain generation mods installed:
Beneath the wetlands
Geophilic
choice theorems overhauled village
all of the Yung´s better mod series
Awesome dungeons Oceans
Biome Makeover
chef´s delight x choice theorems addon
Integrated Stronghold
Wabi Sabi
others...

**Comment by LordOfTheWeebs** [comment]
I had the same problem, it seems to be caused by BC Lib. I removed BC Lib from my personal pack (and obviously mods that use it as a dependency) and it seems to work fine.
