### ISSUE TITLE
Use “BrushableBlock” instead of brush extender

### ISSUE THREAD

**Issue by Treetrain1** [FrozenBlock/WilderWild#230]
**Explain your suggestion here.**
A clear explanation of what you would like to see and why. "I'd like to see... added because..." 

When Mojang added suspicious gravel, they changed SuspiciousSandBlock to BrushableBlock that makes it more versatile. It’s overall better than the brush extender alternative.

**Additional context**
Add any other context or screenshots about the suggestion here.

This change cannot be applied to 1.19.4, as “BrushableBlock” is only in the 1.20 snapshots.

**Comment by AViewFromTheTop** [comment]
shouldnt this be closed btw since it was added
