### ISSUE TITLE
jellyfish remodel proposal

### ISSUE THREAD

**Issue by MerpisMe** [FrozenBlock/WilderWild#232]
![file (7)](https://user-images.githubusercontent.com/27739930/233736528-d6c14874-103b-4c57-82b4-33a1ef3b5278.gif)
i really dont like the current model lol
i think this new design looks a lot more minecrafty

**Comment by MerpisMe** [comment]
@AViewFromTheTop wdyt

**Comment by MerpisMe** [comment]
the only differences here are basically  just a slightly bigger body and 2d tentacles

**Comment by Xfrtrex** [comment]
the current one is perfectly fine, this one just looks... eh.

**Comment by Osmiooo** [comment]
> the only differences here are basically just a slightly bigger body and 2d tentacles

could you do it with 3d tentacles? i think it'll look better

**Comment by MerpisMe** [comment]
3d tentacles dont make sense
you dont have 1px models in the game

**Comment by MerpisMe** [comment]
> the current one is perfectly fine, this one just looks... eh.

if the current one was perfectly fine then i wouldnt be trying to change it lol

**Comment by MerpisMe** [comment]
also they're not even technically tentacles
they would be very thin if represented accurately

**Comment by Osmiooo** [comment]
> 3d tentacles dont make sense you dont have 1px models in the game

but 2d tentacles look weird to me
idk what it is but it looks weird

**Comment by MerpisMe** [comment]
hence why i feel making them 2d works better both visually and logically

**Comment by MerpisMe** [comment]
> > 3d tentacles dont make sense you dont have 1px models in the game
> 
> but 2d tentacles look weird to me idk what it is but it looks weird

you probably wouldn't be saying that if i had initially modelled them in 2d

**Comment by MerpisMe** [comment]
in other words i'm sure it only looks wromg because you're bot used to it

**Comment by Treetrain1** [comment]
reduce the number of tentacles holy shit

**Comment by MerpisMe** [comment]
oh fair

**Comment by AViewFromTheEnd** [comment]
> @AViewFromTheTop wdyt

I really disagree on this (also keep in mind I don’t get notifs)
id not be opposed to a config being added for it, but I got really attached to the current design for a reason- as have many others
i did consider a similar idea when we were conceptualizing jellies but I didn’t bother going through with it for a reason
again, I’d be perfectly fine adding this with a config with viable help cause I’m not the best at model mapping and all that

**Comment by AViewFromTheEnd** [comment]
I do think the tentacles should be moved a bit inward though

**Comment by AViewFromTheEnd** [comment]
Also, to the others
please please please try to give a bit more feedback with explanation if you’re able to
it really helps with communication, and was a big frustration I had working alongside you all
if all you’re able to say is that the tentacles look weird, that’s fine
but i do think it’s for the greater good that a bit of elaboration is provided if possible- how to maybe improve, how you’ve considered it before and didn’t like it, why it looks off, inconsistencies it may introduce (squid,) etc
please know i never had ill intentions- im trying to help and right now, im trying to help with everyone’s communication

**Comment by AViewFromTheTop** [comment]
when

**Comment by MerpisMe** [comment]
i've been busy

**Comment by AViewFromTheTop** [comment]
ok really tho is this getting added lol
i wanna see it in action (though itd require us to block off the jelly tentacle config)
