### ISSUE TITLE
Future Update Plans

### ISSUE THREAD

**Issue by AViewFromTheTop** [FrozenBlock/WilderWild#233]
1.2.1
-Merp's new Jellyfish via config
-Fallen Trees generating with full Logs, not Hollowed (DONE)
-Falling Leaves mod uses FrozenLib's wind (DONE)
-Rare “Snapped” Trees- only their bottom halves generate (DONE)
-Update City Center like we tried to before (1.20+, as Sculk Sensor issues were fixed)
-Include Archeology in Ancient City (1.20+)
-Scorched Sand shows Brush stages (1.20+)
-Shipwrecks include new Jellyfish Armour Trim (1.20+)

**Comment by Treetrain1** [comment]
1.2.1?

**Comment by AViewFromTheTop** [comment]
Why not

**Comment by AViewFromTheTop** [comment]
Unless you really want it to be called 1.3 but I see no use

**Comment by Osmiooo** [comment]
Aren't we on 2.0

**Comment by AViewFromTheTop** [comment]
oh

**Comment by AViewFromTheTop** [comment]
2.1

**Comment by Osmiooo** [comment]
yeah thats better

**Comment by AViewFromTheTop** [comment]
im out of it today sorry
probably gonna try to use some meds laterlf lmfaoomv
