### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by Rogenar** [FrozenBlock/WilderWild#238]
wilder wild 2.0 causes crash when creating world in version 1.19.3.
[latest.log](https://github.com/FrozenBlock/WilderWild/files/11330720/latest.log)
[rei.log](https://github.com/FrozenBlock/WilderWild/files/11330724/rei.log)
[rei-issues.log](https://github.com/FrozenBlock/WilderWild/files/11330725/rei-issues.log)
[crash-2023-04-26_11.31.43-client.txt](https://github.com/FrozenBlock/WilderWild/files/11330726/crash-2023-04-26_11.31.43-client.txt)

**Comment by Treetrain1** [comment]
possibly fixed in next release
