### ISSUE TITLE
Incompatible with Sodium 0.4.11

### ISSUE THREAD

**Issue by Poopooracoocoo** [FrozenBlock/WilderWild#240]
**Description of the Bug Encountered**
Creating a world with Sodium 0.4.11, Fabric API 0.80.0, and Wilder Wild 2.0 on Minecraft 1.19.4 crashes. 

**Steps To Reproduce**
1. Create a Fabric 1.19.4 instance in Prism Launcher
2. Add Sodium 0.4.11, Fabric API 0.80.0, and Wilder Wild 2.0
3. Create a new world

**Expected Behavior**
No crash

**Screenshots**
N/A

**Logs**
Crash report: https://mclo.gs/2eujlBG
Logs: https://mclo.gs/12rTvhv

**Additional context**

**Comment by Treetrain1** [comment]
Closed as sodium 0.4.11 is removed from modrinth
