### ISSUE TITLE
Crash when loading a world in 1.19.2 involving Milkweeds

### ISSUE THREAD

**Issue by Alkiasan** [FrozenBlock/WilderWild#243]
Crash on 1.19.2 whenever Milkweeds are loaded, seems to be incompat with either lithium or carpet? Happens when Milkweeds are loaded for a couple of seconds in a pre-existing world that has updated to the latest version of WilderWild.

**Steps To Reproduce**
1.  Load world on dedicated server
2.  Crash after around 5-10 seconds

**Expected Behavior**
No Crash

**Logs**
 https://pastebin.com/xrxxVmt7

**Additional context**
Old reports involved Lithium and Carpet, however, after discussion with their developers, they seem to not be the cause.

**Comment by Treetrain1** [comment]
Fixed in next release
