### ISSUE TITLE
Crash when launching on 1.19.2 with Terrablender installed

### ISSUE THREAD

**Issue by Alkiasan** [FrozenBlock/WilderWild#244]
When trying to start a dedicated server on the latest github build, the server will fail to start.

**Logs**
https://pastebin.com/B2F97JHp

**Comment by Treetrain1** [comment]
could you provide the full crash log?

**Comment by Alkiasan** [comment]
Crash report isn't generated, but I can do one better and provide the full latest.log!
https://pastebin.com/kTLTVx0g

**Comment by Treetrain1** [comment]
You are using an incomplete release, please use 2.0.

**Comment by Alkiasan** [comment]
I am unable to do this due to issue #243 . Is this an expected crash with the current incomplete build?
