### ISSUE TITLE
[1.20-rc1] world generator issue

### ISSUE THREAD

**Issue by MSandro** [FrozenBlock/WilderWild#246]
**Description of the Bug Encountered**
I've installed the Mod WilderWild-2.0.2-Fabric+1.20-pre7 in  MC 1.20-rc1
now the world generates no grass surface anymore.  I know the Mod Version is for pre7 but I just wanted to try if it works with rc1 as well.

**Screenshots**
![image](https://github.com/FrozenBlock/WilderWild/assets/10937159/3feecd9c-67ff-4c32-ba03-e4888204014f)

**Comment by Treetrain1** [comment]
does this issue occur in pre release 7 or is it exclusive to the release candidate?

**Comment by MSandro** [comment]
In pre7 it worked fine

**Comment by AViewFromTheTop** [comment]
Are you using C2ME? If so, that's the problem. We don't really know why, though.

**Comment by MSandro** [comment]
Yes i do, thx I will try without

**Comment by AViewFromTheTop** [comment]
> Yes i do, thx I will try without

Funnily enough, this was just fixed on C2ME's side.

**Comment by AViewFromTheTop** [comment]
@Treetrain1 woukd you be able to close this since Relativity fixed it on their side
