### ISSUE TITLE
Crash every time I try opening.

### ISSUE THREAD

**Issue by Irish-Phouka** [FrozenBlock/WilderWild#247]
I've reinstalled ,switched versons I dont know what's not working
[latest.log](https://github.com/FrozenBlock/WilderWild/files/11643566/latest.log)

[14:37:28] [main/INFO]: Loading Minecraft 1.19.4 with Fabric Loader 0.14.21
[14:37:29] [ForkJoinPool-1-worker-11/WARN]: The mod "brushextender" contains invalid entries in its mod json:
- Unsupported root entry "modmenu" at line 30 column 12

**Comment by Treetrain1** [comment]
This looks like an issue with Reach Entity Attributes, which is included in Origins

Does this error occur without Wilder Wild?

**Comment by Irish-Phouka** [comment]
I actually got it work with origins and wilder wild, it was two other mods not working. Maybe they would work without origins. Thank you for the advice!
