### ISSUE TITLE
1.19.2: Incompatible with ModernFix

### ISSUE THREAD

**Issue by WimpieRatte** [FrozenBlock/WilderWild#249]
When ModernFix (latest: 3.7.1 for Fabric) and Wilder Wild (latest: 2.0.2 for Fabric) are installed together, I get a startup crash.
(ModernFix improves loading times. As alternative, "Smooth Boot (Fabric)" is compatible with Wilder Wild.)

I'm not sure if if this is something fixable, but perhaps it can be mentioned as a compatibility comment in your mod description, that Smooth Boot is a working alternative if this compatibility issue cannot be fixed?

**Steps To Reproduce**
Have both Wilder Wild and ModernFix mods in your client :).

Crash report:
https://github.com/WimpieRatte/SharedFiles/blob/main/20230604WilderWildWithModernFix.txt

**Comment by Treetrain1** [comment]
the issue looks like the vanilla datafixers cannot be built.

perhaps ModernFix disables the vanilla datafixers

**Comment by jitterdev** [comment]
turning off the `perf.dynamic_dfu` mixin in modernfix's config fixes the crash

**Comment by AViewFromTheTop** [comment]
> The next version of ModernFix should fix this; the lazy datafixer will now pass through `getSchema` calls to the real datafixer, not just `update` calls.

Can confirm. Same issue happened with an earlier 1.20 version, and I’ve tested with a newer version of ModernFix and the issue doesn’t occur anymore.
This issue is on their side so if it still happens in 1.19.2, that’s something for its developers to take care of.

**Comment by embeddedt** [comment]
I still maintain versions as old as 1.16.5. ;) The fix was applied to all
versions.

**Comment by AViewFromTheTop** [comment]
> I still maintain versions as old as 1.16.5. ;) The fix was applied to all versions.
> […](#)

Oh wait *youre* the developer of it
Yoooooooo
