### ISSUE TITLE
Clouds get screwed up with Immersive Portals

### ISSUE THREAD

**Issue by AViewFromTheTop** [FrozenBlock/WilderWild#251]
step 1: literally just open a nether portal
step 2: once it loads the nether (you dont even have to walk through,) the clouds get screwed up

**Comment by Treetrain1** [comment]
![wilder wild cool](https://github.com/FrozenBlock/WilderWild/assets/39657565/a3c1012d-bd9a-4216-b040-c4437011b628)

**Comment by AViewFromTheTop** [comment]
what

**Comment by AViewFromTheTop** [comment]
actually naaaaaaah im closing this lol
immersive portals breaks a ton of stuff tbh we shouldnt worry
