### ISSUE TITLE
Mob spawners don't run finalizeSpawn method correctly - 1.19.2 fabric

### ISSUE THREAD

**Issue by arazadaz** [FrozenBlock/WilderWild#255]
**Description of the Bug Encountered**
Spawners don't run finalizeSpawn. This is usually called on mobs before they spawn, and in vanilla, spawner's do run this method & they give mobs the Spawn Reason of "SPAWNER". However, with your mod, mobs from mob Spawners don't seem to be assigned any Spawn Reason.

**Steps To Reproduce**
1.  Install this mod
2.  Place spawner
3. Spawner works, but doesn't call finalizeSpawn method
4. mod incompatability

**Expected Behavior**
Spawners call finalizeSpawn for each mob they summon. For me, this is important because I have another mod that does some logic with mobs & their spawn reason is apart of that. Right now, any mob that spawns from a spawner has a null spawn reason because it's set within finalizeSpawn. I've seen a couple of mods target finalizeSpawn to allow mobs to remember their spawn reason, so fixing this could potentially fix issues with a couple of other mods excluding my own.

**Screenshots**

**Logs**

**Additional context**
This shouldn't really affect vanilla(with this mod) game-play. Although it might? If it does, it's not going to be anything noticeable. This is mostly a mod compatibility issue.

**Comment by AViewFromTheTop** [comment]
Oh, that’s surprising to hear! Do you happen to know what mixin could cause it?

**Comment by Treetrain1** [comment]
> Oh, that’s surprising to hear! Do you happen to know what mixin could cause it?

i believe SpottingIconManager is causing it

**Comment by AViewFromTheTop** [comment]
> > Oh, that’s surprising to hear! Do you happen to know what mixin could cause it?
> 
> i believe SpottingIconManager is causing it

wtf

**Comment by Treetrain1** [comment]
> wtf

I think it's because the nbt operations for `ticksToCheck` are reversed on `load()` and `save()`
is that intentional?
if not, swapping them to their correct methods will fix it

**Comment by AViewFromTheTop** [comment]
> > wtf
> 
> I think it's because the nbt operations for `ticksToCheck` are reversed on `load()` and `save()` is that intentional? if not, swapping them to their correct methods will fix it

Oh my god im such an idiot could you fix that please

**Comment by arazadaz** [comment]
Thanks yall. Hopefully that's the fix.

**Comment by AViewFromTheTop** [comment]
@Treetrain1 i dont think that fixed it
skeletons still dont spawn with bows or anything

**Comment by AViewFromTheTop** [comment]
> @Treetrain1 i dont think that fixed it skeletons still dont spawn with bows or anything

nvm i forgot ww builds with modrinth frozenlib

**Comment by AViewFromTheTop** [comment]
@Treetrain1 ok yeah you fixed it you can close this issue
