### ISSUE TITLE
Termites can Reach sound limit easily.

### ISSUE THREAD

**Issue by Xfrtrex** [FrozenBlock/WilderWild#256]
**Description of the Bug Encountered**
Termites will reach Sound limit (247 sounds playing at the same time) with very few Termite Blocks, for me, only about 6.

**Steps To Reproduce**
1. Get around 6 Termite Mounds
2. Find a ton of wood, such as a baobab tree
3. place the termite mounds around the wood
4. it will eventually start reaching 247 sounds at once (look in f3, in Sounds

**Expected Behavior**
Not reach sound limit, not make other sounds go silent because of the amount of sounds. 

**Additional context**
A solution could possibly coding in a sound limit for how many TERMITE sounds can play at once.

**Comment by AViewFromTheTop** [comment]
I know
Also this is why Minecraft is stupid why is there a limit that’s so small

**Comment by AViewFromTheTop** [comment]
I honestly don’t really care to fix this because it’s just a stupid Minecraft choice
I think it would be better to have a mod that raises the sound limit

**Comment by Treetrain1** [comment]
> I honestly don’t really care to fix this because it’s just a stupid Minecraft choice I think it would be better to have a mod that raises the sound limit

or just use a restricted sound loop

**Comment by AViewFromTheTop** [comment]
> or just use a restricted sound loop

That’s literally going to fix nothing
Tree
They’re Termites
How
Is that going to work

**Comment by Treetrain1** [comment]
> > or just use a restricted sound loop
> 
> That’s literally going to fix nothing Tree They’re Termites How Is that going to work

idk maybe like some sort of sound loop that uses a supplier for coordinates

**Comment by AViewFromTheTop** [comment]
Termite positions don’t sync to the client and I’d rather not go through the pain of making that work, so the sound couldn’t do that

**Comment by AViewFromTheTop** [comment]
I’ve tried making termite poses sync before and I couldn’t figure it out if I had eighty six guns pointed at my head and ready to shoot

**Comment by Treetrain1** [comment]
> Termite positions don’t sync to the client and I’d rather not go through the pain of making that work, so the sound couldn’t do that

they arent synced??

**Comment by AViewFromTheTop** [comment]
> they arent synced??

They’ve literally never been synced

**Comment by AViewFromTheTop** [comment]
….merp for some reason thought they were synced too but I explicitly stated a couple times they aren’t synced
Tbh I’m just kinda worried about sending WAAAAAY too many packets to the client at once idk
maybe I’m being irrational
I’ll look into it, but I’m not changing the particles at all
Evidently I designed the particles so well that everyone thinks termite poses are synced lmfao even I didn’t expect my tricks to work that well on them

**Comment by AViewFromTheTop** [comment]
Speaking of termites
I need to make termite distance configs

**Comment by AViewFromTheTop** [comment]
I’ll get to work after I’m done getting ready for bed and watch some Clone High
season one is honestly better than spongebob at its peak ngl but season two is kinda… meh

**Comment by AViewFromTheTop** [comment]
Also yes I just came up with an idea on how to sync them and I have no clue how I didn’t think of it before
Probably because being in FB and actively working on 2.0 and dealing with all the other shit in life at the time literally drove me insane lmao
Oh well, I can think now and that’s what I’ll do when I’m back
jya na!!

**Comment by AViewFromTheTop** [comment]
Shit.
Well I forgot uh I’ll do this later sorry gn

**Comment by AViewFromTheTop** [comment]
@MerpisMe hey, would you be able to turn the termite moving and eating sounds into loops? id really appreciate it

**Comment by AViewFromTheTop** [comment]
@Treetrain1 thank you for your suggestion, i made looping sounds that switch out when theyre eating or not eating.
we just need the sounds to be modified to sound much better with a loop.
i think this issue can be closed now, or maybe not until we get those sounds edited.

**Comment by Xfrtrex** [comment]
@AViewFromTheTop btw im in a server that apparently has wilder wild, and termites are extremally valuable there lmao

**Comment by Xfrtrex** [comment]
theres even this sign i found
![2023-06-30_09 26 11](https://github.com/FrozenBlock/WilderWild/assets/80720298/fa04886f-fe5e-4039-b7d1-6c8e1bc03a82)

**Comment by AViewFromTheTop** [comment]
> @AViewFromTheTop btw im in a server that apparently has wilder wild, and termites are extremally valuable there lmao

ooooo which server

**Comment by AViewFromTheTop** [comment]
> theres even this sign i found
> ![2023-06-30_09 26 11](https://user-images.githubusercontent.com/80720298/250144840-fa04886f-fe5e-4039-b7d1-6c8e1bc03a82.png)

WHAAAT
FUCK YOU YOU FUCKING STICK-SHAPED WHORE WITH TEXT ON IT
I AM NOT TAKING ANY LS. FUCK YOU. EVEN THOUGH I HAVENT BEEN ABLE TO ENGAGE IN TRANSVESTITE ACTIVITIES FOR A LONG TIME I WILL STILL CONSIDER MYSELF A BISEXUAL FEMBOY FUCK YOU

**Comment by AViewFromTheTop** [comment]
seasonal femboy actually

**Comment by AViewFromTheTop** [comment]
Either way why are termites so valuable to them
Do they have 2.0 yet

**Comment by MerpisMe** [comment]
> @MerpisMe hey, would you be able to turn the termite moving and eating sounds into loops? id really appreciate it

i'm on a week long trip to massachusetts so it'll have to wait

**Comment by AViewFromTheTop** [comment]
as the nearly sole developer of termites i should join and mindfuck them with termite knowledge
and maybe add an Easter egg in 2.1 to fuck with them idk

**Comment by AViewFromTheTop** [comment]
> i'm on a week long trip to massachusetts so it'll have to wait

holy shittttt that’s like
seven days

**Comment by AViewFromTheTop** [comment]
also i might be going to a goth club tonight (not 100% sure if im going yet) so I probably won’t have time to make the termite distance config tonight
im taking a bit of time to set up my brand new PlayStation 3 so I can play plants vs zombies garden warfare on a fifth platform

**Comment by AViewFromTheTop** [comment]
neither of those are a joke btw im dead serious
yes I got a PS4 and PS3 solely to play one fucking game on them
Though I would only need one if POPCAP KNEW WHAT CROSS COMPATABILITY IS

**Comment by AViewFromTheTop** [comment]
![IMG_3247](https://github.com/FrozenBlock/WilderWild/assets/87103914/f8a4ca79-14a6-46b4-8fbd-98dfaaba2550)
SCREW YOU DAMN ROBOT I DONT CARE

**Comment by AViewFromTheTop** [comment]
I’m
Gonna go for a few mins now im getting too excited
Sorry lmao
That’s what happens when you’re put into a job where you finally start socializing with tons of people for the first time in your life since 2015

**Comment by Xfrtrex** [comment]
> Either way why are termites so valuable to them Do they have 2.0 yet

yes they have 2.0, its a 1.20 server. you wont like it, all they do is kill people and burn stuff

**Comment by Xfrtrex** [comment]
plus its private

**Comment by AViewFromTheTop** [comment]
Hello people I am baaaaack

**Comment by Xfrtrex** [comment]
youd have to be whitelisted and i dont think they would

**Comment by AViewFromTheTop** [comment]
> yes they have 2.0, its a 1.20 server. you wont like it, all they do is kill people and burn stuff

Ehhhh I was on a server like that once
It was frustrating but I liked killing people and subtly fucking with their bases 

> youd have to be whitelisted and i dont think they would

yeah thanks the the insult you can stop now

**Comment by Xfrtrex** [comment]
btw we need to fix this bug NOW because they crashed the server with it, you can dupe fireflies simply by clicking really fast with the bottle

**Comment by AViewFromTheTop** [comment]
So anyway
A 1.20 server that “just so happens to have wilder wild” that you’re whitelisted on
yeah suuuuuurrreee something fishy’s going on here

**Comment by AViewFromTheTop** [comment]
> btw we need to fix this bug NOW because they crashed the server with it, you can dupe fireflies simply by clicking really fast with the bottle

just limit the cps of their mice problem solved

**Comment by Xfrtrex** [comment]
> > btw we need to fix this bug NOW because they crashed the server with it, you can dupe fireflies simply by clicking really fast with the bottle
> 
> just limit the cps of their mice problem solved

what no?

**Comment by Xfrtrex** [comment]
lol its bug we need to fix

**Comment by Xfrtrex** [comment]
you dont even need that fast of cps

**Comment by AViewFromTheTop** [comment]
0.5 cps boom problem solved

**Comment by Xfrtrex** [comment]
> 0.5 cps boom problem solved

what?? 💀

**Comment by Xfrtrex** [comment]
that would break so much on the server

**Comment by AViewFromTheTop** [comment]
If you’re in a server full of people who are so far out there that they feel the need to crash a server with fucking fireflies i think that says enough

**Comment by AViewFromTheTop** [comment]
yeah sure I’ll fix it but god damn

**Comment by Xfrtrex** [comment]
> If you’re in a server full of people who are so far out there that they feel the need to crash a server with fucking fireflies i think that says enough

i showed them the nectar thing, they didnt mean to crash they just wanted to fix a players base with 3000 of them to annoy them with the loud nectar fireflies

**Comment by Xfrtrex** [comment]
cause i told them they wouldnt lag at all but i didnt mean 3000 OF THEM

**Comment by AViewFromTheTop** [comment]
Nobody summons 3,000 of ANY entity without expecting a crash, sorry.

**Comment by Xfrtrex** [comment]
i told them they were coded to be super not laggy but

**Comment by AViewFromTheTop** [comment]
> i told them they were coded to be super not laggy but

it’s minecraft
entities lag regardless unless they’re like markers or something

**Comment by Xfrtrex** [comment]
yeah but they are dumb so

**Comment by AViewFromTheTop** [comment]
I found the problem
I put the fucking item stack decrementation on finishUsingItem instead of the regular use method what the hell

**Comment by AViewFromTheTop** [comment]
What kind of jackass does that

**Comment by AViewFromTheTop** [comment]
@Xfrtrex alright should be fixed, im committing rn and ill test it real quick

**Comment by AViewFromTheTop** [comment]
genuinely thank you for pointing that out by the way because the firefly bottle stuff was....
it was extremely shitty i dont even know how i didnt notice while i was going through each class to touch them all up
also yea it should definitely be fixed now, i just tested

**Comment by Xfrtrex** [comment]
> Either way why are termites so valuable to them Do they have 2.0 yet

either way they are valuable to them because "they are cool"

**Comment by Xfrtrex** [comment]
> @Xfrtrex alright should be fixed, im committing rn and ill test it real quick

thank you!!

**Comment by AViewFromTheTop** [comment]
> > Either way why are termites so valuable to them Do they have 2.0 yet
> 
> either way they are valuable to them because "they are cool"

Lmao just that
Do they have any genuine reason
