### ISSUE TITLE
Game crashes when loading into a world.

### ISSUE THREAD

**Issue by Valorioo** [FrozenBlock/WilderWild#257]
**Description of the Bug Encountered**

**Steps To Reproduce**
1. Join singleplayer world
2. 
3. 
4. 

**Expected Behavior**
Game crashes completely.

**Screenshots**

**Logs**

// You should try our sister game, Minceraft!

Time: 2023-06-29 18:33:34
Description: Exception generating new chunk

java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / wilderwild:old_growth_birch_taiga]=net.minecraft.class_1959@4e05e47b}]
	at net.minecraft.class_7510.method_44210(class_7510.java:100)
	at net.minecraft.class_2794.method_44215(class_2794.java:136)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at net.minecraft.class_2794.method_12102(class_2794.java:397)
	at net.minecraft.class_2806.method_20613(class_2806.java:145)
	at net.minecraft.class_2806.method_12154(class_2806.java:292)
	at net.minecraft.class_3898.method_17225(class_3898.java:679)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:673)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:62)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_7510.method_44210(class_7510.java:100)
	at net.minecraft.class_2794.method_44215(class_2794.java:136)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at net.minecraft.class_2794.method_12102(class_2794.java:397)
	at net.minecraft.class_2806.method_20613(class_2806.java:145)
	at net.minecraft.class_2806.method_12154(class_2806.java:292)
	at net.minecraft.class_3898.method_17225(class_3898.java:679)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:673)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:62)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)

-- Chunk to be generated --
Details:
	Location: -1,-1
	Position hash: -1
	Generator: net.minecraft.class_3754@5cb73b69
Stacktrace:
	at net.minecraft.class_3898.method_17225(class_3898.java:679)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:673)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:62)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 625
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 0 game time, 0 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:367)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:315)
	at net.minecraft.class_1132.method_3823(class_1132.java:68)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1431820736 bytes (1365 MiB) / 5133828096 bytes (4896 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 4.01
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) HD Graphics 530
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x1912
	Graphics card #0 versionInfo: DriverVersion=31.0.101.2111
	Graphics card #1 name: NVIDIA GeForce GTX 1080
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1b80
	Graphics card #1 versionInfo: DriverVersion=31.0.15.3598
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Virtual memory max (MB): 39819.03
	Virtual memory used (MB): 32277.09
	Swap memory total (MB): 15360.00
	Swap memory used (MB): 735.35
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		alloy_forgery: Alloy Forgery 2.0.19+1.19
		antighost: AntiGhost 1.19.1-fabric0.58.5-1.1.5
			crowdin-translate: CrowdinTranslate 1.4+1.19
		applecrates: Apple Crates 2.8.5
		architectury: Architectury 6.5.85
		artifacts: Artifacts 7.1.1+fabric
			expandability: ExpandAbility 6.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		attributefix: AttributeFix 17.1.3
		badpackets: Bad Packets 0.2.1
		balm-fabric: Balm 4.5.4
		bcc: BetterCompatibilityChecker 2.0.2-build.16+mc1.19.1
		bclib: BCLib 2.1.6
		beachparty: Beachparty 1.0.8
		beautify: Beautify 1.1.0+fabric-1.19.2
		bettervillage: Better village 3.0.0
		bhmenu: BHMenu-Fabric 1.19-1.3
		bookshelf: Bookshelf 16.2.17
		carryon: Carry On 2.0.4.6
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.1
		cem: Custom Entity Models 0.7.3-1.19
			completeconfig-base: completeconfig-base 2.2.0
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.2.0
		charm: Charm 4.4.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		charm_fixer: Charm Fixer 1.0.0
		chipped: Chipped 2.1.4
		citresewn: CIT Resewn 1.1.2+1.19.2
			citresewn-defaults: CIT Resewn: Defaults 1.1.2+1.19.2
		clienttweaks: Client Tweaks 8.1.0
		cloth-api: Cloth API 4.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-scissors-api-v1: Cloth Scissors API v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		cloth-config: Cloth Config v8 8.2.88
		clumps: Clumps 9.0.0+14
		clutter: Clutter 1.19.2-0.2.1
		collective: Collective 6.48
		completeconfig: CompleteConfig 2.1.0
			coat: Coat 1.0.0-beta.19+mc22w17a
			completeconfig-gui-coat: completeconfig-gui-coat 2.1.0
			completeconfig-gui-yacl: completeconfig-gui-yacl 2.1.0
		continuity: Continuity 2.0.1+1.19
		controlling: Controlling For Fabric 10.0+7
		convenientdecor: Convenient Decor 0.1.0
		corgilib: CorgiLib 1.0.0.32
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		create: Create 0.5.0.i-961+1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.8.a-4
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			porting_lib: Porting Lib 2.1.784+1.19.2
				forge_tags: Porting Lib Tags 3.0
				mm: Manningham Mills 2.3
				porting_lib_accessors: Porting Lib Accessors 2.1.784+1.19.2
				porting_lib_attributes: Porting Lib Attributes 2.1.784+1.19.2
				porting_lib_base: Porting Lib Base 2.1.784+1.19.2
				porting_lib_common: Porting Lib Common 2.1.784+1.19.2
				porting_lib_constants: Porting Lib Constants 2.1.784+1.19.2
				porting_lib_entity: Porting Lib Entity 2.1.784+1.19.2
				porting_lib_extensions: Porting Lib Extensions 2.1.784+1.19.2
				porting_lib_fake_players: Porting Lib Fake Players 2.1.784+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.784+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.784+1.19.2
				porting_lib_model_loader: Porting Lib Model Loader 2.1.784+1.19.2
				porting_lib_models: Porting Lib Models 2.1.784+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.784+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.784+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.784+1.19.2
				serialization_hooks: Serialization Hooks 0.3.26
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			registrate-fabric: Registrate for Fabric 1.1.50-MC1.19.2
		creativecore: CreativeCore (Fabric) 2.9.3
		crittersandcompanions: Critters and Companions 1.19.2-2.0.1
		cull-less-leaves: Cull Less Leaves 1.0.6
			conditional-mixin: conditional mixin 0.3.0
		culturaldelights: Cultural Delights Fabric 0.14.9+1.19.2
			terraform-wood-api-v1: Terraform Wood API (v1) 4.2.0
		dataattributes: Data Attributes 1.4.2
		dawn: Dawn API 3.5.0
		debugify: Debugify 2.8.0
		diagonalfences: Diagonal Fences 4.2.5
		do_a_barrel_roll: Do a Barrel Roll 2.6.2+1.19.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cicada: CICADA 0.1.2
				langfiles-plus: Langfiles Plus 1.0.0
		doapi: Lets Do Api 1.1.0
		doubledoors: Double Doors 4.2
		dramaticdoors: Dramatic Doors (Fabric) 1.19.2-2.0.0
		dungeons_arise: When Dungeons Arise 2.1.54
		dynamicfps: Dynamic FPS 2.2.0
		elytraslot: Elytra Slot 6.1.0+1.19.2
		enchancement: Enchancement 1.19-14
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		enchantinginfuser: Enchanting Infuser 4.2.2
		enchdesc: EnchantmentDescriptions 13.0.14
		enhancedblockentities: Enhanced Block Entities 0.7.2+1.19.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			spruceui: SpruceUI 4.0.0+1.19
		entityculling: EntityCulling-Fabric 1.6.1-mc1.19.2
		extrakeybinds: ThatRobins Extra Origins Keybinds 0.4.0+1.17-1.19.2
		extraorigins: Extra Origins 1.19-2
		fabric-api: Fabric API 0.75.1+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.0+82db024a90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.25+cafc6e8e90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.1+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.2+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.7+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.35+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.5+dce4603e90
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.38+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.12+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.15+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.23+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.1+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+1adbf27790
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+1adbf27790
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.24+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.27+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.9.1+kotlin.1.8.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.19.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.17
		farmersdelight: Farmer's Delight 1.19.2-1.3.9
		farsight: Farsight Mod 1.19-2.4
			com_github_jctools_jctools_jctools-core: jctools-core v4.0.1
		fastload: Fast Load 2.6.11
		fastquit: FastQuit 2.1.0+1.19-1.19.2
		ferritecore: FerriteCore 5.0.3
		figura: Figura 0.1.0+1.19.2-6316a24
			com_github_kingdom-of-the-moon_luaj_luaj-core: luaj-core 3.0.6-figura
			com_github_kingdom-of-the-moon_luaj_luaj-jse: luaj-jse 3.0.6-figura
			org_java-websocket_java-websocket: Java-WebSocket 1.5.2
		forgeconfigapiport: Forge Config API Port 4.2.11
		furnish: Furnish 23
		galosphere: Galosphere 1.19.2-1.3.0
		geckolib3: Geckolib 3.1.40
			com_eliotlash_mclib_mclib: mclib 20
		go-fish: Go Fish 1.6.0-1.19.1
		grindenchantments: Grind Enchantments 2.0.0+1.19.2
		guardiansgalore: GuardiansGalore 1.19.2-3.0
		handcrafted: Handcrafted 2.0.6
		icarus: Icarus 1.13
		iceberg: Iceberg 1.0.46
		immersive_paintings: Immersive Paintings 0.6.1+1.19.2
		indium: Indium 1.0.9+mc1.19.2
		infinitybuttons: Infinity Buttons 3.1.0-mc1.19.2
		inmis: Inmis 2.7.1-1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		iris: Iris 1.5.0
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre8
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		jamlib: JamLib 0.6.0+1.19
		java: OpenJDK 64-Bit Server VM 17
		kiwi: Kiwi Lib 8.1.2
		konkrete: Konkrete 1.6.0
		labels: labels 1.19.2-1.9
		languagereload: Language Reload 1.5.4+1.19.2
		libipn: libIPN 2.0.2
		libraryferret: Library ferret 4.0.0
		lithium: Lithium 0.10.4
		lootr: Lootr 0.4.25.64
		luphieclutteredmod: Cluttered 2.0
		magnumtorch: Magnum Torch 4.2.1
		malilib: MaLiLib 0.13.0
		meadow: Meadow 1.1.1
		memoryleakfix: memory Leak Fix 1.19.3-0.7.0
		midnightcontrols: MidnightControls 1.7.4+1.19
			org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		midnightlib: MidnightLib 1.0.0
		minecraft: Minecraft 1.19.2
		moonlight: Moonlight 1.19.2-2.2.27
		morediscs: More discs 1.19.2-27
		mousetweaks: Mouse Tweaks 2.22
		mythicmetals: Mythic Metals 0.17.3+1.19.2
			additionalentityattributes: Additionalentityattributes 1.2.0+1.19
		mythorigins: Mythology Origins 1.19-0.2.0
		netherportalfix: NetherPortalFix 10.0.1
		nethersdelight: Nether's Delight 1.0.1
			disable_custom_worlds_advice: Disable Custom Worlds Advice 3.0
		nets: Not Enough Trinket Slots (NETS) 0.3.5.2
		nightlights: Night Lights 1.1
		nochatreports: No Chat Reports 1.19.2-v1.13.12
		notenoughanimations: NotEnoughAnimations 1.6.2
		nounusedchunks: No Unused Chunks 1.4
			tcdcommons: TCD Commons API 1.1+1.19.2
		openloader: OpenLoader 15.0.1
		optigui: OptiGUI 1.1.6
			org_apache_commons_commons-text: commons-text 1.9
		origins: Origins 1.7.1
			apoli: Apoli 2.6.1
				calio: Calio 1.7.0
				playerabilitylib: Pal 1.6.0
		originsumbrellas: Origins: Umbrellas 1.5.4
		owo: oωo 0.9.3+1.19
		patchouli: Patchouli 1.19.2-77-FABRIC
			fiber: fiber 0.23.0-2
		pehkui: Pehkui 3.6.3+1.14.4-1.19.3
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		pfm: Paladin's Furniture 1.1.1
		polymorph: Polymorph 0.46.1+1.19.2
			cardinal-components-item: Cardinal Components API (items) 5.0.1
			spectrelib: SpectreLib 0.11.0+1.19
		prism: Prism 1.0.3
		promenade: Promenade 2.7.1
			terraform-shapes-api-v1: Terraform Shapes API (v1) 4.0.0
		puzzle: Puzzle 1.4.2-1.19
			puzzle-base: Puzzle Base 1.4.2-1.19
			puzzle-gui: Puzzle GUI 1.4.2-1.19
			puzzle-models: Puzzle Models 1.4.2-1.19
			puzzle-splashscreen: Puzzle Splash Screen 1.4.2-1.19
		puzzleslib: Puzzles Lib 4.3.12
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
		quartzelv: Quartz Elevator 2.1.5+1.19
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
		resourcefullib: Resourceful Lib 1.1.23
		rightclickharvest: Right Click Harvest 3.1.0+1.19-1.19.2
		rocks: This Rocks! 1.6.1
		rusticated: Rusticated 2.0.5-fabric
		satin: Satin 1.9.0
		servercore: ServerCore 1.3.3-1.19.2
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			me_lucko_spark-api: spark-api 0.1-SNAPSHOT
			placeholder-api: Placeholder API 2.0.0-pre.1+1.19.2
		simplyswords: Simply Swords 1.43.1-1.19.2
		sit: Sit 1.19-20
		smoothboot: Smooth Boot 1.19-1.7.1
		sod: Grass Overhaul (Sod) 23.5.28
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.16+mc1.19.2-build.90
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		spark: spark 1.10.29
		starlight: Starlight 1.1.1+fabric.ae22326
		structory: Structory 1.0.1
		supplementaries: Supplementaries 1.19.2-2.2.64
		tempad: Tempad 1.4.3
			team_reborn_energy: Energy 2.2.0
		terrablender: TerraBlender 2.0.1.136
		timeoutout: TimeOut Out 1.0.3+1.19.1
		toofast: TooFast 1.0.0
		tooltipfix: ToolTip Fix 1.1.1-1.19
		totw_additions: Towers of the Wild: Additions 1.2.4
		trashcans: Trash Cans Mod 0.0.2-1.19.X
		trinkets: Trinkets 3.4.2
		vinery: Vinery 1.1.4
		vmp: Very Many Players 0.2.0+beta.7.28
		voicechat: Simple Voice Chat 1.19.2-2.4.12
		wilderwild: Wilder Wild 2.0.3-Fabric+1.19.2
			frozenlib: FrozenLib 1.2.4-Fabric+1.19.2
				blue_endless_jankson: jankson 1.2.2
			nbtcrafting: NBT Crafting 2.2.3+mc1.19
		wthit: wthit 5.16.2
		xaerominimap: Xaero's Minimap 23.1.0
		xaeroworldmap: Xaero's World Map 1.28.9
		yet-another-config-lib: YetAnotherConfigLib 2.2.0-for-1.19.2
		yigd: You're in Grave Danger 1.4.8
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.9
			org_javassist_javassist: javassist 3.28.0-GA
			org_reflections_reflections: reflections 0.10.2
		yungsbridges: YUNG's Bridges 1.19.2-Fabric-3.1.0
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Flywheel Backend: GL33 Instanced Arrays
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, Fabric Mods, Supplementaries Generated Pack
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.14.17-1.19.2

**Additional context**

**Comment by AViewFromTheTop** [comment]
Does this still happen in the latest version?
