### ISSUE TITLE
Silk touching Sculk Slabs drops Palm Slabs..

### ISSUE THREAD

**Issue by Xfrtrex** [FrozenBlock/WilderWild#259]
yeah, how did this happen? anyways yeah we need to fix this.

**Comment by AViewFromTheTop** [comment]
what the hell

**Comment by AViewFromTheTop** [comment]
@Xfrtrex just fixed
thanks for letting me know

**Comment by Xfrtrex** [comment]
> @Xfrtrex just fixed thanks for letting me know

NP i was in an ancient city and picked up a palm slab and was so confused

**Comment by AViewFromTheTop** [comment]
> > @Xfrtrex just fixed thanks for letting me know
> 
> NP i was in an ancient city and picked up a palm slab and was so confused

Trust me I would be too lmao
Unfortunately I just can’t get silk touch for some reason in survival I get like every enchant other than it
