### ISSUE TITLE
on version beyond 2.0.4 i get the datapack corruption popup when opening world

### ISSUE THREAD

**Issue by Taleuxss** [FrozenBlock/WilderWild#260]
**Description of the Bug Encountered**
on version beyond 2.0.4 i get the datapack corruption popup when opening world but if i disable C2ME it will work again 
although using C2ME and Wilder Wild alone works, so i dont know much about whats going on here i tried to dig deeper but i gave up after awhile, i remember C2ME BCLib Better End as problems but also thinking combinations of C2ME and other optimization mods 

**Expected Behavior**
open world

**Screenshots**
on the image below, after adding all the selected mods below to my pack it would cause the problem, i didnt go futher to see what is 100% the issues like i didnt see if its just iris + c2me etc. (i remember automodpack and resourcify being fine)
![image](https://github.com/FrozenBlock/WilderWild/assets/50016554/60105bc1-6176-4930-b5b0-8bc4964ffa5b)
![2023-07-01_17 50 39](https://github.com/FrozenBlock/WilderWild/assets/50016554/4298cc96-f329-4552-91a4-d3b3f1dcc13c)
![2023-07-01_17 50 37](https://github.com/FrozenBlock/WilderWild/assets/50016554/6a1facf2-0b29-4c44-b2d0-64997c0151ea)

**Logs**
https://mclo.gs/b2tE9x1

**Additional context**
version 2.0.4 works

**Comment by DayIsGone** [comment]
I am having the same issue if it helps the only mods I have in my folder that the op has are as follows:
betterstats-2.10.3+1.20.1.jar and continuity-3.0.0-beta.2+1.20.jar

doing some more testing version 2.0.6 works fine with those two mods removed. I did try loading the game with each of them added to my mods folder and putting in either would cause the error to happen

**Comment by Treetrain1** [comment]
this provides a further explanation to #268
the issue is introduced in 2.0.5
im going to track this issue there
