### ISSUE TITLE
make Ancient Horn Fragments rarer. 

### ISSUE THREAD

**Issue by Xfrtrex** [FrozenBlock/WilderWild#262]
After a long survival server, players have found Ancient Horn Fragments extremely easy to get.
After around 4 or so Ancient Cities, I have collected around 2 stacks of fragments. This weapon, should be made rarer, for its power. 

How rare should it be? I am thinking extremely rare. maybe even around Silence trim level of rare. however, you could make it maybe about as rare as the ward trim instead.

_also another thing people seem to have a consensus on, is along with making it rarer, make it slightly more powerful such as more damage to players and a slight bit shorter cooldown_

**Comment by AViewFromTheTop** [comment]
> After a long survival server, players have found Ancient Horn Fragments extremely easy to get. After around 4 or so Ancient Cities, I have collected around 2 stacks of fragments. This weapon, should be made rarer, for its power.
> 
> How rare should it be? I am thinking extremely rare. maybe even around Silence trim level of rare. however, you could make it maybe about as rare as the ward trim instead.
> 
> _also another thing people seem to have a consensus on, is along with making it rarer, make it slightly more powerful such as more damage to players and a slight bit shorter cooldown_

and in other cases i go to four cities and can only make two horns

**Comment by AViewFromTheTop** [comment]
and sorry but i dont give a flying f*ck about what players are saying. im not making it more powerful and the cooldown isnt getting shortened.
they just want another stereotypical "hahaha mod item is so op i can kill everyone instantly" item, and im not willing to lean *further* into that. me and Merp have had COUNTLESS discussions about it, and everyone on the team even agreed to not make it any stronger.

**Comment by AViewFromTheTop** [comment]
again, keep in mind how it *appears* like mojang rejects almost 90% of community feedback
thats because the average player only cares about making things easier for themselves, and they dont realize that if their feedback were implemented, the longetivity and fun of the game would expire much more rapidly than it would otherwise
both me and mojang *DO* consider all feedback, and know what to just ignore. this is one of those cases.
if anything, a better solution would be to just remove the horn altogether- unfortunately we've gone too far, so coming up with ideas to balance it (and right now it's as good as it's ever been, though not perfect,) is all we can really do at this point.
implementing feedback to literally undo ALL the work gone towards balancing it is just extremely counterintuitive, im sorry.

**Comment by AViewFromTheTop** [comment]
this is also like half the reason i insist i continue working on the mod
i dont want the wrong feedback and ideas being implemented and id prefer everything to be executed as good as possible in my eyes

**Comment by AViewFromTheTop** [comment]
ill look into its rarity but thats all im changing
just like your message said, the weapon is *powerful* and i dont want to make it any more powerful than it already is

**Comment by AViewFromTheTop** [comment]
sorry for going off

**Comment by Xfrtrex** [comment]
> and sorry but i dont give a flying f*ck about what players are saying. im not making it more powerful and the cooldown isnt getting shortened. they just want another stereotypical "hahaha mod item is so op i can kill everyone instantly" item, and im not willing to lean _further_ into that. me and Merp have had COUNTLESS discussions about it, and everyone on the team even agreed to not make it any stronger.

i said _slightly_

**Comment by Xfrtrex** [comment]
also that was a side thing, the main point is making it rarer.

**Comment by Xfrtrex** [comment]
if you dont want to make them more powerful thats fair, i kinda agree with your points (except i do think they should deal more damage to players, cause i guess you seem to do tests on people who dont have armor, cause they do like half a heart or sometimes NO damage

**Comment by AViewFromTheTop** [comment]
> if you dont want to make them more powerful thats fair, i kinda agree with your points, except i do think they should deal more damage to players, cause i guess you seem to do tests on people who dont have armor, cause they do like half a heart or sometimes NO damage

half a heart or no damage??????
the ONLY way that happened is a config change. unless im missing something.

**Comment by AViewFromTheTop** [comment]
> if you dont want to make them more powerful thats fair, i kinda agree with your points, except i do think they should deal more damage to players, cause i guess you seem to do tests on people who dont have armor, cause they do like half a heart or sometimes NO damage

ok long story short whoever made damage sources data-driven (tree) didnt make it bypass armour alonside the port
ill see if i can figure it out really quick

**Comment by AViewFromTheTop** [comment]
@Xfrtrex ok basically i just have to add the damage source to a tag and the armour issue should be fixed
once again, holy shit thanks for letting me know

**Comment by AViewFromTheTop** [comment]
lmao why are witches immune to sonic booms
guess theyll be immune to ancient horns as well then

**Comment by AViewFromTheTop** [comment]
@Xfrtrex ok test with latest commit if intellij is finally working for you

**Comment by AViewFromTheTop** [comment]
im probably gonna see if i can kinda add a "tomb" area in the center of ancient cities

**Comment by Xfrtrex** [comment]
> @Xfrtrex ok test with latest commit if intellij is finally working for you

its not :/

**Comment by Xfrtrex** [comment]
> lmao why are witches immune to sonic booms guess theyll be immune to ancient horns as well then

they what?!

**Comment by AViewFromTheTop** [comment]
> they what?!

i definitely misunderstood but that's what the tag is called
i think they take significantly reduced damage from them

**Comment by AViewFromTheTop** [comment]
> its not :/

ill dm you on cf with a build soon

**Comment by AViewFromTheTop** [comment]
> > its not :/
> 
> ill dm you on cf with a build soon

@Xfrtrex

**Comment by Xfrtrex** [comment]
whats cf

**Comment by AViewFromTheTop** [comment]
> whats cf

CurseForge

**Comment by Xfrtrex** [comment]
also whats added anyways

**Comment by AViewFromTheTop** [comment]
> also whats added anyways

@Xfrtrex https://github.com/AViewFromTheTop/WilderWild/blob/1.20/CHANGELOG.txt

**Comment by Treetrain1** [comment]
cf L fr

**Comment by AViewFromTheTop** [comment]
@Xfrtrex does the version i sent on CF resolve this?

**Comment by Treetrain1** [comment]
Is this resolved?
