### ISSUE TITLE
Jellyfish unoptimized getting 

### ISSUE THREAD

**Issue by otDan** [FrozenBlock/WilderWild#263]
**Description of the Bug Encountered**
The jellyfish takes up the major amount of a ticks time

**Expected Behavior**
Not taking up such an amount

**Screenshots**
![image](https://github.com/FrozenBlock/WilderWild/assets/59731738/7e68abf0-4e83-4437-8e7f-7abe1310efe6)

**Comment by AViewFromTheTop** [comment]
That kind of has to happen in order to split them between oceans and Jelly Caves properly

**Comment by AViewFromTheTop** [comment]
@Treetrain1 do you have literally any ideas on how to work around this and get it to run faster lol
ive been trying and cant come up with anything- the ONLY idea i have is maybe a system like the Palm Crown tracker
honestly im gonna try doing that now that i think of it

**Comment by AViewFromTheTop** [comment]
just implemented it.
unfortunately it doesn't *completely* solve the problem, but it is a LOT better.
