### ISSUE TITLE
Storing Experience 

### ISSUE THREAD

**Issue by Xfrtrex** [FrozenBlock/WilderWild#264]
A way to take your experience, and put it into hanging tendrils, either by interacting with bottles o' enchanting, or somehow taking XP from the XP bar. needs more ideas on how to do this

**Comment by AViewFromTheTop** [comment]
I don’t think this is something for Wilder Wild to do

**Comment by AViewFromTheTop** [comment]
@Osmiooo don’t forget to post about 2.1 on the Twitter account lol

**Comment by Treetrain1** [comment]
isnt sculk literally just an experience block

**Comment by AViewFromTheTop** [comment]
> isnt sculk literally just an experience block

Yes
Hanging Tendrils solve the issue of Sculk being annoying to farm XP with

**Comment by Osmiooo** [comment]
> @Osmiooo don’t forget to post about 2.1 on the Twitter account lol

oh yeah right

**Comment by Osmiooo** [comment]
there

**Comment by AViewFromTheTop** [comment]
https://twitter.com/fb_oasis/status/1682540132987990016?s=46&t=uGScwX6kYEhgftCaKJkCgQ
@Osmiooo 1.18 not 1.19 lol

**Comment by AViewFromTheTop** [comment]
Ty btw

**Comment by Osmiooo** [comment]
> https://twitter.com/fb_oasis/status/1682540132987990016?s=46&t=uGScwX6kYEhgftCaKJkCgQ @Osmiooo 1.18 not 1.19 lol

i copied tree's message

**Comment by Treetrain1** [comment]
> [twitter.com/fb_oasis/status/1682540132987990016?s=46&t=uGScwX6kYEhgftCaKJkCgQ](https://twitter.com/fb_oasis/status/1682540132987990016?s=46&t=uGScwX6kYEhgftCaKJkCgQ) @Osmiooo 1.18 not 1.19 lol

its supposed to be 1.19
remember we stopped supporting version 1.19 in favor of 1.19.2
