### ISSUE TITLE
Wilder Wild removes river biome generation sometimes

### ISSUE THREAD

**Issue by Soro335** [FrozenBlock/WilderWild#266]
**Description of the Bug Encountered**
Generation in Wilder Wild can remove rivers in places where they should be

**Steps To Reproduce**
1. Create worlds in Vanilla and with the Wilder Wild(seed: -1000817228682010047)
2. Teleport to (/execute in minecraft:overworld run tp @s 7755.33 116.34 -2266.77 -2230.90 46.95) in Vanilla and with Wilder Wild

**Expected Behavior**
River should generate, but this does not happen with Wilder Wild

**Screenshots**
![image](https://github.com/FrozenBlock/WilderWild/assets/82042293/3ce4e8ec-aec7-4136-81ec-490d36e37ec1)
![image](https://github.com/FrozenBlock/WilderWild/assets/82042293/30b957c1-afe9-4aa1-b7fa-8e924ae172bd)

**Comment by Xfrtrex** [comment]
what version is this

**Comment by Treetrain1** [comment]
what is the difference between the two screenshots?

**Comment by Soro335** [comment]
> what version is this

this problem is also frozen lib related, but this problem starting with 2.0+

**Comment by Soro335** [comment]
> what is the difference between the two screenshots?

I think you should test yourself!

**Comment by Treetrain1** [comment]
> > what is the difference between the two screenshots?
> 
> I think you should test yourself!

i mean based on the screenshot the terrain is unchanged apart from placed features

**Comment by Soro335** [comment]
> > > what is the difference between the two screenshots?
> > 
> > 
> > I think you should test yourself!
> 
> i mean based on the screenshot the terrain is unchanged apart from placed features

Terrain shouldn't change lol

**Comment by Treetrain1** [comment]
> > > > what is the difference between the two screenshots?
> > > 
> > > 
> > > I think you should test yourself!
> > 
> > 
> > i mean based on the screenshot the terrain is unchanged apart from placed features
> 
> Terrain shouldn't change lol

so what river generation is removed

**Comment by Soro335** [comment]
> > > > > what is the difference between the two screenshots?
> > > > 
> > > > 
> > > > I think you should test yourself!
> > > 
> > > 
> > > i mean based on the screenshot the terrain is unchanged apart from placed features
> > 
> > 
> > Terrain shouldn't change lol
> 
> so what river generation is removed

Do you know how generation works since 1.18?

**Comment by Soro335** [comment]
> > > > > what is the difference between the two screenshots?
> > > > 
> > > > 
> > > > I think you should test yourself!
> > > 
> > > 
> > > i mean based on the screenshot the terrain is unchanged apart from placed features
> > 
> > 
> > Terrain shouldn't change lol
> 
> so what river generation is removed

River BIOME generation

**Comment by Xfrtrex** [comment]
treetrain, with all due respect, i dont think you know how this works

**Comment by AViewFromTheTop** [comment]
@Treetrain1 the BIOME isnt there
easiest way to tell: seagrass is gone, which is a river feature

**Comment by AViewFromTheTop** [comment]
@Soro335 this has been fixed
