### ISSUE TITLE
Mesoglea let me see into forever

### ISSUE THREAD

**Issue by OriWritesAPlugin** [FrozenBlock/WilderWild#269]
**Description of the Bug Encountered**

Mesoglea seem a little _too_ see-through, allowing me to see the spaces between/beyond blocks in the style of blockclipped spectator mode

**Steps To Reproduce**
1. Place a mesoglea block
2. Look at the mesoglea block

**Expected Behavior**

I'd guess they're expected to have a transparency that functions like the outer edge of slime blocks

**Screenshots**

![2023-07-16_15 23 35](https://github.com/FrozenBlock/WilderWild/assets/19622123/6d1438ae-5b9b-460f-ad39-3d906a83142f)
![2023-07-16_15 24 12](https://github.com/FrozenBlock/WilderWild/assets/19622123/7b57682b-0083-4349-a0f6-400c27cc6902)
![2023-07-16_15 28 11](https://github.com/FrozenBlock/WilderWild/assets/19622123/2664a1dd-19e6-490d-9654-1c474bff15a5)
![2023-07-16_15 23 01](https://github.com/FrozenBlock/WilderWild/assets/19622123/27ae6d1b-7dad-48eb-bee5-237e45ca5316)

**Logs**

None to mention, likely just a block thing. Logged versions:

Native libraries:  Mods:   [✔] qfapi-7.0.6_qsl-6.0.4_fapi-0.85.0_mc-1.20.1   [✔] WilderWild-2.0.6-Fabric+1.20.1

  Java Arguments: [-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms8192m, -Xmx8192m, -Duser.language=en]   Minecraft 

[main/INFO]: Loading Minecraft 1.20.1 with Quilt Loader 0.19.2

**Additional context**
Not doing anything fancy with rendering settings, tested this on a bog-standard install (just for this purpose). Intending to use this in a big exploration pack with friends, kudos for making a lovely mod! We're especially excited about the fireflies. Let me know if there's any setups you want me to try.

**Comment by Treetrain1** [comment]
Fixed in future release, 2.1

**Comment by AViewFromTheTop** [comment]
> Fixed in future release, 2.1

huh ive never had that bug before lol I doubt I accidentally fixed it
are you sure

**Comment by Treetrain1** [comment]
> > Fixed in future release, 2.1
> 
> huh ive never had that bug before lol I doubt I accidentally fixed it are you sure

ive had the issue on 2.0.x but not once on 2.1

**Comment by AViewFromTheTop** [comment]
@Treetrain1 issue should be closed

**Comment by Treetrain1** [comment]
> @Treetrain1 issue should be closed

true
