### ISSUE TITLE
Server crashes upon creating a world (1.20.1)

### ISSUE THREAD

**Issue by Zunwolf1896** [FrozenBlock/WilderWild#274]
**Starting a new world on an online server, the server crashes upon reaching spawn area: 68%, it starts throwing out errors. **

**Steps To Reproduce**
1. Install mods insto server
2. Load new world
3. World won't load
4. 

**Expected Behavior**
World to load and server to be online

**Screenshots**

**Logs**
[latest.log](https://github.com/FrozenBlock/WilderWild/files/12136775/latest.log) (The crash and errors are at line 2193)

**Additional context**
The log above shoudl list the Mods I have in. I am using version 2.1-Fabric+1.20.1.jar for Wilder Wilds. Using the exact same mods, we are able to open and use worlds no problem in Single Player, it is only on the server we have experienced this.

**Comment by Treetrain1** [comment]
This is an issue on Lost Features side, same issue as #272
