### ISSUE TITLE
Scorched Sand feature not generate and cannot be placed with command

### ISSUE THREAD

**Issue by Soro335** [FrozenBlock/WilderWild#275]
In version 2.1 Scorched Sand feature does not work. 
Cannot be found in a world with single Desert biome. 
And also cannot be placed with command /place feature wilderwild:scorched_sand... 

![image](https://github.com/FrozenBlock/WilderWild/assets/82042293/522e7d2f-3a3a-490f-b100-26519a018692)

**Comment by AViewFromTheTop** [comment]
jesus christ what now i hate this

**Comment by AViewFromTheTop** [comment]
@Treetrain1 new lib and ww pr coming up prs are getting really annoying

**Comment by AViewFromTheTop** [comment]
actually just ww
