### ISSUE TITLE
Mesoglea Bubble Elevators

### ISSUE THREAD

**Issue by Noobulus** [FrozenBlock/WilderWild#277]
**Explain your suggestion here.**
A clear explanation of what you would like to see and why. "I'd like to see... added because..." 

I would like to have the ability to make bubble columns with waterlogged mesoglea in lieu of regular water source blocks. Mesoglea is already permeable when wet, allowing for some neat builds, but I think that adding this functionality would add both a cleaner way to construct bubble columns in open spaces and additional depth to mesoglea as a feature.

**Describe alternatives you've considered**

Bubble columns are an existing feature, but allowing them to propagate through mesoglea would open up some exciting possibilities for builds. This is an integration of two existing mechanics, so I'm not sure what an alternative would be.

**Additional context**
Add any other context or screenshots about the suggestion here.

Example usage:
![2023-07-25_17 17 46](https://github.com/FrozenBlock/WilderWild/assets/20390143/197e71d2-ef33-48b4-b586-6ac9cdc7ea4d)

**Comment by AViewFromTheTop** [comment]
this contradicts existing minecraft features- kelp, trapdoors, etc etc etc waterlogged doesnt do this.
its possible this may be added with a config option as it is a neat feature to have, but i disagree with it being enabled by default unless mojang reworks bubble columns to work with waterlogged blocks.

**Comment by MerpisMe** [comment]
> this contradicts existing minecraft features- kelp, trapdoors, etc etc etc waterlogged doesnt do this.

thats kind of the appeal to the idea imo

it would be neat because it'd be a way to have a single block wide bubble column without using hacky methods like glass panes or trapdoors

**Comment by MerpisMe** [comment]
also, the difference between other waterlogged blocks and mesoglea is that mesoglea straight up *becomes* the liquid
it coalesces

**Comment by AViewFromTheTop** [comment]
> thats kind of the appeal to the idea imo
> 
> it would be neat because it'd be a way to have a single block wide bubble column without using hacky methods like glass panes or trapdoors

that's not really hacky-
irl we'd 100% need something around water lmao
water towers arent considered hacky or anything

> also, the difference between other waterlogged blocks and mesoglea is that mesoglea straight up _becomes_ the liquid it coalesces

hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
why do you keep doing this to meeeeee
no just
no
it conflicts with minecrafts design
stop tempting me to say otherwise

**Comment by AViewFromTheTop** [comment]
mesoglea renders as a full block (unless the *not default* option is set to true)
the water renders inside it
mesoglea doesn't turn into lava though
and mesoglea isn't registered as a separate liquid either

**Comment by AViewFromTheTop** [comment]
@MerpisMe ok how about this
it gets added but behind a config
if we can manage to have enough fun with it then screw it itll be true by default

**Comment by Noobulus** [comment]
> this contradicts existing minecraft features- kelp, trapdoors, etc etc etc waterlogged doesnt do this. its possible this may be added with a config option as it is a neat feature to have, but i disagree with it being enabled by default unless mojang reworks bubble columns to work with waterlogged blocks.

I think this is more of a technical limitation than it is an intentional design choice. Bubble columns are a distinct block rather than just some state of water, so it wouldn't be possible for them to intersect with waterlogged blocks without changing how they are implemented.

That being said, I'd love to see this feature as part of the mod whether it is enabled by default or not.

**Comment by Noobulus** [comment]
Also, mesoglea is a wonderfully strange block as is - nothing in the base game really works like it, so we're already bending some rules just to have it exist. I think that strangeness is part of what makes it compelling as a feature.

**Comment by AViewFromTheTop** [comment]
> I think this is more of a technical limitation than it is an intentional design choice. Bubble columns are a distinct block rather than just some state of water, so it wouldn't be possible for them to intersect with waterlogged blocks without changing how they are implemented.

I'm aware, hence why i mentioned mojang possibly reworking them
they absolutely could honestly, but the fact they aren't makes the decision feel a lot more.... intentional on their part.
especially with how they'd shown water flowing through fences at one point, and removed that before snapshots/betas as well.

> That being said, I'd love to see this feature as part of the mod whether it is enabled by default or not.

once im more free ill see what i can do

> Also, mesoglea is a wonderfully strange block as is - nothing in the base game really works like it, so we're already bending some rules just to have it exist. I think that strangeness is part of what makes it compelling as a feature.

you can thank Merp for coming up with its functionality
literal pure genius and im glad to've been able to implement it in that form

**Comment by AViewFromTheTop** [comment]
btw couldn't the waterlogged and bubble column stuff be kind of "fixed" by changing the property from a boolean to an enum

**Comment by MerpisMe** [comment]
> btw couldn't the waterlogged and bubble column stuff be kind of "fixed" by changing the property from a boolean to an enum

waterlogging in general could be fixed by fully implementing the layering system that they completely scrapped just snapshots before 1.13 released

**Comment by Treetrain1** [comment]
> > btw couldn't the waterlogged and bubble column stuff be kind of "fixed" by changing the property from a boolean to an enum
> 
> waterlogging in general could be fixed by fully implementing the layering system that they completely scrapped just snapshots before 1.13 released

what layering system

**Comment by MerpisMe** [comment]
> what layering system

they had a fluid layering system that was almost identical to the one on bedrock which allowed them to not use a blockstate property to define waterlogged blocks
the water would just be completely separate from the blocks

**Comment by AViewFromTheTop** [comment]
@MerpisMe going to need to consult you for this. you're the mesoglea master.
should pearlescent mesoglea have any special interaction with this?
should we consider sideways bubble columns in mesoglea?

**Comment by AViewFromTheTop** [comment]
nvm im not doing sideways columns for now
i need to get the normal ones working first lmao

**Comment by AViewFromTheTop** [comment]
well anyway mesoglea bubble elevators will be in the next update
just need to fix a bug with them

**Comment by AViewFromTheTop** [comment]
@MerpisMe can we make mesoglea bubble columns entirely separate and not carry into water
pleeeeeeaaaseeeee
we could do sideways elevators with mesoglea then which is REALLY something i want
ive been obsessed with the idea of adding currents/fans into mc and this is the PERFECT opportunity

**Comment by AViewFromTheTop** [comment]
i remember you saying that mesoglea simply isnt worthwhile and while i disagreed at that time too, this would absolutely seal the deal
now that i think of it, i just now recall people asking for mesoglea to have current properties with different variants
this is the better way to do that with zero new blocks

**Comment by AViewFromTheTop** [comment]
AND MAYBE YOU CAN DISCONTINUE CURRENTS BY CHANGING THE MESOGLEA COLOUR
