### ISSUE TITLE
Wilder Wild crashes when loading into a world with the latest version of Sodium.

### ISSUE THREAD

**Issue by Fourbo** [FrozenBlock/WilderWild#280]
**Description of the Bug Encountered**
A single-player world can suddenly not be loaded successfully anymore once Wilder Wild is used alongside the latest version of Sodium. Sodium underwent massive changes for version 0.5.0, breaking compatibility when used with Wilder Wild.

**Steps To Reproduce**
1. Added both Sodium 0.5.0 and Wilder Wild v2.1.1 (the latest versions of Iris, Reese's Sodium Options, Sodium Extra, and Quilted Fabric API are also included in this instance, but they are compatible together).
2. Start the game, and the menu loads up like normal.
4. Load into a single player world, it starts loading all the way to the joining world screen, but then switches to saving the world, and the game crashes.

**Expected Behavior**
Single-player world should load like normal.

**Screenshots**
![Screenshot 2023-08-05 002439](https://github.com/FrozenBlock/WilderWild/assets/101537906/6d5771ea-e33b-4b8e-acf3-a33f11f32a0f)

**Logs**
[latest.log](https://github.com/FrozenBlock/WilderWild/files/12266459/latest.log)

**Crash Report**
[crash-2023-08-05_00.24.02-client.txt](https://github.com/FrozenBlock/WilderWild/files/12266456/crash-2023-08-05_00.24.02-client.txt)

**Additional Context**
This is running on the latest version of Quilt Loader (0.19.2) and Quilted Fabric API 0.86.1.

**Comment by Treetrain1** [comment]
Fixed in future version (1.1.2)

**Comment by AViewFromTheTop** [comment]
> Fixed in future version (1.1.2)

@Treetrain1 tree I don’t think we’re regressing by two major versions-
I hope at least

**Comment by Treetrain1** [comment]
> > Fixed in future version (1.1.2)
> 
> @Treetrain1 tree I don’t think we’re regressing by two major versions- I hope at least

sorry typo
