### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Rogenar** [FrozenBlock/WilderWild#281]
After updating from version 2.1.1 to version 2.1.2 it caused my game to crash while creating world.
[latest.log](https://github.com/FrozenBlock/WilderWild/files/12268535/latest.log)
[crash-2023-08-06_04.44.10-client.txt](https://github.com/FrozenBlock/WilderWild/files/12268537/crash-2023-08-06_04.44.10-client.txt)

**Comment by Treetrain1** [comment]
Upgrade Sodium to 0.5.0 or revert to 2.1.1
