### ISSUE TITLE
Crash on start with Sodium (mixin error)

### ISSUE THREAD

**Issue by James103** [FrozenBlock/WilderWild#282]
**Description of the Bug Encountered**
The game crashes on start with a mixin error.

**Steps To Reproduce**
1. Install `sodium-fabric-mc1.20.1-0.5.0`
2. Install `indium-1.0.23+mc1.20.1`
3. Install `wilderwild 2.1.1-Fabric+1.20.1`
4. Install all dependencies of the above mods.
5. Start the game.

**Expected Behavior**
The game should not crash.

**Logs**
[latest.log](https://github.com/comp500/Indium/files/12268588/latest.log)
[crash-2023-08-06_05.24.24-client.txt](https://github.com/comp500/Indium/files/12268589/crash-2023-08-06_05.24.24-client.txt)

**Additional context**
See also https://github.com/comp500/Indium/issues/222

**Comment by James103** [comment]
Closing as it appears to be fixed in 2.1.2.

**Comment by AViewFromTheTop** [comment]
@Treetrain1 im thinking maybe we should find a way to test the sodium version and display a message if it isn’t the same one WW needs
Perhaps a utility to be added to frozenlib?

**Comment by Treetrain1** [comment]
> @Treetrain1 im thinking maybe we should find a way to test the sodium version and display a message if it isn’t the same one WW needs Perhaps a utility to be added to frozenlib?

just add a "breaks" thing in fabric.mod.json lmao
