### ISSUE TITLE
Game crashes on world creation.

### ISSUE THREAD

**Issue by Zelta-Deluxe** [FrozenBlock/WilderWild#283]
**Description of the Bug Encountered**
Game crashes exactly when a world opens. This happens with FrozenLib by itself but also with Wilder Wild or both.

**Steps To Reproduce**
1. Install the same mods from the log.
2. Open the game.
3. Create a world.

**Expected Behavior**
Joining the world.

**Screenshots**

**Logs**
[latest.log](https://github.com/FrozenBlock/WilderWild/files/12283341/latest.log)

**Additional context**
Minecraft runs normally without this mod or FrozenLib. Fatal errors ran in render thread and error details say that it is related to the player rendering, (maybe?).

**Comment by Zelta-Deluxe** [comment]
Oh. Sorry for not specifying my version. I'm running Fabric 1.19.2, not 1.20. Versions you are mentioning are for 1.20.

**Comment by Treetrain1** [comment]
Oh, sorry for assuming that.

We have stopped support for 1.19.2, as it is not worth our time to update an outdated version.
Sorry.
