### ISSUE TITLE
The map of the cypress tree cannot be displayed

### ISSUE THREAD

**Issue by fforepretty** [FrozenBlock/WilderWild#285]
**Description of the Bug Encountered**
The betwitchment module also has cypress trees
Perhaps it was a conflict with other modules that resulted in the loss of the cypress map.

**Steps To Reproduce**
1. none

**Expected Behavior**
Fix errors

**Screenshots**
![image](https://github.com/FrozenBlock/WilderWild/assets/140879602/06d660ad-f7c2-4ea6-b491-8cb4368d7802)
![image](https://github.com/FrozenBlock/WilderWild/assets/140879602/31768f80-0a0a-4ebf-8906-66dc97714aed)

**Logs**
none

**Additional context**
none

**Comment by AViewFromTheTop** [comment]
Closing as this clearly isn't our issue.
