### ISSUE TITLE
Coconuts cannot be thrown while looking at a block

### ISSUE THREAD

**Issue by donkeyrat** [FrozenBlock/WilderWild#286]
**Description of the Bug Encountered**

**Steps To Reproduce**
1. Hold a coconut
2. Look at a block
3. Right-click to throw
4. Nothing happens

**Expected Behavior**

It should be thrown.

**Screenshots**

**Logs**

None needed

**Additional context**

It seems like when you're looking at a block, the coconut's sapling side takes over the projectile side, when the expectation is that if it can't be placed, it should get thrown. It creates an awkward effect where you cannot throw it while looking at a block, which contrasts with vanilla's throwables.
A potential solution is to introduce a separate sapling item crafted with a single coconut, though this likely wouldn't be necessary.

**Comment by AViewFromTheTop** [comment]
I think Mojang would just try to find a workaround to let you throw the Coconut if it can’t be placed.
I’m personally strongly against the idea of having a separate Sapling for Palms (that would also cause inconsistency with Baobabs,) so I wouldn’t go the separate item route. I’ll look into this and see what I can do when I have the time.

**Comment by AViewFromTheTop** [comment]
Fixed in the next update :)
