### ISSUE TITLE
internal server freezes with etcetara and starlight mod

### ISSUE THREAD

**Issue by mateus3c** [FrozenBlock/WilderWild#288]
**Description of the Bug Encountered**

The internal server completely freezes, chunks stop loading, I cant drop anything, mobs dont walk, nothing drops uppon breaking blocks...

**Steps To Reproduce**
1. Install WilderWild with etcetara and/or starlight
2. Walk a little
3. Server freezes

**Expected Behavior**

the server wasnt supposed to freeze

**Screenshots**
![image](https://github.com/FrozenBlock/WilderWild/assets/122059128/9a0fe1b0-cd07-449d-8647-36c4a431d48d)

**Logs**

https://pastebin.com/XTh7RzQS

**Additional context**

**Comment by Nicolol1234** [comment]
i had a similar bug, but my server crashed like 1min after the freeze

**Comment by AViewFromTheTop** [comment]
Does this still occur in 2.2.1?

**Comment by AViewFromTheTop** [comment]
I will be closing this soon if a response is not given. Does this occur in the latest version?

**Comment by AViewFromTheTop** [comment]
Closing as no response was given.
