### ISSUE TITLE
Can't place off hand torches while holding axe (versions >= 2.1)

### ISSUE THREAD

**Issue by CatastropheBlack** [FrozenBlock/WilderWild#293]
**Description of the Bug Encountered**
Player cannot place torches (on non-log blocks) from off hand while holding an axe in main hand since mod v2.1. Mod version 2.0.6 and lower has expected torch placing behavior.

**Steps To Reproduce**
1. Install WilderWild v2.1 or above.
2. Hold an axe in main hand, hold torch in off hand.
3. Right click on a non-log block to place torch.
4. Axe tries to interact with block instead of placing torch.

**Expected Behavior**
Right clicking on a non-log block places a torch.

**Additional context**
Minecraft v1.20.1
Fabric Loader 0.14.22
fabric-api-0.87.0+1.20.1
WilderWild-2.1-Fabric+1.20.1.jar

**Comment by vico93** [comment]
I'm getting this annoying axe-tries-to-interact-with-everything as well.

**Comment by AViewFromTheTop** [comment]
Fixed in the next update!
