### ISSUE TITLE
Add option to prevent rolling tumbleweed to trample crops

### ISSUE THREAD

**Issue by vico93** [FrozenBlock/WilderWild#294]
Self-explanatory in the title. Even lowering the spawn rates of rolling tumbleweeds (that, btw, have a very wonky physics, but this is subject for a possible another suggestion), they still find a way to end up inside my field (that is surronded by fences, btw), trampling the crops.

A standalone option to make tumbleweeds to not mess with crops is desirable and would prevent me to try to switch `mobGriefing` to `false` and affect lots of other mechanics that i dont like to switch off.

**Comment by AViewFromTheTop** [comment]
done! will be included in the next update.
