### ISSUE TITLE
Config setting to disable log hollowing

### ISSUE THREAD

**Issue by donkeyrat** [FrozenBlock/WilderWild#302]
Disabling log hollowing would give modpack creators the option to avoid the problems of compatibility-less log hollowing. It would also be good for normal users who don't like the mechanic.

The alternative is to add mod-log compatibility. Both would be best, but I believe a config to disable log hollowing is simplest.

**Comment by AViewFromTheTop** [comment]
added in the next version

**Comment by Treetrain1** [comment]
> added in the next version

update: not next update but one after that
next update is a hotfix for chunk loading

**Comment by AViewFromTheTop** [comment]
> > added in the next version
> 
> update: not next update but one after that next update is a hotfix for chunk loading

bruh
