### ISSUE TITLE
0.5.3 sodium incompatibility

### ISSUE THREAD

**Issue by remiimber** [FrozenBlock/WilderWild#303]
**Description of the Bug Encountered**
for some reason I keep getting a incompatible mod set alert with sodium 0.5.3

**Screenshots**

**Logs**
Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
Replace mod 'Wilder Wild' (wilderwild) 2.1.3-Fabric+1.20.1 with any version that is compatible with:
sodium 0.4.10+build.27
Unmet dependency listing:
Mod 'Wilder Wild' (wilderwild) 2.1.3-Fabric+1.20.1 is incompatible with any version before 0.5.0 of mod 'Sodium', but matching versions are present: 0.5.3/0.4.10+build.27!

**Additional context**
I have a bunch of mods installed that all seem to be working fine so idk

**Comment by Treetrain1** [comment]
You are using sodium 0.4.10.

**Comment by Treetrain1** [comment]
Does this happen in 2.1.5?

**Comment by AViewFromTheTop** [comment]
I played on the latest version and it was perfectly fine with the newest sodium @Treetrain1
