### ISSUE TITLE
Hanging tendril crashed the server when it is placed beside soulfire and triggered by sculk sensors nearby.

### ISSUE THREAD

**Issue by gorbodoh** [FrozenBlock/WilderWild#305]
**Description of the Bug Encountered**
Hanging tendril crashed the server when it is placed beside soulfire and triggered by sculk sensors nearby.

**Steps To Reproduce**
1. Light a fire on soulsand.
2. Place a hanging tendril at the neighbouring block.
3. Place a sculk sensor nearby.
4. Move around to trigger the  sculk sensor and the hanging tendril.
5. Server crashed.

**Expected Behavior**
The server to not crashed.

**Screenshots**
No screenshots available.

**Logs**
[crash-2023-09-22_13.15.04-server.txt](https://github.com/FrozenBlock/WilderWild/files/12705632/crash-2023-09-22_13.15.04-server.txt)

**Additional context**
NA

**Comment by AViewFromTheTop** [comment]
wtf lmao???? @Treetrain1 ????

**Comment by AViewFromTheTop** [comment]
java.lang.IllegalArgumentException: Cannot get property class_2754{name=sculk_sensor_phase, clazz=class net.minecraft.class_5705, values=[inactive, active, cooldown]} as it does not exist in Block{minecraft:sculk_catalyst}

for some reason it's trying to get hanging tendril properties from a sculk catalyst which makes literally no sense
