### ISSUE TITLE
Crash while generating

### ISSUE THREAD

**Issue by Nicolol1234** [FrozenBlock/WilderWild#311]
**Description of the Bug Encountered**
While exploring with some mods, the game crashed

**Steps To Reproduce**
1. install wilder wilds
2. explore
3. see the crash

**Expected Behavior**
no crash

**Logs**
https://mclo.gs/mBC7kj3 (crash report)

**Additional context**
here are the normal logs: 
https://mclo.gs/a2BEPVM

**Comment by AViewFromTheTop** [comment]
Would you be able to test this without C2ME installed?

**Comment by Nicolol1234** [comment]
Ok i'll test it today

**Comment by Nicolol1234** [comment]
Do you plan to fix it? because i'd like to use your mod with c2me to have better performance

**Comment by ZiLenTz** [comment]
Got a similar error and also another one in difference circumstance which both prevented me from generating chunks.

There are some workarounds that required you to change some setting in Wilder Wild's config folder.
It fixed crashing issue but I'm not sure how they are gonna affect this mod as I haven't tested it yet.

at net.frozenblock.wilderwild.block.OsseousSculkBlock.worldGenSpread
- goto mixins.json5
- change "sculk" from true to false

at net.frozenblock.wilderwild.block.HangingTendrilBlock.method_9565
(In case that you also run into this.)
- goto block.jsons5
- change "tendrilsCarryEvents" from true to false

BTW, we can't just remove this mod in an existing world as it will create another error at least from my experience.
Also playing without C2ME is painful so I also share the same sentiment hahaha.

Hope this is not too late.
@Nicolol1234

**Comment by Nicolol1234** [comment]
It's never too late thx!

**Comment by AViewFromTheTop** [comment]
I'm hoping this will indeed be fixed in 2.2 per my changes.

**Comment by unoMato** [comment]
I also have similar issue with my modpack.

[log file](https://gist.githubusercontent.com/unoMato/cbf28c8792363f02398bbb353994a820/raw/863f11b61e3dfca61eaf55cca00f667ee3c8452a/gistfile1.txt) 
Server didn't crash but it froze and i had to close it manually.

Disabling parralel feature generation in c2me.toml config file fixed my crashes/freezes.
Under [threadedWorldGen] 
`allowThreadedFeatures = false`

Wordgen might be little slower but it's better than crashing.

**Comment by AViewFromTheTop** [comment]
Does this still occur in 2.2.1?
