### ISSUE TITLE
Server crash with luckperms

### ISSUE THREAD

**Issue by Nicolol1234** [FrozenBlock/WilderWild#314]
**Description of the Bug Encountered**
Crash on startup

**Steps To Reproduce**
1. install the latest 1.20.1 version on fabric
2. et voila.

**Expected Behavior**
Server should start

**Logs**
https://mclo.gs/kNYJ09b

**Comment by Treetrain1** [comment]
luckperms incompat

**Comment by AViewFromTheTop** [comment]
> luckperms incompat

….how did we manage to be incompatible with that of all mods lmfao

**Comment by Nicolol1234** [comment]
Idk, but your mod is causing a LOT of problems with the other mods, so i took it out

**Comment by AViewFromTheTop** [comment]
Does this occur in the latest version? I believe this should've been fixed.
