### ISSUE TITLE
[1.20.1 Forge] Crash with Roughly Enough Resources on world load (singleplayer)

### ISSUE THREAD

**Issue by TelepathicGrunt** [FrozenBlock/WilderWild#315]
This was reported to RER's issue report
https://github.com/shedaniel/RoughlyEnoughResources/issues/18

However, the issue appears more to be on Wilder Wild's side. 

A friend deduced that the crash being on Copy State means that minecraft deserialize the copy state loot table, found one of Wilder Wild's loot table's copy_state usage has an invalid blockstate so the blockstate map lookup returns null, causes the copy state's set of properties to have a null in it, then when RER serializes it to json to send to client, the CopyState function explodes due to the null in the set.

You'll have to review and breakpoint and make sure all of your copy_state usages are correct and not putting null into the set anymore.
https://github.com/search?q=repo%3AFrozenBlock%2FWilderWild%20copy_state&type=code

**Comment by AViewFromTheTop** [comment]
@Treetrain1 i think it’s the display lantern that one always gives an error in logs

**Comment by fleetag** [comment]
How did you get Wilder Wild to work on Forge 1.20.1?
