### ISSUE TITLE
Firefly flickering is weird

### ISSUE THREAD

**Issue by Treetrain1** [FrozenBlock/WilderWild#316]
this has been bothering me for eternity but ive just never mentioned it

**Comment by Treetrain1** [comment]
unless its intentional but it bothers me idk

**Comment by Treetrain1** [comment]
looks like it is intentional
but why

**Comment by Treetrain1** [comment]
im talking about this

https://github.com/FrozenBlock/WilderWild/assets/39657565/12560eba-2fc7-44dc-86c2-a42fd5bc38d4

**Comment by AViewFromTheTop** [comment]
> this has been bothering me for eternity but ive just never mentioned it

It’s because I initially made a mistake when first implementing their flickering- it’s caused by an overflow of the int so it does that, but then regresses because it’s either a sin or cos wave
I need to find a function with lots of vertical asymptotes if I want to “fix” it

**Comment by AViewFromTheTop** [comment]
I forgot what they were called lol
Maybe rational functions idfk
