### ISSUE TITLE
Mod doesn't work on Quilt modloader because of 0.90.4 version requirement while quilt api is 0.90.0

### ISSUE THREAD

**Issue by Hydrazina** [FrozenBlock/WilderWild#317]
**Description of the Bug Encountered**
As in the title

**Steps To Reproduce**
1. Run the mod in the quilt modloader
2. doesnt work
3. help

**Expected Behavior**
1.Mod working

**Screenshots**
![image](https://github.com/FrozenBlock/WilderWild/assets/75476523/a5a878ec-aac4-4a3c-9b61-3e138dcefc91)

**Comment by Treetrain1** [comment]
we require 0.90.4 as it is critical for our blocks to function properly
please report this to quilt
