### ISSUE TITLE
Mod Compatibility - Create Fabric - "Filter's"

### ISSUE THREAD

**Issue by Tyler-Moore** [FrozenBlock/WilderWild#318]
**Description of the Bug Encountered**
Create Mod's "Item Filter" and "Attribute Filter" GUI interface closing the moment it's interacted with. 

**Steps To Reproduce**
1. Run Fabric 1.20.1 with WilderWild Versions 2.1.7 to 2.1.13 along with "Create Fabric" 0.5.1-d-build.1161+mc1.20.1 (v0.5.1.d) and Fabric API 90.7 (tested with 90.4 as well)
2. Create World - Creative or Survival (Creative for ease)
3. Add Fabrics "Item Filter" and/or "Attribute Filter" to hotbar
4. Right-click/Use item

**Expected Behavior**
Loads GUI Interface, and stays till user closes

**Screenshots**
2.1.11
![Untitled video - Made with Clipchamp](https://github.com/FrozenBlock/WilderWild/assets/90428716/ac1024a3-fcb2-4eb4-9e82-08104f5dc825)
2.1.6
![Wilderwild 2 1 6](https://github.com/FrozenBlock/WilderWild/assets/90428716/46aa76b7-74af-4570-b0f2-35860fb1471a)

**Logs**
2.1.13
[2.1.13 latest.log](https://github.com/FrozenBlock/WilderWild/files/13352003/2.1.13.latest.log)

2.1.6
[2.1.6 latest.log](https://github.com/FrozenBlock/WilderWild/files/13352001/2.1.6.latest.log)

**Additional context**
Stopped working with WilderWild Versions 2.1.7-2.1.13 installed.
Version 2.1.6 produced expected results.
GUI pop's up but quickly disappears

Update:
    I found a "workaround." I was able to get the filters to produce the desired results, but the Schematics are required. When you load a Filter that's been assigned through a schematic, you can then right click to open the GUI and edit them to your use.

**Comment by AViewFromTheTop** [comment]
The screenshot you posted doesn’t link properly.
Would you be able to post the logs?

**Comment by MykolaHamster** [comment]
![filter](https://github.com/FrozenBlock/WilderWild/assets/124202878/0a35c4c6-1d21-4724-9eba-44b483945a27)
[latest.log](https://github.com/FrozenBlock/WilderWild/files/13347856/latest.log)

Same issue on a fresh instance with only Create and WilderWild

**Comment by AViewFromTheTop** [comment]
luckily this has recently just been fixed
