### ISSUE TITLE
Make the stone chest interact with comparators

### ISSUE THREAD

**Issue by lumiscosity** [FrozenBlock/WilderWild#319]
**Explain your suggestion here.**
It would be nice if stone chests could output a signal through comparators based on how much of the lid is open.

**Describe alternatives you've considered**
Not exactly a complete replacement, just a related feature - maybe a trapped stone chest that outputs a signal once the player opens the chest's inventory?

**Additional context**

![image](https://github.com/FrozenBlock/WilderWild/assets/26834471/926dc9b1-df64-4ca9-8d45-cfca0e8b5846)

**Comment by AViewFromTheTop** [comment]
just added!
