### ISSUE TITLE
Switching between copper horns while playing makes the sound stack

### ISSUE THREAD

**Issue by lumiscosity** [FrozenBlock/WilderWild#320]
**Description of the Bug Encountered**

**Steps To Reproduce**
1. Hold multiple copper horns in your hotbar
2. Hold the item use button
3. Switch between the horns
4. The sound of the previous horn(s) will not stop until you let go of the use key or switch to a non-copper horn slot

**Expected Behavior**
Only the sound of the currently held horn plays.

**Screenshots**
https://github-production-user-asset-6210df.s3.amazonaws.com/26834471/285680299-caae8e51-e02c-4689-8d21-3d5172ae1f13.mp4

**Additional context**
Honestly, if not for the jerky item switch animation I'd believe this is an intentional feature (playing chords is pretty fun)! Maybe just make it toggleable and cap it at some sound event count?

**Comment by Treetrain1** [comment]
@AViewFromTheTop is this intentional?

**Comment by AViewFromTheTop** [comment]
As stated in dev chat no

**Comment by LThreeZeroT** [comment]
I kinda like this feature though :(

**Comment by Treetrain1** [comment]
> I kinda like this "bug" though :(

its not intended
