### ISSUE TITLE
Add a way to change biome generation weight

### ISSUE THREAD

**Issue by lumiscosity** [FrozenBlock/WilderWild#321]
**Explain your suggestion here.**
In a setting with many modded biomes, it would be nice to be able to force the WW biomes to generate less commonly. [Promenade](https://github.com/DawnTeamMC/Promenade) implements a biome weight option in its config that could be used for refference. 

**Describe alternatives you've considered**
A full config for every biome placement value would probably be a bit overkill?

**Additional context**
None.

**Comment by AViewFromTheTop** [comment]
Promenade uses a separate biome injection api while we pretty much use vanilla methods of doing so
i dont see how this would be realistically possible
