### ISSUE TITLE
[Crash] CalibratedSculkSensorBlock 

### ISSUE THREAD

**Issue by Zunwolf1896** [FrozenBlock/WilderWild#322]
Unsure, I was at work when teh crash happened and can't get in contact with all the players.

**Steps To Reproduce**
1. ??
2. ??
3. 
4. 

Server not crashing

**Screenshots**

[**Logs**](https://mclo.gs/WxOcXmI)

**Additional context**

**Comment by AViewFromTheTop** [comment]
Does this still occur in 2.2.1?
