### ISSUE TITLE
[Crash] Undefined crash (1.19.2)

### ISSUE THREAD

**Issue by 4zy1** [FrozenBlock/WilderWild#323]
The game crashes when loading this mod, I made a new installation with only this mod installed and it still crashes.
Fabric version is 0.15.1
Game version is 1.19.2
Log can be found [here](https://mclo.gs/PVlyrnP)

**Comment by Treetrain1** [comment]
unfortunately we do not provide updates for this mod on 1.19.2.
in order to get the latest versions you must use the latest versions of minecraft.
