### ISSUE TITLE
Netty Epoll Server IO [STDERR]

### ISSUE THREAD

**Issue by unoMato** [FrozenBlock/WilderWild#326]
**Description of the Bug Encountered**
Every time server starts there is netty errors. When Wilder Wild mod is disabled errors are gone.

Also when world is created first time there is more errors.

**Steps To Reproduce**
1. Make fabric 1.20.1 server with Fabric Loader 15.1
2. add Fabric API, Cloth Config and Wilder Wild mods to mods folder
3. Start server
4. Watch terminal or log for errors

**Expected Behavior**
No errors

**Logs**
[Generating world first time](https://gist.githubusercontent.com/unoMato/6cf2e81e3aa60c5f8c81f5682975da69/raw/b565e4c813b41eb3cd9d10751ed89b7a05623ca6/Launch%2520server%2520first%2520time)
[Second time](https://gist.githubusercontent.com/unoMato/6cf2e81e3aa60c5f8c81f5682975da69/raw/b565e4c813b41eb3cd9d10751ed89b7a05623ca6/Launch%2520server%2520second%2520time)

**Additional context**
Mod and server seems to work fine othewise

**Comment by AViewFromTheEnd** [comment]
What version of Fabric API are you using? Would you be able to test with a version below 0.91.0?

**Comment by AViewFromTheTop** [comment]
If this is the cause of the error, I’ll have to fix it for 2.2 whenever I get the chance.
Reported to Fabric and they denied a change to it, but at least they told me how exactly to go about fixing it. https://github.com/FabricMC/fabric/issues/3464#issuecomment-1853392086

**Comment by unoMato** [comment]
After further investigation I found out that by changing server port I got rid of those error messages. It seems that some ports give error and some don't. Example server ports 25564-25566 give error and those ports should be free of any other services. Server ports 25561-25563 work fine.

Weird thing is that I'm having hard time reproducing that error my other systems. There might be something on my server system what causes some ports to throw an error with this mod.

And for some reason port what I used first works now without errors.

I have no idea what could cause this or if issue itself is in this mod. Sorry for inconvenience.

**Comment by unoMato** [comment]
I Think i finaly got it.

My servers are running from CraftyController and if in servers config tab server port is set to be same as server running with WilderWild mod it generates that netty error.
![image](https://github.com/FrozenBlock/WilderWild/assets/151737416/ac818efd-4525-452a-ac92-c64b6571af7f)

So I guess when Crafty connects to server in guestion for stats that causes those netty messages at startup.

If i change port to be same in server.properties and Crafty control panel config tab I alway got those error messages. When I Change server port to something that crafty isn't listening for stats there are no errors.

If someone could confirm that this is Crafty related it would be great! It would also explain why I didn't get those erros in other systems since they don't have Crafty running.

**Comment by unoMato** [comment]
Me again, I was close last time but it's just related to ping request send during server startup. 

I Was in contact with Crafty support and learned that Crafty send many stats request on server startup and when server is running. That's why it generates those messages at every startup.

Netty error messages can be reproduced easily just by using Minecrafts ingame server browser.

1. Add your server with WilderWild mod to your server list
2. Start server
3. - Rapidly click refresh in server list until server up
   -  Alternatively you can wait until you see these messages in terminal and press refresh once or twice.
    >     [Server thread/INFO]: Preparing level "world"
    >     [Server thread/INFO]: Wilder Wild's Overworld Surface Rules have been added!
    >     [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
4. Netty error messages should appear in terminal/log

After server is fully loaded refreshing don't generate netty error messages anymore.

**Comment by AViewFromTheTop** [comment]
Pretty sure this was a vanilla issue iirc
