### ISSUE TITLE
Items called Air... Coconut called Air

### ISSUE THREAD

**Issue by makumaku1974** [FrozenBlock/WilderWild#328]
**Description of the Bug Encountered**

**Steps To Reproduce**

no need to reproduce

**Expected Behavior**

Items and Food called Air

**Screenshots**

![2023-12-17_11 43 25](https://github.com/FrozenBlock/WilderWild/assets/129804277/21874b66-25ab-403d-be94-1608185332f9)

**Logs**

**Additional context**

**Comment by Treetrain1** [comment]
i dont understand
can you explain

**Comment by AViewFromTheTop** [comment]
> i dont understand can you explain

Its that issue we had in development when something is registered out of order somehow (or isn’t even registered)

**Comment by Treetrain1** [comment]
> > i dont understand can you explain
> 
> Its that issue we had in development when something is registered out of order somehow (or isn’t even registered)

i have a feeling its more to do with that display mod, i dont know which one it is
but using EMI is totally functional

**Comment by Treetrain1** [comment]
without any form of context, we cannot help with this issue

**Comment by AViewFromTheTop** [comment]
Dang tree I guess you really don’t like invisible coconuts in the air
