### ISSUE TITLE
Server crash when touching jellyfish [Fabric 1.20.1]

### ISSUE THREAD

**Issue by waddon1** [FrozenBlock/WilderWild#329]
**Description of the Bug Encountered**

**Steps To Reproduce**
1. Join server
2. Go into shipwreck
3. Touch Jellyfish
4. Crash

**Expected Behavior**
Not crash

**Screenshots**

**Logs**
[crash-2023-12-18_11.39.04-server.txt](https://github.com/FrozenBlock/WilderWild/files/13705871/crash-2023-12-18_11.39.04-server.txt)

**Additional context**

**Comment by Majurad** [comment]
I just ran into this problem on my server as well. 

[crash-2024-01-05_22.21.38-server.txt](https://github.com/FrozenBlock/WilderWild/files/13848228/crash-2024-01-05_22.21.38-server.txt)

**Comment by AViewFromTheTop** [comment]
I was unable to reproduce this on 1.20.1 with just FrozenLib, WilderWild, and Fabric API.
@Treetrain1 by any chance, do you see anything concerning in the logs?
If anything, I'm certain this is a mod compat issue that we have no control over.

**Comment by Treetrain1** [comment]
for those who experience this crash, please try to reproduce it with the mod StackDeobfuscator
that mod makes issue reports much easier to work with

**Comment by AViewFromTheTop** [comment]
> for those who experience this crash, please try to reproduce it with the mod StackDeobfuscator that mod makes issue reports much easier to work with

Ditto that.

**Comment by Abbie5** [comment]
reproduced this in a dev environment on the 1.20.1 branch
[crash-2024-01-19_20.54.33-server.txt](https://github.com/FrozenBlock/WilderWild/files/13994423/crash-2024-01-19_20.54.33-server.txt)

**Comment by AViewFromTheTop** [comment]
> reproduced this in a dev environment on the 1.20.1 branch [crash-2024-01-19_20.54.33-server.txt](https://github.com/FrozenBlock/WilderWild/files/13994423/crash-2024-01-19_20.54.33-server.txt)

Interesting- this is by far the best reported log I've seen!
Thank you!

**Comment by AViewFromTheTop** [comment]
In the current class, there's no possible way for a Jellyfish to ever access a LocalPlayer. Let's wait and see if this occurs in 2.3 once it releases.

**Comment by Abbie5** [comment]
it's not only possible, it happened, and the crash log i provided proves it...

doesn't mean in know why it happened though...

**Comment by AViewFromTheTop** [comment]
> it's not only possible, it happened, and the crash log i provided proves it...
> 
> doesn't mean i know why it happened though...

2.3 includes a server check in the sting method, and I also haven't encountered the issue there. I just want to see if that happens to fix it once it releases or not.

**Comment by Abbie5** [comment]
ok, i also asked in the quilt discord and got this explanation:
![image](https://github.com/FrozenBlock/WilderWild/assets/43531981/a22434c1-a57f-4d8d-8fa3-20bba7330097)
https://discord.com/channels/817576132726620200/832355328623902741/1198013844916805677

**Comment by AViewFromTheEnd** [comment]
> ok, i also asked in the quilt discord and got this explanation: ![image](https://private-user-images.githubusercontent.com/43531981/298204025-a22434c1-a57f-4d8d-8fa3-20bba7330097.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MDA5MjMsIm5iZiI6MTcwNTcwMDYyMywicGF0aCI6Ii80MzUzMTk4MS8yOTgyMDQwMjUtYTIyNDM0YzEtYTU3Zi00ZDhkLThmYTMtMjBiYmE3MzMwMDk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDIxNDM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyZDg0YmNmZjJhMzc3YzZjYTEwZDRkZGNkN2Y4M2RkMDMwNDNhNjkwODFjMDYxODY5MGUwMzk2M2M1MmNjOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tIhFminfNI10eDdSwT1qRct5M1NGDTCrSYBrXmzgMAg) https://discord.com/channels/817576132726620200/832355328623902741/1198013844916805677

As much as I’d like to say that’s true- I’ve played 2.3 on a server for hours straight and haven’t encountered this issue with any packets.

**Comment by Treetrain1** [comment]
unrelated but the sting packet can probably have `Wilder` removed from the name

**Comment by AViewFromTheEnd** [comment]
> unrelated but the sting packet can probably have `Wilder` removed from the name

Nuh uh that’s contradictory tree

**Comment by AViewFromTheEnd** [comment]
Wtf why is my alt on the in-app browser instead of my main

**Comment by Abbie5** [comment]
do you have a build of 2.3 i can test this on? i can reliably reproduce this issue on 2.2.3

**Comment by Abbie5** [comment]
reproduced on latest commit on `ostrich` branch (2.3)
[crash-2024-01-19_22.27.13-server.txt](https://github.com/FrozenBlock/WilderWild/files/13995119/crash-2024-01-19_22.27.13-server.txt)

**Comment by AViewFromTheTop** [comment]
> reproduced on latest commit on `ostrich` branch (2.3), taken from github actions (https://github.com/FrozenBlock/WilderWild/actions/runs/7589112401) [crash-2024-01-19_22.27.13-server.txt](https://github.com/FrozenBlock/WilderWild/files/13995119/crash-2024-01-19_22.27.13-server.txt)

Would you be able to test on the latest `ostrich` branch commit?

**Comment by Abbie5** [comment]
tested on 0a00fcb (https://github.com/FrozenBlock/WilderWild/actions/runs/7591484341), no crash

**Comment by AViewFromTheTop** [comment]
Poggg
