### ISSUE TITLE
Client disconnects from server after picking up blaze rod

### ISSUE THREAD

**Issue by nickademas** [FrozenBlock/WilderWild#330]
**Description of the Bug Encountered**
after picking up the blaze rod the game disconnects from the server with the error "io.netty.handler.codec.DecoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_175.comp_1924()" because "criterion" is null", in the console server only shows that the player has been disconnected, after trying to pick up blaze rod once, each time joining this server results in immediate kick
**Steps To Reproduce**
1.  Host a server with this mod
2.  Join it from client with this mod
3. Pick up a blaze rod

**Logs**
[latest.log](https://github.com/FrozenBlock/WilderWild/files/13721248/latest.log)

**Comment by AViewFromTheEnd** [comment]
Can you turn the “Modify Advancements” toggle in the config off, restart the server, and try again?

**Comment by nickademas** [comment]
Disabling this option on the client fixed it
I also started a vanilla server and joined it with client with Wilder Wild with default config (idk how did it even work and the world looked pretty cursed) and after picking up blaze rod the same thing occured so the so the mod does not have to be on the server for the error to occur.

**Comment by AViewFromTheEnd** [comment]
Yeah…. An additional BlockState is added to some blocks which causes that funny issue with Vanilla worlds.. my apologies. As for the achievement thing, @Treetrain1, whenever you have the time, would you be able to look into this? We don’t modify the Blaze Rod advancement at all, so I don’t know what would be causing this. Has to be a mod conflict I think.

**Comment by nickademas** [comment]
Mod conflict? I had only wilder wild + fabric api both on server and on client so i don't think it's a mod conflict.

**Comment by AT14C** [comment]
Had the same problem and applied the same fix, now I'm getting the same error even tho I haven't picked up any blaze rods, I have no idea what the source of the problem is

**Comment by AViewFromTheTop** [comment]
@Treetrain1

**Comment by AViewFromTheTop** [comment]
I can't reproduce this. Is there any additional context behind this?

**Comment by Icky50** [comment]
The error appears in a lot of situations. There are many vanilla achievements and achievements from other datapacks and mods that caused that issue for us.
Turning off “Modify Advancements” on the server and on the client fixed it. Thanks.
I tested it on a fabric server with the mod installed on the client AND on the server. (1.20.2 mod version 2.2.1 AND 2.2.3)

**Comment by AViewFromTheTop** [comment]
Does this still occur in 2.3?

**Comment by nickademas** [comment]
Fixed in 2.3. Thanks.
