### ISSUE TITLE
Fabric Seasons Extras crash on world load - Minecraft 1.19.2

### ISSUE THREAD

**Issue by thatFishStick** [FrozenBlock/WilderWild#331]
**Description of the Bug Encountered**
Game crashes when attempting to load a world with Wilder Wild and Fabric Seasons Extras

**Steps To Reproduce**
1. Install Wilder Wild, Fabric Seasons, and Fabric Seasons Extras
2. Load or generate a world

**Logs**
[latest.log](https://github.com/FrozenBlock/WilderWild/files/13824099/latest.log)
[crash-2024-01-03_14.31.49-server.txt](https://github.com/FrozenBlock/WilderWild/files/13824101/crash-2024-01-03_14.31.49-server.txt)

**Additional context**
Crash only occurs with the Extras mod, Fabric Seasons by itself doesn't crash with Wilder Wild

**Comment by Treetrain1** [comment]
It's an out of memory error, but the game still has ~7G left before it runs out.
Is the host machine running out of memory?

**Comment by thatFishStick** [comment]
I have 32GB installed. Looking at windows task manager, it says there's still 12.8GB available to the system when the game crashes. I just tried increasing minecraft's mem allocation from 8GB to 16GB, which only seemed to give the game a few more seconds before crashing

**Comment by thatFishStick** [comment]
it seems the crash log isn't correctly reporting memory usage at the time of the crash, mem usage ramps up quickly while loading the world until reaching the max allocated to the game

**Comment by Treetrain1** [comment]
thats very odd
i wonder if fabric seasons extras is rapidly filling up a map, causing a memory leak

**Comment by Treetrain1** [comment]
what's even more odd is its using a fake world for Patchouli but you don't have Patchouli installed.

**Comment by Sunconure11** [comment]
I'm having this issue despite allocating literal 16 gigs of RAM, and having 128 gigs on my machine.
