### ISSUE TITLE
no fps for me ig 😔 

### ISSUE THREAD

**Issue by Lumenyl-Cal** [FrozenBlock/WilderWild#334]
**Description of the Bug Encountered**
   fps

**Steps To Reproduce**
1. install the mod
2. play minecraft
3. play minecraft
4. playminecraft

**Expected Behavior**
   fps

**Screenshots**
   install and use the mod

**Logs**
  use the mod

**Additional context**
550 fps at 64RD to 450 fps optimise your fucking mod stupido
4060 ti 16gb

**Comment by BioTechproject27** [comment]
I mean, c'mon, ya gotta give more info than that, this is literally useless as it is.
What operating system? Which loader? Which mod version? Any other mods?
It works perfectly fine on my system (windows 10 64bit, Fabric 0.15.3, 1.20.1, mod version 2.2.3)
Istg some primates...💀

**Comment by AViewFromTheTop** [comment]
You can do it for us!
Or perhaps submit a bug report that isn’t a flat out lie.
Or you can try turning off the Pollen Particles config option if your PC can’t handle a couple extra pixels ;)
