### ISSUE TITLE
Exception generating new chunk

### ISSUE THREAD

**Issue by angelpuppy** [FrozenBlock/WilderWild#335]
the game will crash when rendering specifically the old growth birch taiga

**Steps To Reproduce**
1. join world near / in old growth birch taiga
2. crash
3. 
4. 

**Expected Behavior**
not crash

**Screenshots**

**Logs**
[crash-2024-01-22_23.49.35-server.txt](https://github.com/FrozenBlock/WilderWild/files/14020080/crash-2024-01-22_23.49.35-server.txt)

**Comment by angelpuppy** [comment]
i believe the mod causing teh crash is [rusticated](https://www.curseforge.com/minecraft/mc-mods/rusticated) , as after i removed it it stopped crashing ! will be reporting it to them aswell

**Comment by AViewFromTheTop** [comment]
Closing as no response has been given,
