### ISSUE TITLE
Unable to start server with only this mod

### ISSUE THREAD

**Issue by sevderg** [FrozenBlock/WilderWild#336]
**Description of the Bug Encountered**
I am unable to start a server using nothing but this mod and the Fabric api as it is required

**Steps To Reproduce**
1. Fresh install of Fabric server, MC 1.20 loader version 0.15.6
2. Add the Wilder Wild mod (version 2.0.4) and Fabric api (I tried multiple versions including the latest 1.20 one along with 0.86.1 which is shown as the dependency for that version of Wilder Wild) to mods folder
3. Run server
4. Error occurs

**Expected Behavior**
Server starts as normal

**Screenshots**
None

**Logs**
[latest.log](https://github.com/FrozenBlock/WilderWild/files/14071676/latest.log)

**Additional context**
I apologize if I'm being dumb and there is some simple fix, I feel like it can't be that complicated when I have literally no other mods installed. Let me know if you need any more info. Thanks for the help.

**Comment by AViewFromTheTop** [comment]
We do not support 1.20 anymore, only 1.20.1+.
the issue is that we include MixinExtras which got added in Fabric Loader 0.15+.
You can use 7Zip to try to remove MixinExtras from Wilder Wild/FrozenLib and that’ll fix it.

**Comment by sevderg** [comment]
What exactly would I need to remove using 7Zip? I tried just removing the mixinextras folder but that led to another error.
[latest.log](https://github.com/FrozenBlock/WilderWild/files/14074251/latest.log)
