### ISSUE TITLE
Shulkers do not shoot projectiles as they should

### ISSUE THREAD

**Issue by Icky50** [FrozenBlock/WilderWild#338]
**Description of the Bug Encountered**
Shulker projectiles do not get fired properly. Hey appear and then disappear again in the shulker shell as if the shulker is hitting itself
but it does not hit itself because it does not duplicate the shulker

**Steps To Reproduce**
1. Install the mod
2. Spawn a shulker
3. Switch to survival mode or give the shulker any other target
4. Watch the sulker not shooting
Tested with:
Minecraft version: 1.20.2
Fabric Loader version: 0.15.3
Fabric API version: 0.91.6+1.20.2
Wilder Wild version: 2.2.3-Fabric+1.20.2
I tested it in a normal world and also on a server. The problem appears in both cases.

**Expected Behavior**
The shulker should shoot and its projectile should leave the shell and fly away

**Screenshots**
![2024-01-28_21 59 49](https://github.com/FrozenBlock/WilderWild/assets/101670446/4066718a-8eb8-4b99-910b-c2c4017affd3)

**Logs**
There are no errors in the log. Neither on the client nor on the server

**Additional context**
This also breaks shulkerfarms
It would be great if you can fix this issue for the version 1.20.2

**Comment by AViewFromTheTop** [comment]
@Treetrain1

**Comment by AViewFromTheTop** [comment]
@Treetrain1 important flib thing to fix before we release ww 2.3.1

**Comment by AViewFromTheTop** [comment]
This has been fixed, stay tuned for the next release!

**Comment by Icky50** [comment]
Thank you, that sounds very promising. Still, I tried to run the newest versions by using the gradle task 'run client' in multiple branches (main, 1.20.2 and 1.20.1) that were updated in the last couple of days and none of them seem to fix the bug. I know the next release you talked about is not officially out yes but I just wantet to mention that.

**Comment by Icky50** [comment]
The bug is fixed in the dev branch now. Thank you soo much. I'm excited for the next release!

**Comment by AViewFromTheTop** [comment]
> The bug is fixed in the dev branch now. Thank you soo much. I'm excited for the next release!

@Treetrain1 please release
