### ISSUE TITLE
Some item names are overriden as "Air"

### ISSUE THREAD

**Issue by StunfMC** [FrozenBlock/WilderWild#339]
**Description of the Bug Encountered**

As shown in #328, some items will be called Air instead of their actual name. This happens without any sort of mods that would modify this, even when just using Wilder Wild.

**Steps To Reproduce**

No need to reproduce.

**Expected Behavior**

Items are called their actual names.

**Comment by AViewFromTheTop** [comment]
Are you using Quilt?
If so, we highly recommend switching back to Fabric. Quilt causes lots of random issues like that.

**Comment by StunfMC** [comment]
I apologize for the late response, but I am using Fabric on the latest version of Wilder Wild and Fabric API/Loader.

**Comment by AViewFromTheTop** [comment]
> I apologize for the late response, but I am using Fabric on the latest version of Wilder Wild and Fabric API/Loader.

@Treetrain1

**Comment by StunfMC** [comment]
This issue seems to be resolved on the latest version.

**Comment by JuceInUse** [comment]
Currently experiencing the same issue on Fabric v1.20.1 with Wilder Wild v2.4.2

**Comment by StunfMC** [comment]
Dare I speak. This issue does still persist, I apologize.

**Comment by StunfMC** [comment]
I believe that this issue has been fixed.
