### ISSUE TITLE
Wilder Wild removes goat horn cooldown

### ISSUE THREAD

**Issue by StunfMC** [FrozenBlock/WilderWild#340]
**Description of the Bug Encountered**

Wilder Wild removes all horn cooldowns, vanilla and ones added by Wilder Wild **except Ancient Horn** regardless of gamemode.

**Expected Behavior**

Goat and copper horns have cooldowns like Vanilla

**Comment by AViewFromTheTop** [comment]
This is entirely intentional.
You can turn the "Restrict Instrument Sound" config off if you don't like this.
The goal is to make horns play sounds only while held, while the Ancient Horn plays the full sound (hence the projectile and cooldown.)
