### ISSUE TITLE
Ancient Vault

### ISSUE THREAD

**Issue by AViewFromTheTop** [FrozenBlock/WilderWild#341]
-Would be a “scarier” looking alternative of the regular vault
-Located in the center of Ancient Cities, replacing the Stone Chests inside
-Will cause a lot of Vibrations

As we do not know how Mojang will go about the unlocking of other vaults, I would rather hold off to see if this is a worthy addition or not.
-Key could be found in random Stone Chests
-Key could be crafted with Trial Keys and Echo Shards

**Comment by Treetrain1** [comment]
if its just more scary looking then theres no point

**Comment by Treetrain1** [comment]
also isnt the center area supposed to be a secret?

**Comment by Treetrain1** [comment]
if a key is added, the player needs to know where to actually use it
the ideal progression is find the locked vault, search for a key, come back to the vault and loot it

**Comment by AViewFromTheTop** [comment]
closing for now
