### ISSUE TITLE
Palm rename

### ISSUE THREAD

**Issue by benio1394** [FrozenBlock/WilderWild#344]
**Explain your suggestion here.**
I'd like to suggest renaming palm as woodset and sappling to coconut palm. It's small and cosmetic feature, but it would give a little bit better experience with other biomes mods, because most of them have own palms, but without coconuts. This could provide better knowledge of what palm do we have and remove silly situation when you have two diffrent palm logs, but you can't stack them.

**Comment by AViewFromTheTop** [comment]
If you’d like, you can always make a resource pack with this change.
