### ISSUE TITLE
Game crash when joining server

### ISSUE THREAD

**Issue by Zman398** [FrozenBlock/WilderWild#347]
**Description of the Bug Encountered**
After updating server and client files to latest versions, user's game immediately crashes.

**Steps To Reproduce**
1. Update server and client side to most recent versions for mods FrozenLib, WilderWild, and Sodium
2. Restart server to apply updates
3. After restarting, find server and join. The game will look like it will initialize, but then crash 

**Expected Behavior**

**Screenshots**
![image_2024-02-10_201548720](https://github.com/FrozenBlock/WilderWild/assets/39968553/bde15e8e-176b-41c0-82e6-dfe79bd3f605)

**Logs**
[crash-2024-02-10_20.04.54-client.txt](https://github.com/FrozenBlock/WilderWild/files/14230970/crash-2024-02-10_20.04.54-client.txt)

Below is the crash error in the Minecraft Launcher:

The game crashed whilst ticking particle
Error: java.lang.NoSuchMethodError: 'net.minecraft.class_243 net.frozenblock.lib.wind.api.ClientWindManager.getWindMovement(net.minecraft.class_4538, net.minecraft.class_2338, double)'

**Additional context**

**Comment by Treetrain1** [comment]
use frozenlib 1.6, wilder wild hasnt updated for 1.6.1 yet

**Comment by AViewFromTheTop** [comment]
Hey!
If you're using FrozenLib 1.6.1, downgrade to 1.6.

**Comment by AViewFromTheTop** [comment]
oh
we both got it at the same time LMAO

**Comment by Zman398** [comment]
will there be any conflicts since the server is running on 1.20.4?
