### ISSUE TITLE
Fungus Crash

### ISSUE THREAD

**Issue by BalancedOneshot** [FrozenBlock/WilderWild#349]
**Right clicking a fungus of any type instantly crashes the client**

**Steps To Reproduce**
1. Load a new world
2. Find a fungus on a tree
3. Right click the fungus
4. Crash

**Expected Behavior**
Not crash lol

**Logs**
https://mclo.gs/jznCriE

**Additional context**
First discovered while using a decent sized modpack (100 mods or so) on a server. Created a new instance using just Fabric API and the newest Wilder Wild release and tried it on a singleplayer world. Crash still happens.

**Comment by AViewFromTheEnd** [comment]
This is fixed in the next version. We just have to wait for it to release, which will be soon.

**Comment by AViewFromTheTop** [comment]
And there I am on my alt again.
This account can close it lol
