### ISSUE TITLE
Shelf Fungus Crashes The Game

### ISSUE THREAD

**Issue by karetArts** [FrozenBlock/WilderWild#350]
Right clicking Shelf Fungus in any manner closes the game and no crash report is sent to the launcher

I was playing **Minecraft 1.20.1** on **Fabric Loader 0.15.3** and the mods I had installed were **Wilder Wild 2.3** and **Fabric Api 0.91.0**

I downloaded Wilder Wild on Modrinth, changing the version of Sodium is undesirable as another mod requires it to be 0.5.3

the game closes and does not leave a crash report on the launcher the moment you right click the fungus

The crash log:
[latest.log](https://github.com/FrozenBlock/WilderWild/files/14274324/latest.log)

**Comment by AViewFromTheTop** [comment]
Fixed in the next release.
