### ISSUE TITLE
Shulker bullets always firing directly downwards for some reason. (Wilder Wild)

### ISSUE THREAD

**Issue by BobTheBobTheBobTheBob** [FrozenBlock/WilderWild#351]
**Description of the Bug Encountered**
When in The End, with Wilder Wild 2.3 and no other mods installed, (except fabric API) Shulkers can only fire bullets directly down. This negatively effects the survival experience. They often teleport when they shoot the ground because they hit themselves. 

**Steps To Reproduce**
1. Wilder Wild 2.3-fabric+1.20.1
2. Fabric API 0.92.0+1.20.1
3. Fabric launcher 0.15.6
4. Enter The End
5. Get a Shulker to try and shoot you

**Expected Behavior**
Shulker bullet should track player, but instead shoots directly down and hits the ground, and perhaps causes skulker to teleport away. 

**Screenshots**
Bit of a messy screenshot, but it does the job. Shulker is targeting me, but the bullet is heading directly down. 
![2024-02-14_17 31 48_2](https://github.com/FrozenBlock/WilderWild/assets/159981004/9da7306a-d39a-4c77-980b-96afab3b6123)

**Logs**
I have not uploaded the log, as the game did not crash. I hope I understood the guidelines correctly, I read them twice. 

**Additional context**
-I also encounter this problem testing on1.20.4 but I play 1.20.1

-I use JDK 17. If that matters, sorry I'm not very technical, I use JDK instead of JRE for school. 

-I have tested in vanilla, with only this mod, and with other mods, and have figured out this mod is the mod causing the issue.  Weird as it doesn't focus on the end. 

-I play using an offline account on Prism Launcher (Win10), I don't see how that would matter, but hey.

**Comment by AViewFromTheTop** [comment]
We are aware of this issue and it's been fixed for the next release.
It should be releasing (hopefully) tomorrow.

**Comment by BobTheBobTheBobTheBob** [comment]
> We are aware of this issue and it's been fixed for the next release. It should be releasing (hopefully) tomorrow.

Maybe I should have looked a little harder for the issue. Cheers.
