### ISSUE TITLE
Warden doesen't spawn with mod installed

### ISSUE THREAD

**Issue by PolyframeX** [FrozenBlock/WilderWild#352]
**Description of the Bug Encountered**
With the mod installed, the warden does not spawn at all. Even with commands. I am using fabric 0.15.7 and WilderWild 2.3.1-mc1.20.1

**Steps To Reproduce**
1. Open a world
2. Attempt to spawn the warden in
3. See bug

**Expected Behavior**
The warden should be able to spawn with no issue

**Logs**
https://pastebin.com/XXzdu4Kh

**Additional context**
I have tested the mod independently and have received the error, so it is not a mod incompatibility.

**Comment by AViewFromTheTop** [comment]
@Treetrain1 the sonic boom stuff should be reverted below 1.20.5

**Comment by Treetrain1** [comment]
fixed
