### ISSUE TITLE
Ancient Horn Crashes Game Upon Killing A Player

### ISSUE THREAD

**Issue by PolyframeX** [FrozenBlock/WilderWild#353]
**Description of the Bug Encountered**
When using the ancient horn, the game will crash occasionally if a player is killed

**Steps To Reproduce**
1. Load up a world
2. Spawn in an ancient horn
3. Kill a player

**Expected Behavior**
Game should not crash

**Screenshots**
Not applicable

**Logs**
https://pastebin.com/3czknfm0

**Additional context**
Multiple mods have been installed on the server, and it may be an incompatibility. However I cannot confirm this.

**Comment by PolyframeX** [comment]
I believe its the dcintegration mod. It could be an issue on their end potentially.

**Comment by PolyframeX** [comment]
This issue only occurs when the item is named

**Comment by AViewFromTheTop** [comment]
Have you been able to reproduce this on newer versions?

**Comment by AViewFromTheTop** [comment]
Closing as no response has been given.
