### ISSUE TITLE
Support Antique Atlas

### ISSUE THREAD

**Issue by ryleu** [FrozenBlock/WilderWild#355]
**Explain your suggestion here.**
I'd like to see antique atlas support because I think antique atlas fits the exploration of this mod very well.

**Additional context**
[Antique Atlas Mod](https://github.com/sisby-folk/antique-atlas)

Here's what a cypress wetlands biome looks like with no AA support:

![image](https://github.com/FrozenBlock/WilderWild/assets/69326171/24160c4b-72f8-4343-ba7d-da386bd540c9)

**Comment by Treetrain1** [comment]
im not entirely sure what this means

where's the cypress wetlands?

**Comment by AViewFromTheTop** [comment]
> im not entirely sure what this means
> 
> where's the cypress wetlands?

Likwlt LL RGW QWIESLT XOLORED TIJES KUIK

**Comment by AViewFromTheTop** [comment]
wtf happened

**Comment by AViewFromTheTop** [comment]
ignore that

**Comment by AViewFromTheTop** [comment]
Likely the weirdly colored tiles
Thing is, I haven't found any documentation about supporting the mod whatsoever
I tried looking when this was reported

**Comment by AViewFromTheTop** [comment]
https://github.com/AntiqueAtlasTeam/AntiqueAtlas/wiki/API
i found this actually

**Comment by AViewFromTheTop** [comment]
Of course it's stuck on 1.20.1 :/

**Comment by ryleu** [comment]
The weird colored lines are indeed the Cypress Wetlands.

**Comment by AViewFromTheEnd** [comment]
> Likwlt LL RGW QWIESLT XOLORED TIJES KUIK

@Treetrain1 see I was right
