### ISSUE TITLE
Mip Levels Dropped Dramatically 

### ISSUE THREAD

**Issue by LThreeZeroT** [FrozenBlock/WilderWild#356]
I updated my mods in my modpack and the mip levels  dropped. I checked the logs and it said it was the nectar overlay that caused this. 

I was wondering if there was any other mods in my modpack that might cause this to happen. 

P.S. This has never happened to me before

**Comment by LThreeZeroT** [comment]
I am using the most recent version of Wilder Wild on 1.20.1 fabric

**Comment by Treetrain1** [comment]
can you send a log file where the warning occurs

**Comment by LThreeZeroT** [comment]
Do you want the whole log or just the part where it talks about the mip levels?

**Comment by LThreeZeroT** [comment]
I'll just give you the whole thing.

https://mclo.gs/LL3lyqh

It's line 2,060

**Comment by Treetrain1** [comment]
I have a feeling it is caused by Mythic Mounts and Useless Reptile
could you disable those two mods and test if the issue is still there with the nectar overlay?

**Comment by LThreeZeroT** [comment]
I only added useless reptile after this bug occurred though.

**Comment by LThreeZeroT** [comment]
But yes, I will

**Comment by LThreeZeroT** [comment]
Neither had anything to do with the bug.

**Comment by LThreeZeroT** [comment]
Have you found anything?

**Comment by AViewFromTheTop** [comment]
Should be fixed in the next minor update, unless this truly is a mod compat issue.

**Comment by LThreeZeroT** [comment]
Ok

**Comment by LThreeZeroT** [comment]
I updated it, and the firefly nectar overlay was fixed, however now there is a different texture issue.
