### ISSUE TITLE
Item named displaying as "Air". (quilt+fapi-1.20.1)

### ISSUE THREAD

**Issue by tessitalisman** [FrozenBlock/WilderWild#357]
Items and blocks are named "Air" yet their functions are working as expected

Step to Reproduce and non-applicable apart from installing the mod itself

Items should be named accordingly, I.E "Coconut" or "Prickly Pair" instead of "Air"

![Screenshot 2024-03-09 135617](https://github.com/FrozenBlock/WilderWild/assets/78642278/0764af1b-e369-4d66-bcf4-c6766e20ef16)
![Screenshot 2024-03-09 135843](https://github.com/FrozenBlock/WilderWild/assets/78642278/96a32f82-9587-4321-b8ab-99eb77cb3de2)

Logs are very large due to mods folder containing 241 items, I do apologise.
No incompatibility found with EMI nor Jade (I may be wrong)
[latest.log](https://github.com/FrozenBlock/WilderWild/files/14544768/latest.log)

wilder_wild_2.3.2+1.20.1 Installed on quilt-loader-0.24.0-1.20.1 with fabric-api-0.92.0+1.20.1

Affected items are as followed. (Note: I have put down only the block ID's though the respective items to place these blocks are affected as well)

wilderwild:seedling_dandelion
wilderwild:carnation
wilderwild:prickly_pear
wilderwild:tumbleweed_plant
wilderwild:tumbleweed
wilderwild:bush
wilderwild:coconut
wilderwild:cypress_sapling
wilderwild:baobab_nut

**Comment by tessitalisman** [comment]
Additionally, this has been tested with no other mods apart from the fabric API and sodium, achieving similar results with the listed items being labelled "air"

**Comment by Treetrain1** [comment]
Does this issue happen on Fabric Loader?

**Comment by tessitalisman** [comment]
Issue does not occur in fabric loader

**Comment by Treetrain1** [comment]
Please report this issue to Quilt Loader
Consider using Fabric Loader until the issue is fixed
