### ISSUE TITLE
[24w###] Game crashes with Embeddium installed

### ISSUE THREAD

**Issue by SonicGamerEpisode55** [FrozenBlock/WilderWild#359]
**Description of the Bug Encountered**
Game crashes with Embeddium installed on 24wSNAPSHOTS

**Steps To Reproduce**
1.  Install WilderWild and Embeddium
2.  Launch the game
3.  Try to create an new world
4.  Game tells "Loading world..." then "Saving world" then crashes.

**Expected Behavior**
The game loads successfully.

**Screenshots**
The messages are appearing too fast, I can't capture it.

**Logs**
[2024-03-12-1.log](https://github.com/FrozenBlock/WilderWild/files/14577060/2024-03-12-1.log)

**Comment by AViewFromTheTop** [comment]
would you be able to try without sodium? are you on the latest version of it?

**Comment by AViewFromTheTop** [comment]
nevermind, you're on the latest version. let me see if they changed anything.

**Comment by SonicGamerEpisode55** [comment]
Without sodium it works correctly.

**Comment by Treetrain1** [comment]
> would you be able to try without sodium? are you on the latest version of it?

This is not Sodium. This is the fork, Embeddium

**Comment by AViewFromTheTop** [comment]
I've just tested with the 24w10a version of Emdeddium and cannot reproduce this.

**Comment by nickademas** [comment]
> I've just tested with the 24w10a version of Embeddium and cannot reproduce this.

that's weird because it crashes for me too

**Comment by AViewFromTheTop** [comment]
Regardless of the outcome, I've gone out of my way to add support for it in the next major release.
