### ISSUE TITLE
Mip Levels Dropped Dramatically, for a Different Reason Though

### ISSUE THREAD

**Issue by LThreeZeroT** [FrozenBlock/WilderWild#360]
After updating the mod since the most recent version came out, the firefly nectar overlay mip issue has been fixed. However, along with this update, came another mip issue. It has something to do with "minecraft:entity/cow/red_mushroom"

**Comment by AViewFromTheEnd** [comment]
We don’t change that texture.

**Comment by LThreeZeroT** [comment]
Hmm, ok

**Comment by LThreeZeroT** [comment]
It turns out it was a compatibility issue with Fresh Animations.

**Comment by LThreeZeroT** [comment]
But only when the Grappling Hook Mod was installed with it.

**Comment by AViewFromTheEnd** [comment]
Wtf
