### ISSUE TITLE
[Suggestion] SereneSeasons integration

### ISSUE THREAD

**Issue by vico93** [FrozenBlock/WilderWild#361]
Basically, add integration for [SereneSeasons](https://github.com/Glitchfiend/SereneSeasons) ([MR](https://modrinth.com/mod/serene-seasons)) now that that's became a multiloader mod.

By "integration" i mean adding its biomes to SereneSeasons tags according to its climate (eg.: tropical, temperate, infertile, etc) in the mod's internal datapack.

[Here](https://github.com/Glitchfiend/SereneSeasons/tree/HEAD/common/src/main/resources/data/sereneseasons/tags)'s the default tags for vanilla biomes and [here](https://cdn.discordapp.com/attachments/432826613676113920/1183828649317769278/Serene_Seasons_-_Example_Datapack.zip?ex=6601b9d8&is=65ef44d8&hm=2f4c3359d2ebd8b53eb9229619dad7e162d193fa0ab950043abff1f2d27d7e82&)'s a example of how the files need to be organized.

**Comment by AViewFromTheEnd** [comment]
Thank you for pointing this out, and the additional info is especially appreciated!!
Lucky for you, I’m wrapping up the next major version of Wilder Wild and am doing some datagen stuff. I’ll get on it later today!
