### ISSUE TITLE
Config option to disable automatic resource pack apply?

### ISSUE THREAD

**Issue by PolyframeX** [FrozenBlock/WilderWild#363]
**Explain your suggestion here.**
It would be useful if there was a config to disable automatically applying the resource pack. This would help with certain compatibility when making modpacks, and trying to override resource pack defaults.

**Describe alternatives you've considered**
An alternative could be to just have the resource pack be disabled on default. However the first option would be much more preferred.

**Comment by AViewFromTheTop** [comment]
What exactly would be the point of a config for that? You can just disable it once in the Resource Pack menu and it’ll remain disabled. If not, that’s a Fabric API issue.

**Comment by AViewFromTheTop** [comment]
Nevermind. I was a bit tired and didn’t realize this was in relation to modpacks.
I’ll see if I can make a small config later.

**Comment by AViewFromTheTop** [comment]
Just added. Will be included in 2.4's misc config.
