### ISSUE TITLE
Biome using removed sound event

### ISSUE THREAD

**Issue by charlyb01** [FrozenBlock/WilderWild#365]
**Description of the Bug Encountered**

The `sounds.json` of the mod defines music for some added biomes. It adds music, but also Minecraft sound events to avoid duplicating sounds definition. However, it uses `music.overworld.jungle_and_forests` which was removed from the game in an earlier version.

```json
  "music.overworld.wild_forests": {
    "sounds": [
      {
        "name": "music.overworld.jungle_and_forests",
        "type": "event"
      },
```

**Steps To Reproduce**
1. Go in a biome that plays wild_forests sound event
2. Wait for music to play
3. Notice than only the added music are played, and no Minecraft ones

**Expected Behavior**
Shoud be replaced with one of the newly added sound events, such as `music.overworld.bamboo_jungle`, `music.overworld.jungle` and `music.overworld.sparse_jungle`

**Comment by AViewFromTheTop** [comment]
Just fixed this.
Thank you!
