### ISSUE TITLE
Wilder Wild & Croptopia chicken breeding bug

### ISSUE THREAD

**Issue by jimmytrouser** [FrozenBlock/WilderWild#367]
**Description of the Bug Encountered**

Minecraft seeds cannot be used to breed chickens when Wilder Wild and Croptopia are installed.
**Steps To Reproduce**
1. 
2. 
3. 
4. 

**Expected Behavior**

**Screenshots**

**Logs**

**Additional context**
Have tried different fabric versions from 0.14.25 to 0.15.9.   When both mods are installed the bug is present.

**Comment by AViewFromTheTop** [comment]
What version of Wilder Wild are you using, and what Minecraft version are you on?
Wilder Wild doesn’t change anything about Chickens or their food.

**Comment by jimmytrouser** [comment]
Minecraft 1.19.2
Fabric 0.15.9
Wilder Wild 2.0.7
Croptopia 2.2.2

It's weird but if you put croptopia and wilder wild together the chickens will not breed with Minecraft seeds, but they do with Croptopia seeds so there must be a conflict between them, I don't know I am not a coder.

Tags for minecraft seeds say something about wilder wild change.  I used this mod https://modrinth.com/mod/simple-tag-viewer to see.

Hope that helps.

**Comment by Treetrain1** [comment]
I'm sorry, but we aren't accepting issues for 1.19 versions of the game. Our support range at the moment is 1.20.1, 1.20.2, 1.20.4, and 1.20.5 snapshots.
It has become a hassle to support a large number of versions, so we have cut down.

**Comment by jimmytrouser** [comment]
No worries.  Thanks for the reply.
