### ISSUE TITLE
[SUGGESTION] Immersive Weathering compat

### ISSUE THREAD

**Issue by Sunconure11** [FrozenBlock/WilderWild#370]
While I'm waiting on the devs of Fabric Seasons to start looking into the issue with their mod with yours, I noticed IW has a feature that may conflict with your mod, namely, the effects of lightning on sand. Would it be possible to add a config to turn off creating scorched sand via lightning strikes? Primarily on 1.19.2 and 1.20.1, too.

**Comment by AViewFromTheTop** [comment]
We do not support 1.19.2 anymore.
A config has been added for lightning a while ago.
