### ISSUE TITLE
Geysers should put out fires

### ISSUE THREAD

**Issue by Dashy22** [FrozenBlock/WilderWild#372]
**Explain your suggestion here.**
Geyers should put out fires when they blow out their air. I want this since it makes since, and would be cool

**Describe alternatives you've considered**
There's soul fire too

**Additional context**
Blowing out a candle

**Comment by AViewFromTheTop** [comment]
oooooooooo YESSSS YOU ARE A GENIUS

**Comment by AViewFromTheTop** [comment]
Implemented in future update 2.4.2.
Thank you very much!
