### ISSUE TITLE
A technical question

### ISSUE THREAD

**Issue by theprodigy2013** [FrozenBlock/WilderWild#374]
Hello, absolutely loving the mod and cheers for all the hard work. I couldn't help but notice that the mod file is about 55mb big which is more than both aethers, the twilight forest and create mods combined; what could be the reason? Is it all the textures?

**Comment by AViewFromTheTop** [comment]
It's due to the three new tracks by LudoCrypt that the mod adds.
Not really sure of a way to get around that unfortunately, Vanilla's able to download assets but we can't do that.
