### ISSUE TITLE
Snowlogging bugged with Sodium (+Indium) and Continuity

### ISSUE THREAD

**Issue by IJuanTM** [FrozenBlock/WilderWild#377]
**Description of the Bug Encountered**
When using Wilder Wild together with Sodium + Indium and Continuity, snowlogged blocks like grass and flowers will not have a snow layer in them, but instead you can see through the ground.

It seems like there is also other mods that cause the issue besides Continuity, because even without it I still have the issue in my mod pack. But it is really difficult to test because it has 300+ mods.

**Steps To Reproduce**
1. Install these mods:
![image](https://github.com/FrozenBlock/WilderWild/assets/43535731/e62ede3d-61ef-4fb9-b482-5f818aff7b0c)
2. Launch game and make new world
3. Find snow biome and grass and flowers should have the glitch

**Expected Behavior**
Just snow, no visual glitch

**Screenshots**
![2024-05-12_14 11 35](https://github.com/FrozenBlock/WilderWild/assets/43535731/610289b5-b3b5-4add-a185-c9796317a836)

**Logs**
[latest.log](https://github.com/FrozenBlock/WilderWild/files/15286261/latest.log)

**Additional context**
I tried other connected texture mods like Fusion or Athena, but those seem to be working fine. It also works without Sodium + Indium. Which makes me think it is mainly an issue with those, but Continuity exposes the issue in some way.

**Comment by AViewFromTheTop** [comment]
@Treetrain1 how would we even fix this

**Comment by samualtnorman** [comment]
is there a known workaround?

**Comment by AViewFromTheTop** [comment]
> is there a known workaround?

Not at the moment.
The best solutions are using another Connected Textures mod, or disabling Snowlogging in the config.

**Comment by NUTsTUN** [comment]
Running into the same issue on my 1.20.1 modpack.

I tried to recreate with the above scenario but there seems to be something else causing the issue.

![Screenshot 2024-06-20 171817](https://github.com/FrozenBlock/WilderWild/assets/3260169/fcc669f2-9c99-40ef-8494-607d80427702)

Minecraft Version: 1.20.1
Fabric Loader: 0.15.11

![2024-06-20_17 21 20](https://github.com/FrozenBlock/WilderWild/assets/3260169/9cdfaa0e-3ea2-46eb-9075-c4b7f58ec9ab)

**Comment by AViewFromTheTop** [comment]
I was just able to fix this.
Please note, however, that we are only supporting 1.21+ from now on.

**Comment by NUTsTUN** [comment]
Is that inclusive or exclusive to this change? (Will this fix specifically be available for 1.20.1?)

**Comment by AViewFromTheTop** [comment]
Fiiiiine I’ll try to backport the update once it’s finished 😭😭😭
Technically I shouldn’t as we’ve all agreed to drop everything below 1.21 already but whatever I’ll do my best
