### ISSUE TITLE
Error joining in a world after closing the game using this mod

### ISSUE THREAD

**Issue by Yoni664** [FrozenBlock/WilderWild#378]
When I use this mod I can create a new world without problems and play in it, the problem arises when I close the game, reopen it and reload that same world. The game will load the world for a while but after a while it takes me to the main menu with a message that says: "Error accessing the world." I suppose it is probably some trouble with a incompatibility mod, since I think this is a unique case but I still wanted to report it in case you can check the log

**Steps To Reproduce**
1. Create a new world (You will be able to play in the world without problems)
2. Close the game
3. Open the game
4. Join the same world

**Expected Behavior**
Re join to the world without problems

**Screenshots**
![Minecraft Screenshot 2024 05 13 - 01 49 26 48](https://github.com/FrozenBlock/WilderWild/assets/143241985/65db524f-fdb8-43a6-ae79-8a896514aa51)

**Logs**
[latest.log](https://github.com/FrozenBlock/WilderWild/files/15291149/latest.log)

**Comment by AViewFromTheTop** [comment]
Please disable the config option for removing the Experimental warning in FrozenLib’s config. Install Cloth Config and enable libraries in ModMenu.
