### ISSUE TITLE
Optimized hollowed log model with compatibility and proper culling

### ISSUE THREAD

**Issue by Soulfate24** [FrozenBlock/WilderWild#379]
Hi!
I've optimized the "hollowed" and "stripped hollowed" log models by using 8 blocks, vanilla textures (excepted for Baobab, Cypress and Palm) and proper culling so it's performance friendly. "Hollowed" textures are not used anymore (only original "log" and "stripped" ones are necessary).
LINK (1.20.4 version): https://drive.google.com/drive/folders/1xGpq_7k6lbDsQSxXiSVVdcsZD3FwRZKk
![wilderwild_optimized_hollow](https://github.com/FrozenBlock/WilderWild/assets/27165775/96dc3d00-e512-4de1-86c8-e80c272a9584)

With love,
Soulfate

**Comment by AViewFromTheTop** [comment]
Have you checked how this looks in-game?
The main issue is that for whatever reason, it causes some parts of the texture to be misaligned in-game.
No clue why, and is absolutely a vanilla issue. If you’ve gotten that to somehow not happen, I’ll gladly implement this.

**Comment by Soulfate24** [comment]
About gap issues, you have the mod "model gap fix" that fixes any misaligned sides (while the rendering is perfect in the editor). It's a universal fix and it works with this kind of custom models ;) I've honestly forgotten about this issue because I always have "model gap fix" installed.

**Comment by AViewFromTheTop** [comment]
I would prefer if a Vanilla solution were introduced instead, as I personally prefer the mod to work with strictly just Fabric API and nothing else out of the box.

**Comment by Soulfate24** [comment]
I understand, thank you for your time ;) I'm going back to my resourcepack :P

**Comment by Soulfate24** [comment]
Hi,
It's me again.
I've ran the game with Quilt, Wilder Wild and my log resources only. There is no issue ;)
![test](https://github.com/FrozenBlock/WilderWild/assets/27165775/c9611f2d-08e0-4a00-a67f-4d6db659ffc0)

**Comment by AViewFromTheTop** [comment]
I'll give it a shot, however I still expect this issue to happen. It's been very subtle but noticeable once you look in the right place.

**Comment by AViewFromTheTop** [comment]
wtf the issue doesnt happen?????
@Treetrain1 this is crazy
