### ISSUE TITLE
World Freezing with Antique Atlas

### ISSUE THREAD

**Issue by serenyadev** [FrozenBlock/WilderWild#381]
**Description of the Bug Encountered**
World Freezing while loading/generating chunks with Antique Atlas and Wilder Wild installed, related to [this issue](https://github.com/sisby-folk/antique-atlas/issues/106)

**Steps To Reproduce**
1. Install Antique Atlas and Wilder Wild
2. Make sure Snowlogging is enabled (disabling it fixes this)
3. Create a new world or enter an existing one
4. The world will freeze when attempting to load a chunk with a snowlogged block in it

**Expected Behavior**
The game running normally

**Logs**
The error seems to be located at like 1440 in the thread dump
[thread dump.txt](https://github.com/FrozenBlock/WilderWild/files/15444587/thread.dump.txt)
[latest.log](https://github.com/FrozenBlock/WilderWild/files/15444583/latest.2.log)

**Additional context**
I tested this with more mods installed but based on the logs it is pretty obvious that Antique Atlas and Wilder Wild are the culprits,if you need a mod only log please ask

**Comment by MathiewMay** [comment]
I can confirm this

**Comment by serenyadev** [comment]
If you want to play with them for now, disable snowlogging in the wilder wild config, that fixes the issue.

**Comment by MathiewMay** [comment]
> If you want to play with them for now, disable snowlogging in the wilder wild config, that fixes the issue.

Thank you this fix seems to work!

**Comment by AViewFromTheTop** [comment]
will be "fixing" this by disabling snowlogging with antique atlas installed in 2.4.8
