### ISSUE TITLE
Stone Chests no longer animating correctly when attempting to open

### ISSUE THREAD

**Issue by lambsie11** [FrozenBlock/WilderWild#383]
**Description of the Bug Encountered**
When attempting to open a Stone Chest in versions 2.4.1 and 2.4.2, the animation that is meant to play will not play. 

**Steps To Reproduce**
1. Place down a Stone Chest or locate a naturally spawning Stone chest in the aforementioned versions.
2. Attempt to open it.
3. The animation that is supposed to play when opening it does not play.

**Expected Behavior**
The stone chest should be playing it's partial opening animation when interacted with.

**Additional context**
This bug is notably not present in 2.4 and earlier, leading me to believe that it appeared from the switch to using the 'setChanged' method for block entities.

**Comment by AViewFromTheTop** [comment]
This is fixed in the next release.
Just hang tight!
