### ISSUE TITLE
1.21 Frozen Lib is from 1.20.6 not 1.21

### ISSUE THREAD

**Issue by makumaku1974** [FrozenBlock/WilderWild#387]
**Description of the Bug Encountered**

**Steps To Reproduce**
1. 
2. 
3. 
4. 

**Expected Behavior**

**Screenshots**
![Screenshot 2024-06-20 162029](https://github.com/FrozenBlock/WilderWild/assets/129804277/b37a25b8-3680-4559-ac4d-070cdb020215)

**Logs**

**Additional context**

**Comment by Treetrain1** [comment]
Use Wilder Wild 2.4.4
