### ISSUE TITLE
Problems with the embedded version of FrozenLib 1.20.1

### ISSUE THREAD

**Issue by Yoni664** [FrozenBlock/WilderWild#388]
Minecraft dosn't launch due a problem with the embedded version of frozenlib
WilderWild version: 2.4.4
Minecraft version 1.20.1
Fabric version: 0.15.11

**Steps To Reproduce**
1. Update wilder wild
2. Launch minecraft
3. Some mods wont load due a problem with the embedded version of FrozenLib in wilderwild

**Expected Behavior**
Game starts

**Screenshots**
![Captura](https://github.com/FrozenBlock/WilderWild/assets/143241985/b1a0100d-c8a8-45b2-9899-1ea434254563)

**Logs**
[latest.log](https://github.com/user-attachments/files/15919724/latest.log)

**Comment by Treetrain1** [comment]
Do you have the FrozenLib mod installed separately

**Comment by Yoni664** [comment]
Ok, first I looked for the word Frozen in the .minecraft folder, and some files appeared in a folder called processed mods, I deleted those files and others with the .dat extension. Thanks to this, the error that fabric throws has changed but it still indicates that version 1.5.2 of frozenlib is present

![dadad](https://github.com/FrozenBlock/WilderWild/assets/143241985/a24df40d-0614-4060-8101-f4d5fece2306)

Then even when I searched for the word "frozen" in the .minecraft folder, there is nothing related to that word, so I don't know where else it could be loading that version if not internally from the .minecraft folder

![fznohay](https://github.com/FrozenBlock/WilderWild/assets/143241985/24901c5a-773c-4556-aabe-6ff198cb0341)

**Comment by Treetrain1** [comment]
Can you send your modlist

**Comment by Yoni664** [comment]
Sure, I created this from the cmd cos I don't know how to do it in another way, hope this helps
[mods.txt](https://github.com/user-attachments/files/15922922/mods.txt)

**Comment by Treetrain1** [comment]
Install Fabric Language Kotlin 0.11.0

**Comment by Yoni664** [comment]
Thx! This fixes the problem!

**Comment by AViewFromTheEnd** [comment]
wtf 😭
