### ISSUE TITLE
1.21 Crashed for some reason...

### ISSUE THREAD

**Issue by makumaku1974** [FrozenBlock/WilderWild#389]
**Description of the Bug Encountered**

Launched the game but im running with 299+ mods.. I have only 2 big biome overhauls, Biomes o Plenty and William Whyters Overhaul

**Logs**
[2024-06-21-3.log.gz](https://github.com/user-attachments/files/15923262/2024-06-21-3.log.gz)

**Comment by AViewFromTheTop** [comment]
I haven't seen anything related to Wilder Wild in the logs, but the beehive dimension mod seems a bit concerning (though from potentially harmless logs, failing to teleport entities)
id suggest you try without it anyway, or at least try to obtain new logs

**Comment by makumaku1974** [comment]
I actually send them this bug too no worries. I'll be back after testing.

**Comment by Rebel459** [comment]
A basic rule of modpack dev is not to ask mod devs to work out your problems, but instead to be certain of the mods conflicting with each other first _and then_ report it to the relevant devs if the issue isn’t known.
