### ISSUE TITLE
Strange log entries after singleplayer world "froze"

### ISSUE THREAD

**Issue by vico93** [FrozenBlock/WilderWild#390]
I got a strange issue where my singleplayer world just "froze" (felt like the internal server stopped working), and i needed to terminate the `javaw` process using Task Manager.

While it didn't generated any crash report, the [latest.log](https://gist.github.com/vico93/5a7c599ededdba6c3814d22271286368) contains a plenty of errors mentioning both Cloth Config and Wilder Wild, i'm not sure if this is related or not with the freeze and what mod was the responsible.

- minecraft 1.21
- fabricloader 0.15.11
- fabric-api 0.100.3+1.21
- wilderwild 2.4.4-Fabric+1.21
- I also have [mixintrace](https://modrinth.com/mod/mixintrace) and [stackdeobfuscator](https://modrinth.com/mod/stackdeobf), in case you find my log "weird".

**Comment by Treetrain1** [comment]
Definitely not a Wilder Wild issue, but I don't know what mod is causing it. I believe a mod is making a vanilla-only registry lookup, which basically just ignores all modded content and makes the game error out.

**Comment by vico93** [comment]
Thanks for the clarification!

**Comment by vico93** [comment]
Well, after doing some tests tweaking around mods to try to figure out what was causing the freezing issue, i ended up figuring out that taking out WilderWild solves the issue.

If you guys have interest, i can zip my profile folder on Discord for you to test.
