### ISSUE TITLE
1.21 It seems that this is conflicting with EXT Shapes. What do i do?

### ISSUE THREAD

**Issue by makumaku1974** [FrozenBlock/WilderWild#391]
crash log : 
[crash-2024-06-21_17.47.41-client.txt](https://github.com/user-attachments/files/15926196/crash-2024-06-21_17.47.41-client.txt)

Log : 
[2024-06-21-6.log.gz](https://github.com/user-attachments/files/15926198/2024-06-21-6.log.gz)

**Comment by Treetrain1** [comment]
This is an EXT Shapes issue. There's nothing we can do about.
Please make a bug report over there.

The issue is they use `BuiltinRegistries` in `pers.solid.brrp.v1.impl.RuntimeResourcePackImpl`, which crashes any time there's any modded content.

**Comment by makumaku1974** [comment]
This is now fix with the new BRRP api. It is now fully compatible with Wilder Wilds.
