### ISSUE TITLE
Hypixel issue

### ISSUE THREAD

**Issue by Omni-Man1** [FrozenBlock/WilderWild#392]
When I load up Hypixel, every block in the whole server seems to have swapped place with another block. For example, in bedwars the wool has swapped place with the half of a bed.

**Comment by AViewFromTheTop** [comment]
This is a known issue, simply because Wilder Wild adds additional states to existing blocks.
Just disable the mod prior to playing on servers without it installed. The Modrinth launcher makes this quick and easy.

**Comment by Omni-Man1** [comment]
Thank you!
