### ISSUE TITLE
Weird droplets. 1.21

### ISSUE THREAD

**Issue by makumaku1974** [FrozenBlock/WilderWild#396]
**Explain your suggestion here.**
You see I actually dislike this feature, it's hacking away my framerates to 20.

**Describe alternatives you've considered**
Please do it in a biome that is procuring heat.

**Additional context**

![2024-07-06_13 50 51](https://github.com/FrozenBlock/WilderWild/assets/129804277/9ef0397f-08eb-40ea-9730-1452c0050e46)

**Comment by Rebel459** [comment]
What does this have to do with Wilder Wild? Looks like an issue with whatever modpack you’re playing

**Comment by makumaku1974** [comment]
Actually, I created the modpack. I'll close this right now for the inconvenience.

**Comment by makumaku1974** [comment]
Well, Im reopening this issue again because this time it didn't happen. As you can see I removed Wilder Wild this time and created a new world and no droplets happen. 

![2024-07-06_18 48 38](https://github.com/FrozenBlock/WilderWild/assets/129804277/f2471d74-c047-4eb6-931f-70162f62daf2)

Please, I still need to confirm this issue to another mod called Extended Shapes since the api mod BRRP is still on Beta. I need to clarify it yet to what is happening with both of this screenshots.

**Comment by makumaku1974** [comment]
Here is also a Log file if it helps https://mclo.gs/Mz9wjtp

**Comment by Rebel459** [comment]
I have no clue what is causing the problem tbh, but I do know that Wilder Wild does not do this by itself.

**Comment by AViewFromTheTop** [comment]
There’s no way that’s our issue 😭
The only time those are referenced in our mod is to spawn alongside water drip particles for waterlogged red mesoglea

**Comment by AViewFromTheTop** [comment]
In warmer oceans you’ll find Red Jellyfish, and killing them yields Red Nematocyst.
4 Red Nematocyst crafts into 1 Red Mesoglea.
The whole idea behind Mesoglea is that it’s solid, but can be passed through when waterlogged. Basically can be used as water that doesn’t flow.

**Comment by makumaku1974** [comment]
So it looks like the one that is dripping from the screenshot right? I guess Extended Block Shapes is still incompatible with Wilder Wild. Btw are you fine testing both mods?

**Comment by Rebel459** [comment]
Testing an issue with another mod is either the responsibility of the modpack dev or (after the issue is found) the responsibility of the dev of the mod primarily responsible for the problems. Neither of those are Wilder Wild. Either remove the other mod or have the dev of the mod causing the issue find a fix. If the fix requires some work on Wilder Wild’s part, then re-open this / create a new issue

**Comment by makumaku1974** [comment]
will do.

**Comment by AViewFromTheTop** [comment]
> So it looks like the one that is dripping from the screenshot right? I guess Extended Block Shapes is still incompatible with Wilder Wild. Btw are you fine testing both mods?

Red Mesoglea doesn’t generate naturally, and it only drips if there is no block or liquid below.
…which makes this very confusing.

**Comment by AViewFromTheTop** [comment]
They also only drip while waterlogged.
Mesoglea is also always transparent and emits a bit of light, so you’d very obviously see it there.
In this case, they’re not even there.

**Comment by makumaku1974** [comment]
> They also only drip while waterlogged. Mesoglea is also always transparent and emits a bit of light, so you’d very obviously see it there. In this case, they’re not even there.

Hey, I actually managed to remove the problem but I'll check out biomes o plenty if it is causing the issue. The pre-release version of the BRRP https://github.com/SolidBlock-cn/extshape/issues/46#issuecomment-2229898967 is this one.

**Comment by AViewFromTheTop** [comment]
> > They also only drip while waterlogged. Mesoglea is also always transparent and emits a bit of light, so you’d very obviously see it there. In this case, they’re not even there.
> 
> Hey, I actually managed to remove the problem but I'll check out biomes o plenty if it is causing the issue. The pre-release version of the BRRP [SolidBlock-cn/extshape#46 (comment)](https://github.com/SolidBlock-cn/extshape/issues/46#issuecomment-2229898967) is this one.
> 
> Voila, No more jelly droplets. ![image](https://private-user-images.githubusercontent.com/129804277/348933891-d78e6d55-9ab5-44bb-ad12-a7e0a46cc29a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMDI3NzAsIm5iZiI6MTcyMTEwMjQ3MCwicGF0aCI6Ii8xMjk4MDQyNzcvMzQ4OTMzODkxLWQ3OGU2ZDU1LTlhYjUtNDRiYi1hZDEyLWE3ZTBhNDZjYzI5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwNDAxMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOGY1YWNmZGQ0YzM0MjEzOTc1ODJlODEzMGE5MGJlNGQzYTc0MjU4NWNjMzcyYTBhNGI1ZTdiOWI5MmVlOGQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QWQ9pg3aWvyt3BouxEMetjWvECMJsgDk4gi3PVWcrxk)

i am so confused

**Comment by makumaku1974** [comment]
> > > They also only drip while waterlogged. Mesoglea is also always transparent and emits a bit of light, so you’d very obviously see it there. In this case, they’re not even there.
> > 
> > 
> > Hey, I actually managed to remove the problem but I'll check out biomes o plenty if it is causing the issue. The pre-release version of the BRRP [SolidBlock-cn/extshape#46 (comment)](https://github.com/SolidBlock-cn/extshape/issues/46#issuecomment-2229898967) is this one.
> > Voila, No more jelly droplets. ![image](https://private-user-images.githubusercontent.com/129804277/348933891-d78e6d55-9ab5-44bb-ad12-a7e0a46cc29a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMDI3NzAsIm5iZiI6MTcyMTEwMjQ3MCwicGF0aCI6Ii8xMjk4MDQyNzcvMzQ4OTMzODkxLWQ3OGU2ZDU1LTlhYjUtNDRiYi1hZDEyLWE3ZTBhNDZjYzI5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwNDAxMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOGY1YWNmZGQ0YzM0MjEzOTc1ODJlODEzMGE5MGJlNGQzYTc0MjU4NWNjMzcyYTBhNGI1ZTdiOWI5MmVlOGQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QWQ9pg3aWvyt3BouxEMetjWvECMJsgDk4gi3PVWcrxk)
> 
> i am so confused

Me too, to be honest im resetting my modpack to zero. And fix all things that needs to be fixed.
