### ISSUE TITLE
Crash: Missing Attribute 'minecraft:generic.attack_damage' When Ticking Jellyfish

### ISSUE THREAD

**Issue by 107nicho** [FrozenBlock/WilderWild#400]
**Description of the Bug Encountered**
When playing on a Fabric modded server in version 1.21, the game crashes with an **'IllegalArgumentException'** indicating that the attribute **'minecraft:generic.attack_damage'** cannot be found. This crash occurs when the game attempts to tick a custom entity, specifically the Jellyfish entity from the **'wilderwild'** mod.

**Steps To Reproduce**
1. Install Minecraft 1.21 with Fabric Loader 0.16.0.
2. Add the wilderwild mod and other listed mods (see mod list below).
3. Spawn a Jellyfish entity in the game.
4. Wait for the game to tick the entity, which results in a crash.

**Logs**
Singleplayer crash log
[crash-2024-07-15_16.57.21-server.txt](https://github.com/user-attachments/files/16240847/crash-2024-07-15_16.57.21-server.txt)
Multiplayer crash log
[crash-2024-07-15_17.04.06-server.txt](https://github.com/user-attachments/files/16240848/crash-2024-07-15_17.04.06-server.txt)

**Mod List**
advancedcombat: Advanced Combat (Revitalized) 1.21-4.3FC
advancednetherite: Advanced Netherite 2.1.6-1.21
animal_feeding_trough: Animal Feeding Trough 1.1.1+1.21
architectury: Architectury 13.0.4
better_climbing: Better Climbing 3
betterfpsdist: Better FPS distance Mod 1.21-4.3
biomesoplenty: BiomesOPlenty 21.0.0.12
buildguide: Build Guide 0.4.1
camerapture: Camerapture 1.6.0
cardinal-components: Cardinal Components API 6.1.0
cicada: CICADA 0.8.1+1.21-and-above
cloth-config: Cloth Config v15 15.0.127
comforts: Comforts 9.0.0+1.21
connectivity: Connectivity Mod 1.21-5.7
creativecore: CreativeCore 2.12.1
croptopia: Croptopia 3.0.4
cupboard: cupboard 1.21-2.7
do_a_barrel_roll: Do a Barrel Roll 3.6.1+1.21
earthtojavamobs: Earth2Java 1.11.5
easymagic: Easy Magic 21.0.1
elementa: Elementa 649
elementalenchantments: Elemental Enchantments 2.0.0
endrem: End Remastered 5.3.2
entityculling: EntityCulling 1.6.6
epherolib: EpheroLib 1.2.0-1.20.6
essential: Essential 1.3.2.8
explorify: Explorify 1.6.1
fabric-api: Fabric API 0.100.6+1.21
fabric-language-kotlin: Fabric Language Kotlin 1.10.19+kotlin.1.9.23
fabricloader: Fabric Loader 0.16.0
forgeconfigapiport: Forge Config API Port 21.0.2
geckolib: GeckoLib 4 4.5.6
geophilic: Geophilic 2.4.3
glitchcore: GlitchCore 2.0.0.2
gpumemleakfix: Gpu memory leak fix mod 1.21-1.8
handcrafted: Handcrafted 4.0.1
hopobettermineshaft: Hopo Better Mineshaft 1.2.5
hopobetterruinedportal: Hopo Better Ruined Portal 1.4.2
hopobetterunderwaterruins: Hopo Better Underwater Ruins 1.1.8
indium: Indium 1.0.34+mc1.21
iris: Iris 1.7.3+mc1.21
jei: Just Enough Items 19.5.0.31
kiwi: Kiwi Library 15.1.0+fabric
krypton: Krypton 0.2.8
lithium: Lithium 0.12.7
mavapi: More Axolotl Variants API 1.2.1
mcwdoors: Macaw's Doors 1.1.1
mcwfences: Macaw's Fences and Walls 1.1.2
mcwlights: Macaw's Lights and Lamps 1.1.1
minecraft: Minecraft 1.21
modernfix: ModernFix 5.18.8+mc1.21
modmenu: Mod Menu 11.0.1
more_armor_trims: More Armor Trims 1.3.2-1.21
mr_dungeons_andtaverns: Dungeons and Taverns

**System Details**
Operating System: Windows 10 (amd64) version 10.0
Java Version: 21.0.3, Oracle Corporation
Memory: 8GB allocated to Minecraft
CPU: Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz
GPU: NVIDIA GeForce RTX 2060 SUPER

**Additional Information**
The crash seems to be related to the elementalenchantments mod, specifically when it tries to check for the minecraft:generic.attack_damage attribute. It is also noteworthy that the Jellyfish entity from the wilderwild mod triggers this issue during its stingEntities method.

**Comment by Treetrain1** [comment]
can you see if this issue occurs when pufferfish sting entities

**Comment by 107nicho** [comment]
This issue can be recreated by spawning in a pufferfish and having it sting another entity or the player, here is the crash report: 
[crash-2024-07-16_17.55.31-server.txt](https://github.com/user-attachments/files/16257376/crash-2024-07-16_17.55.31-server.txt)

I also had this occur when a snowman threw a snowball and the snowball came in contact with a separate entity, this is the crash report for that incident:
[crash-2024-07-15_19.55.45-server.txt](https://github.com/user-attachments/files/16257382/crash-2024-07-15_19.55.45-server.txt)

**Comment by 107nicho** [comment]
This error was caused by a conflict in the Elemental Enchantments (v2.0.0) mod and had nothing to do with Wilder Wilds, the new update (v2.0.1) of Elemental Enchantments addresses and fixes this conflict.
