### ISSUE TITLE
Some saplings missing and others not growing when bonemealed.

### ISSUE THREAD

**Issue by Gamemassa** [FrozenBlock/WilderWild#401]
**Version**
- Minecraft 1.21
- Fabric Loader 0.16.0
- Fabric API 0.100.7
- Wilder Wild 2.4.6 for MC 1.21

**Description of the Bug Encountered**
I eventually got Wilder Wild to work in my modpack with the latest beta of BRRP, but I've noticed that Palm saplings are completely missing from the item list (both in REI and in creative inventory). 
![image](https://github.com/user-attachments/assets/0d1d1790-79f9-4c23-b51a-da708330d566)

Also, I used bone meal on (what I assumed is) a Baobab sapling and Jade shows its growth level as "Mature", but it didn't actually grow at all.
![image](https://github.com/user-attachments/assets/e1f9c79e-8eb5-45e2-b491-ac7c8727fe50)

**Comment by Soro335** [comment]
To grow a baobab you need to place saplings 4x4

**Comment by Kluski42** [comment]
Coconuts are palm tree saplings, in the same way baobab nuts are baobab tree saplings.

**Comment by Gamemassa** [comment]
> To grow a baobab you need to place saplings 4x4

![image](https://github.com/user-attachments/assets/bfac3a44-9c67-4f9c-80ca-8f534df0740f)
I tried that too. Still nothing.

**Comment by Gamemassa** [comment]
Gotcha. Thanks for confirming!
