### ISSUE TITLE
Can you please remove Motion Blur on the Wilder Wild's option menu.

### ISSUE THREAD

**Issue by makumaku1974** [FrozenBlock/WilderWild#402]
**Explain your suggestion here.**
It gives me motion sickness at times.

**Describe alternatives you've considered**
Just be a normal minecraft option theme.

**Additional context**
![image](https://github.com/user-attachments/assets/6bb523d4-ab43-4ea3-a925-b07e4e8ef72c)

**Comment by AViewFromTheTop** [comment]
This is a Cloth Config issue, not ours

**Comment by makumaku1974** [comment]
ok

**Comment by AViewFromTheTop** [comment]
> ok

Good news, just fixed it.
It's still a Cloth issue, but it's caused by the setBackground method... which they should've removed the functionality of and deprecated in 1.21 versions, but kept for simplicity of supporting older versions.

**Comment by makumaku1974** [comment]
is it on the update?

**Comment by AViewFromTheTop** [comment]
> is it on the update?

It'll be releasing very soon :)

**Comment by AViewFromTheTop** [comment]
Here you go!
https://modrinth.com/mod/wilder-wild/version/2.4.7-mc1.21
