### ISSUE TITLE
World freezes when wardens use their sonic boom on echo glass.

### ISSUE THREAD

**Issue by UshankThePog** [FrozenBlock/WilderWild#404]
**Description of the Bug Encountered**
When a warden uses their sonic boom, the world will freeze when echo glass is in its path.

**Steps To Reproduce**
1. Anger a warden.
2. Stall long enough for it to use its attack.
3. Place echo glass in between you and the warden.

**Expected Behavior**
The echo glass cracks and the chase continues as normal.

**Screenshots**
![2024-07-29_01 31 13](https://github.com/user-attachments/assets/447b4e50-a682-4192-b33b-62b36b07efe7)

**Logs**
[latest.log](https://github.com/user-attachments/files/16408691/latest.log)

**Additional context**

**Comment by AViewFromTheTop** [comment]
We aren't supporting issues with Quilt in use, as it's notorious for having.. well... issues.
All I can say is to report back if this works fine or not without Effective installed.
