### ISSUE TITLE
Regular forests are too busy and not distinct enough from flower forests

### ISSUE THREAD

**Issue by JanTheLynx** [FrozenBlock/WilderWild#405]
So far I'm loving this mod and can't help but ask why some of these features aren't already in vanilla. However, I think the tulips and commonality of colorful flowers in regular forests are a little overboard, and they take away from the uniqueness of flower forests. They make regular forests look so busy in addition to the pollen particles everywhere.

One thing I enjoy about this mod is how seamless much of its content would be in vanilla while still spicing things up and giving us some of the updates we were teased about but never got. When a common, "bland" biome is overly busy, it kinda takes away from that. I also think tulips should still be rare in plains biomes, even if less so than in vanilla.

Now that's just my opinion. Do with it what you will.

**Comment by AViewFromTheTop** [comment]
![2024-07-29_23 16 36](https://github.com/user-attachments/assets/2d85c18e-2e36-4539-876f-d02cf1fe78b9)
![2024-07-29_23 15 50](https://github.com/user-attachments/assets/bfe429a3-ad5d-4038-a3c7-ab54e1e08dad)
Forest vs. Flower Forest
I'll go ahead and increase the amount of flowers slightly in flower forests, but idk if that'll do much

**Comment by AViewFromTheTop** [comment]
lol this is making me do a whole flower gen update
