### ISSUE TITLE
Incompatibility with Interactic. 1.21

### ISSUE THREAD

**Issue by makumaku1974** [FrozenBlock/WilderWild#406]
**Description of the Bug Encountered**
This managed to work previously but I think that was covered by other mods that suppressed Interactic from crashing.

**Expected Behavior**
Interactic crashing with Wilder Wild without the help of other mods.

**Screenshots**
![image](https://github.com/user-attachments/assets/fb4e9719-73f7-48a0-b5e3-82b583a51e0d)

**Logs**
https://mclo.gs/bUlIdFY

**Additional context**

**Comment by AViewFromTheTop** [comment]
The logs you sent definitely aren’t the right ones
Wilder Wild is mentioned nowhere

**Comment by makumaku1974** [comment]
my bad. I could have send the wrong one.
