### ISSUE TITLE
SIHYWTCAMD Incompatibility [MC 1.21] [Fabric Loader 0.16.2]

### ISSUE THREAD

**Issue by Toimis** [FrozenBlock/WilderWild#408]
Hello,

I play with a decently large modpack and noticed at some point after updating mods that my friends were experiencing issues. It seemed like blocks had ID mismatches or something, causing them to appear as waterlogged or as entirely different blocks for them, but normal for me (since I play singleplayer and open the world using Essential when they have time to play).

The issue is reproducible for me with only Fabric API, SIHYWTCAMD, and Wilder Wild. If you join a random server (I used Hypixel), you will notice some crazy stuff happening. I have not tried reproducing on a fresh install, so it's probably a lost cause if you cannot because I had over 100 mods at some point lol.

I will also be reporting this issue to the SIHYWTCAMD repository.

Thank you!

PS: Love the mod, and appreciate the work you put in!

**Screenshots**
![Screenshot 2024-08-21 051924](https://github.com/user-attachments/assets/479677d1-a18c-4701-aadd-55b850a66be6)
![Screenshot 2024-08-21 051727](https://github.com/user-attachments/assets/d8e04a31-6026-49a1-9cd3-bc55ad3d6c9e)

**Logs**
[latest.log](https://github.com/user-attachments/files/16691376/latest.log)

**Comment by AViewFromTheTop** [comment]
You just have to remove Wilder Wild when playing on servers that don’t have it installed

**Comment by Toimis** [comment]
That was just to reproduce the issue easily. I play on a singleplayer world and host a server using the Essential mod. If it's too bothersome to fix, I actually don't really mind since I would prefer to have this mod. I just figured I should let you both know. 
Regardless, thank you.
