### ISSUE TITLE
Can't open Stone Chest in 1.21.1-Fabric

### ISSUE THREAD

**Issue by Akinesis** [FrozenBlock/WilderWild#412]
**Description of the Bug Encountered**
Stone chest don't open any interface.
This appen with chest placed manualy 

**Steps To Reproduce**
1. Find or place a Stone Chest
2. Right click to open
3. The chest play it's open animation but nothing happen.

**Expected Behavior**
The chest should open and reveal it's inventory

**Screenshots**
![image_2024-09-07_140440070](https://github.com/user-attachments/assets/f176a835-f900-4395-b85f-aa67e6cc3a84)

**Logs**
https://mclo.gs/HqyeDhd

**Additional context**
I've tested this on a large modpack and on a small instance with no mods that should interfere.
I played on Fabric 1.21.1
Also, this line is in the logs : 
[13:52:53] [Render thread/WARN]: Encountered duplicate API provider registration for block: wilderwild:stone_chest

**Comment by AViewFromTheTop** [comment]
This is intentional. You have to lift the lid multiple time before you can open it.
