### ISSUE TITLE
Snowlogging broken textures 1.21.1

### ISSUE THREAD

**Issue by Lumguava** [FrozenBlock/WilderWild#418]
Hi! I've encountered a bug in 1.21.1 that also seemed to be present in previous versions which involves snowlogging. I've tried uninstalling Indium and Continuity as a temporary fix but the issue seems to persist. Then after I put my dedicated server to maintenance mode and backed up the files, I tried to disable snowlogging and completely corrupted the world (which I expected due to worldgen mods).

1.  Ran server with Continuity and Indium present. Broken textures on snowlogged blocks with a grass, wall, fence, etc on top.
2.  Removed the two mods and ran server again, issue still persists.

Mod list:
[modlist.txt](https://github.com/user-attachments/files/17170432/modlist.txt)

Screenshots:
![2024-09-27_23 33 46](https://github.com/user-attachments/assets/42ee5aaa-310e-464f-9bf3-0ec49491b4a0)

Logs:
[latest.log](https://github.com/user-attachments/files/17170431/latest.log)

Thanks for taking your time to read!

**Comment by Kluski42** [comment]
This looks like a compatability issue, what's the mod that causes your grass to look this way?

**Comment by AViewFromTheTop** [comment]
If you’re using Sodium 0.6+, please remove Indium. It is no longer needed and will very likely solve the issue.

**Comment by AViewFromTheTop** [comment]
Otherwise, please update to Sodium 0.6 and remove Indium. I am no longer supporting Indium compat at or above 1.21 as Sodium has removed the need for it and 0.6 runs much better than previous versions.

**Comment by Lumguava** [comment]
Hello! Thanks for replying. Tested out removing Indium and it seemed to have solved my Sodium 0.6 beta crash issues and fixed the snowlogging textures as well! Thank you for informing me about the Indium incompatibility. I wouldn't have known so easily since Indium was an essential mod together with the other caffeine mods and got used to it w/o question.

So far, no issues were found during 5 hours of gameplay (without Indium and with Sodium 0.6) since I've done the steps.

Thank you so much for your time and help!

**Comment by AViewFromTheTop** [comment]
> Thank you so much for your time and help!

Of course!!
It’s definitely important to read changelogs for mod updates by the way, especially if you notice a sudden crash like that. Not many people were actually aware of Indium becoming redundant despite it being noted in the changelog, I’ve had to tell quite a few people about that myself even in instances unrelated to Wilder Wild
Plus, you might miss out on smaller details changes and added in updates like Wilder Wild dropping new mud brick blocks a while ago

**Comment by AViewFromTheTop** [comment]
On that note, the Sodium team themselves also noted no issues so the 0.6 beta is pretty stable from what I’ve seen
