### ISSUE TITLE
Neoforge Sinytra 1.21 "error loading mods" with 2.4.10 or above

### ISSUE THREAD

**Issue by axtrough** [FrozenBlock/WilderWild#420]
**Description of the Bug Encountered**
The ones that are above 2.4.9 do not work and gives me the errors you can see in the images
the ones above should be for both 1.21 - 1.21.1

**Steps To Reproduce**
1.  download latest neoforge sinytra stuff with the connector extras.
2. download any wilder wild version thats 2.4.10 or above
3. launch the game
4.  error

**Expected Behavior**
The mod should load in and shouldnt have an error popup due to the wilderwild mod being for both 1.21 and 1.21.1

**Screenshots**
![image](https://github.com/user-attachments/assets/49298d34-e2ac-479c-8196-5a957f72fe68)

**Logs**
[latest.log](https://github.com/user-attachments/files/17232392/latest.log)

[debug.log](https://github.com/user-attachments/files/17232397/debug.log)

**Additional context**

**Comment by AViewFromTheTop** [comment]
Please read the comment under the previous issue: https://github.com/FrozenBlock/WilderWild/issues/419#issuecomment-2389008929
It will get taken care of once the native NeoForge port is finished, we’re currently working on FrozenLib so it may be a bit

**Comment by axtrough** [comment]
when will the native neoforge port be done? would it be weeks, months?

**Comment by AViewFromTheEnd** [comment]
> when will the native neoforge port be done? would it be weeks, months?

Definitely shouldn’t be *months,* but of course no guarantee if something happens in one of our personal lives.
Realistically I’d say give it a couple weeks

**Comment by axtrough** [comment]
alright. sounds lovely. cant wait

**Comment by EfficientStinkbug** [comment]
@AViewFromTheEnd   Hey I heard that the Neoforge port got cancelled sadly because of one person. But does that mean we'll get the chance if you find another person? Because right now it seems like you've completely given up.
