### ISSUE TITLE
Thick Nether Fungi growing with + shape not working 1.21.1

### ISSUE THREAD

**Issue by guytoothpick** [FrozenBlock/WilderWild#422]
**Description of the Bug Encountered**
I know the update literally just came out lol, but When you try to grow a thick nether fungi it just deletes all the fungi or 2 fungi instead of growing the tree.

**Steps To Reproduce**
1.  Place fungi in + pattern 
2. Bonemeal
3. It poofs .-.

*this section isn't important to the report*
Again sorry for doing this so fast lol, just happened to see that you all updated it like an hour ago. But I just wanted to thank you all at Frozen Block Org for this amazing mod, I quite literally won't play minecraft without it anymore, and the newest update to it looks amazing so far! Keep up the good work!

With love and support
-Guy With A Toothpick :)

**Comment by AViewFromTheTop** [comment]
@Kluski42 ASHLYYYYYYYYYYYYYYN

**Comment by AViewFromTheTop** [comment]
on a more serious note, it seems to work for me (and ashlyn showed it working as well a while ago)
odd
![2024-10-22_01 02 26](https://github.com/user-attachments/assets/86a16483-bcf3-4ced-b9e3-4fe01121f865)

**Comment by AViewFromTheTop** [comment]
is there a specific setup you're using? I haven't been able to reproduce this

**Comment by AViewFromTheTop** [comment]
ah. it's warped fungus only. odd.

**Comment by guytoothpick** [comment]
oh no, I think I found the culprit
I finally got it to work by bonemealing the center fungi, the outer ones seem to be the problem.
Sorry!

**Comment by guytoothpick** [comment]
sorry for commenting again!
but it seems to be random? 
sorry for causing more confusion!

**Comment by AViewFromTheTop** [comment]
alright time to disable this feature and release 3.0.1

**Comment by guytoothpick** [comment]
:(
I wish you good luck!

**Comment by AViewFromTheTop** [comment]
This has been fixed by @Kluski42!
