### ISSUE TITLE
Server Non Start due to Wilder Wild/Frozen Lib 1.21

### ISSUE THREAD

**Issue by Wytchcat** [FrozenBlock/WilderWild#424]
**Description of the Bug Encountered**
3.0.2 won't open on 1.21 server

**Steps To Reproduce**
1. 
2. 
3. 
4. 

**Expected Behavior**

**Screenshots**

**Logs**
17:36:18  [Info] Immediate reason: [HARD_DEP wilderwild 3.0.2-mc1.21.1 {depends frozenlib @ [>=1.9-]}, HARD_DEP_NO_CANDIDATE frozenlib 1.9-mc1.21.1 {depends fabric-api @ [>=0.103.0+1.21.1]}, ROOT_FORCELOAD_SINGLE wilderwild 3.0.2-mc1.21.1]
17:36:18  [Info] Reason: [HARD_DEP frozenlib 1.9-mc1.21.1 {depends fabric-api @ [>=0.103.0+1.21.1]}]
17:36:18  [Info] SERVER environment disabled: [fabric-renderer-api-v1, fabric-model-loading-api-v1, fabric-keybindings-v0, modmenu, fabric-client-tags-api-v1, nemos-ambience, fabric-screen-api-v1, nether-coords, fabric-renderer-indigo, fabric-blockrenderlayer-v1, fabric-renderer-registries-v1, fabric-rendering-v0, fabric-sound-api-v1, fabric-key-binding-api-v1, fabric-rendering-v1]
17:36:18  [Info] Fix: add [], remove [], replace [[frozenlib 1.9-mc1.21.1] -> add:frozenlib 1.9- ([[1.9-,∞)])]
17:36:18  [Error] Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
- Replace mod 'FrozenLib' (frozenlib) 1.9-mc1.21.1 with version 1.9- or later that is compatible with:
- fabric-api 0.102.0+1.21
More details:
- Mod 'FrozenLib' (frozenlib) 1.9-mc1.21.1 requires version 0.103.0+1.21.1 or later of mod 'Fabric API' (fabric-api), but only the wrong version is present: 0.102.0+1.21!

**Additional context**

**Comment by AViewFromTheTop** [comment]
Please use Fabric API 0.103.0+1.21.1, as stated in the crash log. It works fine on 1.21.

**Comment by Wytchcat** [comment]
Thanks! They should note that on their damn versions list.
