### ISSUE TITLE
[1.20.1-1.20.4] Crash with Superb Steeds

### ISSUE THREAD

**Issue by MoriyaShiine** [FrozenBlock/WilderWild#432]
**Description of the Bug Encountered**
The game will crash with Superb Steeds installed on 1.20.1-1.20.4 only due to Ostriches extending AbstractHorse but not having the jump strength attribute that all other horses have. This is not an issue in 1.20.5 and above due to all living entities having the jump strength attribute, instead of just horses.

**Steps To Reproduce**
1. Have both mods installed
2. Have an Ostrich tick
3. Game crashes

**Expected Behavior**
The game should not crash

**Logs**
Relevant issue (with log included) [here](https://github.com/MoriyaShiine/superb-steeds/issues/6)

**Additional context**
A simple fix for this would be to just give Ostriches a default jump strength, probably 0 since I can assume it's never used. This would also fix crashes with any other mod that assumes a horse will have the jump strength attribute.

**Comment by AViewFromTheTop** [comment]
I thought I fixed this months ago wtf 💀
guess I never pushed the commit and it somehow reverted idk

**Comment by MoriyaShiine** [comment]
lol nice

**Comment by AViewFromTheTop** [comment]
ok time to fix this

**Comment by AViewFromTheTop** [comment]
fixed
