### ISSUE TITLE
Kicked from server/Packet mismatch

### ISSUE THREAD

**Issue by Dalethium** [FrozenBlock/WilderWild#433]
**Description of the Bug Encountered**
Occasionally you will get kicked from a server due to a wilder-wild packet.

**Steps To Reproduce**
NA/inconsistent

**Logs**

[latest.txt](https://github.com/user-attachments/files/17602343/mjka7wz.txt)

**Additional context**
I understand that this is relatively vague, but if the latest log is not enough information, please let me know, and I'll try to provide any information you can ask me for.

**Comment by AViewFromTheTop** [comment]
That’s certainly… strange. It’s related to the leaf particles, specifically the big cluster of maple leaves that spawn and make a leaf litter when they hit the floor.
Would you be able to reproduce this in singleplayer, if it isn’t already?

**Comment by Dalethium** [comment]
I loaded up the same world in single player where I was crashing, and I didn't appear to crash. I will note that I tried disabling the leaves mix in the configs to try to fix this, but it doesn't appear to have fixed it. 

If you're unable to track this down, could we maybe have a config to disable this packet/feature from being sent entirely?

**Comment by Dalethium** [comment]
Is it possible there's a null check missing for the resource ID? The stream seems to fail when reading the resource identifier. The resource location could be blank due to another mod in my pack and could cause an unexpected number of bytes? Just a guess from a glance.

**Comment by AViewFromTheTop** [comment]
Thing is, there’s no reason it should be null- and everywhere it’s called in WW, it’s not null. Otherwise it would crash and this would’ve been fixed a month or two ago when it was in development.

**Comment by Dalethium** [comment]
I could be way off base, but I think this should work. It seems to have fixed it on my server.
