### ISSUE TITLE
[ QUESTION ] Version of Fabric Loom via Wilder Wild 1.20.1

### ISSUE THREAD

**Issue by Xelbayria** [FrozenBlock/WilderWild#438]
Hello, 
I have a question, is it possible for you to apply Loom 1.6+ for Wilder Wild, so I can continue support it via **Every Compat**. I had some issue with "Fabric Loom v1.7+" on 1.20.1

I would like to hear your option on this. Meanwhile I am waiting for your response, i'll try again to see if I can update Every Compat to use Loom 1.7+

**Comment by AViewFromTheTop** [comment]
Unfortunately not, certain things we’ve imported as dependencies use 1.7+ if I remember correctly. Currently we’re using the latest 1.8 releases, which seem pretty stable. 1.6 wasn’t as stable for us, and 1.8 wasn’t as stable until a later hotfix.

**Comment by Xelbayria** [comment]
I see. What about older version of Wilder Wild that use Loom 1.6+? That's the only solution I can think of.

**Comment by AViewFromTheTop** [comment]
Wilder Wild has significant changes outside bug fixes each major update, and 3.0 has a TON of refactoring- unfortunately it isn’t viable to do without immediately crashing on launch.

**Comment by Xelbayria** [comment]
I'm aware of the changes in Wilder Wild (WW). I noticed there are changed names in Class and a few more things. I'll try v3.0.0 (assuming it's using 1.6+) 

i'll also try to update EveryCompat to use Loom 1.7+.

**Comment by AViewFromTheTop** [comment]
1.8 would be optimal, but I believe Arch Loom hasn't updated to it yet unfortunately

**Comment by Xelbayria** [comment]
> 1.8 would be optimal, but I believe Arch Loom hasn't updated to it yet unfortunately

Yea. I'm aware of it. I'm going to switch EveryCompat to use Multi-loader setup.
