### ISSUE TITLE
Snow on snowlogged blocks is bugged when using Embeddium 1.20.1

### ISSUE THREAD

**Issue by Eggmanplant** [FrozenBlock/WilderWild#442]
**Description of the Bug Encountered**
Snow on snowlogged blocks is bugged when using Embeddium 1.20.1

**Steps To Reproduce**
1. Install Embeddium and Wilder Wild for 1.20.1
2. Place snow on grass or any flower
3. The snow is bugged

**Expected Behavior**
The block is showing properly

**Comment by AViewFromTheTop** [comment]
I used to do Embeddium support but removed it as the mod is no longer being maintained for Fabric. This is not planned.
