### ISSUE TITLE
Magma Caves

### ISSUE THREAD

**Issue by Osmiooo** [FrozenBlock/WilderWild#52]
Basically a volcano biome but to make it more interesting we could make it underground, so a cave biome, having the first real cave wood type, a sort of burnt wood, it would need more things to make more interesting of course, but I think it has potential

**Comment by Treetrain1** [comment]
> > fuck it lets just make the ancient city center piece a nether portal and lead to the nether
> 
> end*

nether

**Comment by Osmiooo** [comment]
> > > fuck it lets just make the ancient city center piece a nether portal and lead to the nether
> > 
> > 
> > end*
> 
> nether

susland*
