### ISSUE TITLE
Bugs and other things

### ISSUE THREAD

**Issue by Soro335** [FrozenBlock/WilderWild#57]
- [x] Add usage for milkweed pod (possibly crafting material)
- [x] Sort items and blocks in creative inventory 

- [x] Fix missing and placeholder textures
- [x] Fix baobab saplings
- [x] Add new colors for cypress wetlands biome
- [x] Invert Sculk Sensor's "not_hiccupping" blockstate and rename it to "hiccupping" (we could make it an integer blockstate and use 0 and 1 instead of true and false if that works better for you)
- [x] Add usage for bottle with firefly 
- [x] Fix ancient horn using animation 
- [x] Fix swamp hut fences(it must connect)
- [x] Super Mario

**Comment by BluePhoenixLOL** [comment]
> - [ ] Add new colors for cypress wetlands biome
ok i tried doing this but you said please keep them as is, what do you want? should i just remove this?

**Comment by BluePhoenixLOL** [comment]
I think milkweed pods could be used as a covering bonemeal, just like bee pollen, but even though it covers a lot, its not as strong as normal bonemeal, so you might need 2 or 3 to make them grow a level.

**Comment by MerpisMe** [comment]
we could make milkweed pods craft into string or white dye or something like that, i think that might make sense

**Comment by MerpisMe** [comment]
> * [ ]  Sort items and blocks in creative inventory

bump
is there any way we could possibly sort the stuff into the correct spots in fabric? i know quilt can do that
