### ISSUE TITLE
Possible Features for Future Releases

### ISSUE THREAD

**Issue by AViewFromTheTop** [FrozenBlock/WilderWild#77]
- [ ] Ostriches (Come up with what their use would be first. If not, don’t bother adding them.)
- [ ] Meerkats (Same deal as Ostriches. They also seem quite useless, so don’t bother adding them if we can’t come up with a use.)
- [x] Stone Chests (Old Ancient City concept. Can only be opened by pushing the lid, which makes lots of noise.)
- [x] Palm Trees & Wood Set
- [ ] Prickly Pears
- [ ] Vultures (Would use GameEvent listeners to detect deaths up to 32 blocks away, scan for items in that area, and try to steal if possible. Or, it could possibly pick up bodies.) 
- [ ] Hanging tendrils break when shot
- [x] Assign tool to null block
- [x] Copper horn
- [ ] More Birch Changes (Leave shape change?)

**Comment by AViewFromTheTop** [comment]
I don’t really think we should do that, ANY viable crafting recipe would lead to instant chaos on smps

**Comment by MerpisMe** [comment]
> I don’t really think we should do that, ANY viable crafting recipe would lead to instant chaos on smps

well i was thinking something stupidly difficult like:
(catalyst = C, deepslate = D, netherite block = N)
[C] [N] [C]
[C] [D] [C]
[C] [N] [C]

**Comment by AViewFromTheTop** [comment]
Any new recipe with Netherite is a no from me

**Comment by MerpisMe** [comment]
> Any new recipe with Netherite is a no from me

ok fair because lore, but how else do we make it extremely difficult to craft? no other block in the game has as much contained value/rarity as a netherite block

**Comment by MerpisMe** [comment]
also, netherite would explain the reinforced part as well

**Comment by SuperNolax** [comment]
make sure the palm logs dont have tree rings to parity with real life if you add palm, also the palms you see in floridia are trimmed so make palm leaf placement chaotic, there could also be coconut palms and banana palms (they all use the same woodtype)
normal palms can be found in beach jungle or oasis biomes, coconut palm could be found in beach or oasis biomes, banana palm could be found in jungle biomes, also an oasis biome, these would spawn rarely in the desert with buried treasure, or the rare fishing dock.
