### ISSUE TITLE
Ancient Stone Chests unique "Sculked" set of textures

### ISSUE THREAD

**Issue by MerpisMe** [FrozenBlock/WilderWild#89]
would be kinda cool if stone chests with the "ancient chest" blockstate had a unique texture or something. not really necessary but would be neat

**Comment by MerpisMe** [comment]
also is that like even possible or something

**Comment by MerpisMe** [comment]
i still need to make the double texture so im reopening this

**Comment by Xfrtrex** [comment]
wait but those dont spawn right?

**Comment by MerpisMe** [comment]
they do now, in the city center

**Comment by Xfrtrex** [comment]
wait wha

**Comment by MerpisMe** [comment]
yeah we gave that one empty room that looks like it'd be a chest room a use so now it has a double stone chest in it

**Comment by Xfrtrex** [comment]
Oh nice, I thought it served its purpose of teaching players Redstone mechanics, but this is nice, I would always just loot all the redstone stuff, even though i would never use it since i know nothing about redstone lol

**Comment by MerpisMe** [comment]
yeah it felt anticlimactic for being a secret area, so giving it unique loot would be nice

speaking of which @AViewFromTheTop should we instead make ancient horns exclusively generate in the city center chest, but still be fairly rare?

**Comment by AViewFromTheTop** [comment]
> yeah it felt anticlimactic for being a secret area, so giving it unique loot felt right
> 
> speaking of which @AViewFromTheTop should we instead make ancient horns exclusively generate in the city center secret area chest, but still make it fairly rare?

NO. The reason I didn't do that to begin with is simple:
Where does the danger come from in the Ancient Cities. The center, with hardly any Sculk, or the entire rest of the City combined?
Forcing players to explore the city as much as possible significantly raises the chances of summoning a Warden. If Horns were always found in the center, someone can easily take the path directly to the center, get a guaranteed horn, and walk out with no harm.
In fact, I think we need to make a separate loot table for the center with no Horns, as I'm using the regular table for one of the chests in there.

**Comment by AViewFromTheTop** [comment]
On this topic. it makes complete sense why the portal doesn't work when thinking of Cities this way. However, that also shows a big flaw in their design- there's not much to do. There's a VERY limited amount of structures to visit and a very limited amount of time players will actually have fun in before getting bored of Cities.
I'd recommend at least doubling the size of cities to fix this, while making Horns rarer AND adding a second item that'd make the trip absolutely worth it.

**Comment by AViewFromTheTop** [comment]
NOW, going back on my point about the portal. It would work if there's a new key to open it that's only going to be in a SINGLE chest in the city. THAT would definitely motivate players to check each chest.
Mojang isn't going to just randomly toss in a dimension unannounced and without snapshots (let's be real here, that's a terrible idea anyway. I'm looking at YOU, 90% of the Minecraft community,) so we don't have that right now- and we don't know if we will.
Either way, if that does end up getting added, Ancient Cities better be at least two or three times bigger to compensate for it. It'd be a lot more fun that way.

**Comment by Xfrtrex** [comment]
idk what lunade thinks bc im too lazy to read his essay long messages, i heard portal, sure lets add a portal /j

**Comment by Xfrtrex** [comment]
please dont get offended this is a joke

**Comment by MerpisMe** [comment]
> > yeah it felt anticlimactic for being a secret area, so giving it unique loot felt right
> > speaking of which @AViewFromTheTop should we instead make ancient horns exclusively generate in the city center secret area chest, but still make it fairly rare?
> 
> NO. The reason I didn't do that to begin with is simple: Where does the danger come from in the Ancient Cities? The center, with hardly any Sculk, or the entire rest of the City combined? Forcing players to explore the city as much as possible significantly raises the chances of summoning a Warden. If Horns were always found in the center, someone can easily take the path directly to the center, get a guaranteed horn, and walk out with no harm. In fact, I think we need to make a separate loot table for the center with no Horns, as I'm using the regular table for one of the chests in there.

fair enough!

> On this topic. it makes complete sense why the portal doesn't work when thinking of Cities this way. Having the biggest piece of loot sitting flat in the center with the least amount of protection (compared to the rest of the city) would mostly defeat the purpose of the city itself.
> 
> However, that also shows a big flaw in their design- there's not much to do. There's a VERY limited amount of structures to visit and a very limited amount of time players will actually have fun in before getting bored of Cities. 

agreed, feels very repetitive after a few runs

>I'd recommend at least doubling the size of cities to fix this,

YES

> while making Horns rarer AND adding a second item that'd make the trip absolutely worth it. There's obviously more to do, but that's a start. Cities shouldn't be a one-stop-trip, you should feel inclined to visit it a few times at a minimum.

i'm sold on this idea let's do it

**Comment by AViewFromTheTop** [comment]
> idk what lunade thinks bc im too lazy to read his essay long messages, i heard portal, sure lets add a portal /j

basically ancient cities are boring because they have nothing to do
making them bigger and having more than just the horn available would make them more fun

**Comment by AViewFromTheTop** [comment]
either way this is going to absolutely be for the next update
i dont even KNOW where to start for expanding cities, let's not waste our time on it right now

**Comment by MerpisMe** [comment]
well, we ran a poll on the discord and 20-something people agreed that they would prefer we delay 1.1 if they get more stuff, so we may be able to pull that off in 1.1

**Comment by Treetrain1** [comment]
> either way this is going to absolutely be for the next update i dont even KNOW where to start for expanding cities, let's not waste our time on it right now

minecraft has a structure size limit of 128
will have to figure out how to get around that somehow or increase the limit
if we do decide to work on that
