### ISSUE TITLE
1.1 Changelog

### ISSUE THREAD

**Issue by MerpisMe** [FrozenBlock/WilderWild#92]
# FEATURES
- Added Display Lantern block
- Added Ancient Horn Fragment
- Added Stone Chests
- Added Copper Horns
- Added Jellyfish
- Added Mesoglea blocks
- Added Nematocyst blocks
- Added Abandoned Cabins

## JELLYFISH CAVES
A flooded, mysteriously beautiful biome hiding beneath the ocean floor.
- Filled with shallow water pools.
- Home to the two pearlescent Jellyfish.
- Nematocyst frequently generates around the biome.
- Mesoglea patches decorate the floors and ceilings.
- Calcite blobs will sometimes generate here.

### DISPLAY LANTERN
A stylish hanging container!
- Can hold up to one item or four Fireflies at a time.
- Each Firefly inside will emit a bit of light, and light-emitting blocks inside will emit their expected levels of light.
- Can be used to display items and Fireflies in a fashionable way.

### MESOGLEA
A context-dependent semi-permeable block!
- Are found generating naturally in Jellyfish Caves.
- When waterlogged, will allow all mobs to swim through it.
- Emits a light level of 7.
- Can be crafted with four Nematocyst of the same color.

### NEMATOCYST
An atmospheric cluster.
- Can be placed on all faces of blocks and emits light.
- Can be crafted into Mesoglea.
- Dropped by Jellyfish, taking on the respective color

### STONE CHEST
A new type of chest with a heavy lid, found in the ruins of Ancient Cities.
- Can be crafted with Cobbled Deepslate in the shape of a Boat, and three Cobbled Deepslate Slabs on top.
- Hoppers can neither pull nor insert items from/into Stone Chests.
- The Stone Chest's heavy lid must be lifted with careful strength. Once lifted high enough, you only have a short amount of time before the lid tips and slams shut.
- All loot will shatter and crumble if the Stone Chest is broken. Note that this only applies to loot generated by loot tables; items placed in Stone Chests by players will not be lost.

### JELLYFISH
A new venomous and gelatinous mob!
- Come in multiple colors.
- Are passive but will sting anything that comes into contact with them.
- - However, will chase after attackers if provoked
- Like all other fish, Jellyfish can be scooped into buckets.
- Drop Nematocyst upon death.

### COPPER HORN
A new tube for your windy desires.
- Will play a single note when used, which will loop until the player stops using it.
- The pitch of the note depends on how high you're looking.

### ANCIENT HORN FRAGMENT
- Takes the place of the Ancient Horn in ancient city loot
- Can be crafted into an ancient horn if combined with gold ingots and echo shards 

### ABANDONED CABINS
A small room. In Your Room.
- Generate sparsely throughout the underground world.
- Contain Barrels and Stone Chests waiting to be looted.

### BIOME CHANGES
- Beta Beaches have been reintroduced!
- Added dying trees!
- Added large fern and tall grass feature to taiga biomes!

### BLOCK CHANGES
- Cacti can now be mined faster with an axe.
- Pointed Dripstone dripping water onto dirt will now convert it to Mud.
- Reinforced Deepslate can now be rotated like Deepslate.
- The stems of Dripleaves can now properly be powered.
- Gravel now has its own custom sounds!
- Clay now has its own custom sounds!
- Soul Fire now has its own custom ambient sounds!
- Sculk slabs, stairs, and walls will now be converted into Sculk whenever a Sculk Charge passes over compatible stairs, slabs, or walls in non-worldgen scenarios.
- Dripstone can now convert Dirt into Mud.
- Dripstone can dry out Sponges.

### GOAT HORN
 - Now only play while the button is held, stopping if released. 
 - No more cooldown.

### LUNADE - THE OTHER SIDE
- The "Lunade - The Other Side" music disc has been renamed to "Lunade - Back" to prevent confusion with the "Lena Raine - Otherside" music disc.

### ANCIENT HORN
- No longer generates naturally within chests, replaced by Ancient Horn Fragments

## ENTITY CHANGES
- Projectiles will now create block particles upon landing.
- The Enderman's staring sound will now follow its position and stop upon death.

# CONFIG
- Completely revamped and split into four sections: Blocks, Items, Entities, and Worldgen.
- Added many, many new config toggles for features in the mod

### BLOCK CONFIG
- Sculk Sensor Tendrils (Vanilla/MC Live 2020)
- Shrieker Gargling
- Custom Soul Fire Sounds

### ENTITY CONFIG
- Entities walk over rails?
- Warden Death Animation
- Warden Emerges from Spawn Egg
- Warden Swim Animation
- Warden Custom Tendril Animation

### ITEM CONFIG
- Ancient Horn shatters glass
- Ancient Horn can summon Warden from player-placed Shriekers
- Projectiles make block break particles on impact

### WORLDGEN CONFIG
- Windswept Savanna Biome Placement
- Jungle Biome Placement
- Swamp Placement
- Mangrove Swamp Placement
- Beta Beach generation
- Fallen Log generation
- Wilder Wild tree generation
- Wilder Wild foliage generation

non-description
- Presence Footsteps Compatibility
- Misc Texture Fixes
- Added Block breaking particles when arrows hit blocks.
- Baobab Saplings have been replaced with Baobab Nuts
- New Shelf Fungus loot tables
- New Sculk Spreading

**Comment by AViewFromTheTop** [comment]
i don't get the point of prickly pears
if it was the actual type of cactus from the biome vote and not a food then i'd agree

**Comment by MerpisMe** [comment]
they're not fully implemented yet

**Comment by AViewFromTheTop** [comment]
> they're not fully implemented yet

yes

**Comment by MerpisMe** [comment]
we plan on making a new kind of cactus that they grow on but im lazy

**Comment by AViewFromTheTop** [comment]
> we plan on making a new kind of cactus that they grow on but im lazy

YOU NEED A TIMEKILLER AND YOU DONT UNDERSTAND

**Comment by AViewFromTheTop** [comment]
i know ive said this lots but once again, i'm glad with how uncheesable stone chests are

**Comment by AViewFromTheTop** [comment]
Let’s make vibrations caused by then go through wool

**Comment by MerpisMe** [comment]
> Let’s make vibrations caused by them go through wool

ehhhh i dunno, i think that would be a little over the top since the whole idea is to take necessary precautions, which includes wool
we want to make them uncheesable, not impossible

**Comment by AViewFromTheTop** [comment]
> ehhhh i dunno, i think that would be a little over the top since the whole idea is to take necessary precautions, which includes wool we want to make them uncheesable, not impossible

It’s a joke ik that the wool thing is intentional game design
Though it’d be hilarious to add considering thunder is somehow nonexistent if there’s wool

**Comment by AViewFromTheTop** [comment]
Btw I also realized that Stone Chests prevent the whole open-and-steal-before-sensors-can-detect-another-vibration thing and I love them even more

**Comment by MerpisMe** [comment]
> Btw I also realized that Stone Chests prevent the whole open-and-steal-before-sensors-can-detect-another-vibration thing and I love them even more

ohhh true

**Comment by AViewFromTheTop** [comment]
They solve quite a few problems I have with Ancient Cities seriously why didn’t Mojang just go ahead and add them

**Comment by MerpisMe** [comment]
> They solve quite a few problems I have with Ancient Cities seriously why didn’t Mojang just go ahead and add them

i'm guessing either time constraints, or they didnt really see a point
and if they didnt really see a point then it's obvious that it never got past the concept phase because they were simply too skeptical

**Comment by AViewFromTheTop** [comment]
“Time Constraints”
We literally made them in like three days Mojang had two years

**Comment by BluePhoenixLOL** [comment]
> i don't get the point of prickly pears if it was the actual type of cactus from the biome vote and not JUST a food then i'd agree

i am removing them, we didnt have time to design them, i think we will add them in 1.2 along with other badlands stuff and deserts

**Comment by BluePhoenixLOL** [comment]
> “Time Constraints” We literally made them in like three days Mojang had two years

thats a stupid arguement, you clearly understand nothing about game development. way different.

**Comment by BluePhoenixLOL** [comment]
https://www.youtube.com/watch?v=dJVBNAqieDM&t=6s&ab_channel=MinecraftIdeasAcademy

**Comment by Osmiooo** [comment]
> “Time Constraints” We literally made them in like three days Mojang had two years

To make an update, they need to come up with creative ideas, add a use for every block they add (except wood variants and things like that), balance everything out and make the same stuff on bedrock too
It's literally not the same

**Comment by BluePhoenixLOL** [comment]
> > “Time Constraints” We literally made them in like three days Mojang had two years
> 
> To make an update, they need to come up with creative ideas, add a use for every block they add (except wood variants and things like that), balance everything out and make the same stuff on bedrock too It's literally not the same

not even that, tons more, tons of designing which is harder then you think. just watch that video

**Comment by Osmiooo** [comment]
> not even that, tons more, tons of designing which is harder then you think. just watch that video

Yeah I was just listing quick stuff

**Comment by BluePhoenixLOL** [comment]
https://www.youtube.com/watch?v=vXaWOJTCYNg

**Comment by AViewFromTheTop** [comment]
> > “Time Constraints” We literally made them in like three days Mojang had two years
> 
> thats a stupid arguement, you clearly understand nothing about game development. way different.

The difference is that Mojang already HAD the idea
they've had the idea for over nine entire months
if a modder can implement said idea in three days, you know the issue isn't time constraints
you can stop slandering me now
don't even try this with me

**Comment by AViewFromTheTop** [comment]
That goes for both of you.
You can't just follow blindly Mojang's bullshit claims of "modders don't have quality because we have 8,000 iterations" claims and prance around with that flag in your mouth.
The point is, Mojang PUBLICIZED an iteration of Stone Chests. Right? Right.
Now, within about three days, we've implemented another iteration of them that seems to fit the Ancient City's intended philosophy. Right? Right.
Mojang, having planned Ancient Cities for about two months (or possibly more) before Minecraft Live, had obviously already considered Stone Chests. They ALREADY had the iterations in place, and the update would've release for around ANOTHER nine months. They HAD the time for it, they DECIDED not to put their time into it. They'd decided to scrap Stone Chests long before Minecraft Live.
If three days is all it takes to get them mostly working, time constraints are not the problem.

**Comment by AViewFromTheTop** [comment]
> To make an update, they need to come up with creative ideas, add a use for every block they add (except wood variants and things like that), balance everything out and make the same stuff on bedrock too It's literally not the same

dude stone chests are literally click multiple times and then it opens they'd work just fine considering THATS HOW CHESTS OPEN ANYWAY

**Comment by AViewFromTheTop** [comment]
I took this way too personally sorry

**Comment by AViewFromTheTop** [comment]
this update adds a lot bruh

**Comment by AViewFromTheTop** [comment]
when release

**Comment by Treetrain1** [comment]
> when release

after #146 :trollface:

**Comment by Osmiooo** [comment]
> when release

before january 1st 2100

**Comment by MerpisMe** [comment]
we're planning on doing it sometime after wattles' next video. we could maybe even do it the day of if we can coordinate it with him, that'd be a really good way to promote the update

**Comment by AViewFromTheTop** [comment]
we really shouldn't care about terrablender

**Comment by AViewFromTheTop** [comment]
honestly we should just hand out the build after merp pushes the new rgb commit to testers to find any bugs at this point

**Comment by AViewFromTheTop** [comment]
also the mod's description is going to be fucking hilariously massive

**Comment by Osmiooo** [comment]
what if we just put all the features themselves in the mod description and then link towards a pastebin or something where everything is explained in details

**Comment by AViewFromTheTop** [comment]
> what if we just put all the features themselves in the mod description and then link towards a pastebin or something where everything is explained in details

nah that ruins both the authenticity and the joke

**Comment by AViewFromTheTop** [comment]
@MerpisMe yooo thanks for the new formatting!!

**Comment by MerpisMe** [comment]
> @MerpisMe yooo thanks for the new formatting!!

spongerobert

**Comment by AViewFromTheTop** [comment]
> > @MerpisMe yooo thanks for the new formatting!!
> 
> spongerobert

petite grian
