### ISSUE TITLE
Feedback on Sound Design

### ISSUE THREAD

**Issue by MerpisMe** [FrozenBlock/WilderWild#97]
### Discussed in https://github.com/Soro335/WilderWild/discussions/96

<div type='discussions-op-text'>

<sup>Originally posted by **MerpisMe** August 18, 2022</sup>
Please provide feedback (either positive or negative) regarding the sound design. Anything you like? Dislike? Would like to see changed? Let me know!</div>

**Comment by AViewFromTheTop** [comment]
The Ancient Loot Crumbles sound should be more crumbly with shard sounds (think glass shards hitting hard rock) instead of basalt

Stone Chest closing sound should sound more natural and rock-like, with a more ping-like slam sound layered with bit more crumbling, with a more bass-heavy and instant slam

if forgot the other things i was thinking of

**Comment by AViewFromTheTop** [comment]
all new ambient sounds must have timekiller echoing in them

**Comment by AViewFromTheTop** [comment]
timekiller music disc

**Comment by MerpisMe** [comment]
> The Ancient Loot Crumbles sound should be more crumbly with shard sounds (think glass shards hitting hard rock) instead of basalt

they werent really finished when i initially pushed them, i will definitely take this into consideration

> Stone Chest closing sound should sound more natural and rock-like, with a more ping-like slam sound layered with bit more crumbling, with a more bass-heavy and instant slam

sure but can you record a bunch of rock scraping sounds for me so i dont have to sample the like two sounds from the audio library i'm using
i literally dont have a mic so i cant do that myself lol

**Comment by MerpisMe** [comment]
> all new ambient sounds must have timekiller echoing in them

ok but seriously what are your thoughts on the new ambient sounds and stuff i'm genuinely curious

**Comment by AViewFromTheTop** [comment]
i don't have rocks to scrape and my mics will pick up a ton of random stuff in the background
they're acoustic guitar/drum mics not rock scraping mics

**Comment by AViewFromTheTop** [comment]
> ok but seriously what are your thoughts on the new ambient sounds and stuff i'm genuinely curious

never heard them

**Comment by MerpisMe** [comment]
> > ok but seriously what are your thoughts on the new ambient sounds and stuff i'm genuinely curious
> 
> never heard them

i completely redid lush caves and i added additions to dripstone caves if you wanna give them a listen
i will probably end up redoing the additions for dripstone caves because i dont like them

**Comment by AViewFromTheTop** [comment]
@MerpisMe freesound.org btw

**Comment by MerpisMe** [comment]
> @MerpisMe freesound.org btw

yeah i guess so

**Comment by AViewFromTheTop** [comment]
https://freesound.org/people/Debsound/sounds/437602/
https://freesound.org/people/NeoSpica/sounds/512243/
https://freesound.org/people/Bertsz/sounds/524312/ (FUNNY)

**Comment by AViewFromTheTop** [comment]
i should mention though, i don't think the stone chest sounds should change TOO much
they just need some tweaks and that's really it, the slamming sound should maybe be the only one to change that much
